//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace TestIntegraMobileWS.integraMobileWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="integraMobileWSSoap", Namespace="http://tempuri.org/")]
    public partial class integraMobileWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingTariffsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationWithTimeStepsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationForMinutesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUnParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUnParkingOperationQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmUnParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFinePaymentQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmFinePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmUserDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateHashOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public integraMobileWS() {
            this.Url = global::TestIntegraMobileWS.Properties.Settings.Default.TestIntegraMobileWS_integraMobileWS_integraMobileWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryLoginCompletedEventHandler QueryLoginCompleted;
        
        /// <remarks/>
        public event QueryCityCompletedEventHandler QueryCityCompleted;
        
        /// <remarks/>
        public event QueryRechargeCompletedEventHandler QueryRechargeCompleted;
        
        /// <remarks/>
        public event ConfirmRechargeCompletedEventHandler ConfirmRechargeCompleted;
        
        /// <remarks/>
        public event QueryParkingTariffsCompletedEventHandler QueryParkingTariffsCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationCompletedEventHandler QueryParkingOperationCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationWithTimeStepsCompletedEventHandler QueryParkingOperationWithTimeStepsCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationForMinutesCompletedEventHandler QueryParkingOperationForMinutesCompleted;
        
        /// <remarks/>
        public event ConfirmParkingOperationCompletedEventHandler ConfirmParkingOperationCompleted;
        
        /// <remarks/>
        public event QueryUnParkingOperationCompletedEventHandler QueryUnParkingOperationCompleted;
        
        /// <remarks/>
        public event QueryUnParkingOperationQuantityCompletedEventHandler QueryUnParkingOperationQuantityCompleted;
        
        /// <remarks/>
        public event ConfirmUnParkingOperationCompletedEventHandler ConfirmUnParkingOperationCompleted;
        
        /// <remarks/>
        public event QueryFinePaymentQuantityCompletedEventHandler QueryFinePaymentQuantityCompleted;
        
        /// <remarks/>
        public event ConfirmFinePaymentCompletedEventHandler ConfirmFinePaymentCompleted;
        
        /// <remarks/>
        public event ConfirmUserDataCompletedEventHandler ConfirmUserDataCompleted;
        
        /// <remarks/>
        public event CalculateHashCompletedEventHandler CalculateHashCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryLogin(string xmlIn) {
            object[] results = this.Invoke("QueryLogin", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryLoginAsync(string xmlIn) {
            this.QueryLoginAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryLoginAsync(string xmlIn, object userState) {
            if ((this.QueryLoginOperationCompleted == null)) {
                this.QueryLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryLoginOperationCompleted);
            }
            this.InvokeAsync("QueryLogin", new object[] {
                        xmlIn}, this.QueryLoginOperationCompleted, userState);
        }
        
        private void OnQueryLoginOperationCompleted(object arg) {
            if ((this.QueryLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryLoginCompleted(this, new QueryLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryCity(string xmlIn) {
            object[] results = this.Invoke("QueryCity", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCityAsync(string xmlIn) {
            this.QueryCityAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryCityAsync(string xmlIn, object userState) {
            if ((this.QueryCityOperationCompleted == null)) {
                this.QueryCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCityOperationCompleted);
            }
            this.InvokeAsync("QueryCity", new object[] {
                        xmlIn}, this.QueryCityOperationCompleted, userState);
        }
        
        private void OnQueryCityOperationCompleted(object arg) {
            if ((this.QueryCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCityCompleted(this, new QueryCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryRecharge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryRecharge(string xmlIn) {
            object[] results = this.Invoke("QueryRecharge", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryRechargeAsync(string xmlIn) {
            this.QueryRechargeAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryRechargeAsync(string xmlIn, object userState) {
            if ((this.QueryRechargeOperationCompleted == null)) {
                this.QueryRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryRechargeOperationCompleted);
            }
            this.InvokeAsync("QueryRecharge", new object[] {
                        xmlIn}, this.QueryRechargeOperationCompleted, userState);
        }
        
        private void OnQueryRechargeOperationCompleted(object arg) {
            if ((this.QueryRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryRechargeCompleted(this, new QueryRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmRecharge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmRecharge(string xmlIn) {
            object[] results = this.Invoke("ConfirmRecharge", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmRechargeAsync(string xmlIn) {
            this.ConfirmRechargeAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmRechargeAsync(string xmlIn, object userState) {
            if ((this.ConfirmRechargeOperationCompleted == null)) {
                this.ConfirmRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmRechargeOperationCompleted);
            }
            this.InvokeAsync("ConfirmRecharge", new object[] {
                        xmlIn}, this.ConfirmRechargeOperationCompleted, userState);
        }
        
        private void OnConfirmRechargeOperationCompleted(object arg) {
            if ((this.ConfirmRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmRechargeCompleted(this, new ConfirmRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingTariffs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingTariffs(string xmlIn) {
            object[] results = this.Invoke("QueryParkingTariffs", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingTariffsAsync(string xmlIn) {
            this.QueryParkingTariffsAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingTariffsAsync(string xmlIn, object userState) {
            if ((this.QueryParkingTariffsOperationCompleted == null)) {
                this.QueryParkingTariffsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingTariffsOperationCompleted);
            }
            this.InvokeAsync("QueryParkingTariffs", new object[] {
                        xmlIn}, this.QueryParkingTariffsOperationCompleted, userState);
        }
        
        private void OnQueryParkingTariffsOperationCompleted(object arg) {
            if ((this.QueryParkingTariffsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingTariffsCompleted(this, new QueryParkingTariffsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingOperation(string xmlIn) {
            object[] results = this.Invoke("QueryParkingOperation", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationAsync(string xmlIn) {
            this.QueryParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationAsync(string xmlIn, object userState) {
            if ((this.QueryParkingOperationOperationCompleted == null)) {
                this.QueryParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperation", new object[] {
                        xmlIn}, this.QueryParkingOperationOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationOperationCompleted(object arg) {
            if ((this.QueryParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationCompleted(this, new QueryParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperationWithTimeSteps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingOperationWithTimeSteps(string xmlIn) {
            object[] results = this.Invoke("QueryParkingOperationWithTimeSteps", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationWithTimeStepsAsync(string xmlIn) {
            this.QueryParkingOperationWithTimeStepsAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationWithTimeStepsAsync(string xmlIn, object userState) {
            if ((this.QueryParkingOperationWithTimeStepsOperationCompleted == null)) {
                this.QueryParkingOperationWithTimeStepsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationWithTimeStepsOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperationWithTimeSteps", new object[] {
                        xmlIn}, this.QueryParkingOperationWithTimeStepsOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationWithTimeStepsOperationCompleted(object arg) {
            if ((this.QueryParkingOperationWithTimeStepsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationWithTimeStepsCompleted(this, new QueryParkingOperationWithTimeStepsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperationForMinutes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int QueryParkingOperationForMinutes(string xmlIn) {
            object[] results = this.Invoke("QueryParkingOperationForMinutes", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationForMinutesAsync(string xmlIn) {
            this.QueryParkingOperationForMinutesAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationForMinutesAsync(string xmlIn, object userState) {
            if ((this.QueryParkingOperationForMinutesOperationCompleted == null)) {
                this.QueryParkingOperationForMinutesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationForMinutesOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperationForMinutes", new object[] {
                        xmlIn}, this.QueryParkingOperationForMinutesOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationForMinutesOperationCompleted(object arg) {
            if ((this.QueryParkingOperationForMinutesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationForMinutesCompleted(this, new QueryParkingOperationForMinutesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmParkingOperation(string xmlIn) {
            object[] results = this.Invoke("ConfirmParkingOperation", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmParkingOperationAsync(string xmlIn) {
            this.ConfirmParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmParkingOperationAsync(string xmlIn, object userState) {
            if ((this.ConfirmParkingOperationOperationCompleted == null)) {
                this.ConfirmParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmParkingOperationOperationCompleted);
            }
            this.InvokeAsync("ConfirmParkingOperation", new object[] {
                        xmlIn}, this.ConfirmParkingOperationOperationCompleted, userState);
        }
        
        private void OnConfirmParkingOperationOperationCompleted(object arg) {
            if ((this.ConfirmParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmParkingOperationCompleted(this, new ConfirmParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryUnParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryUnParkingOperation(string xmlIn) {
            object[] results = this.Invoke("QueryUnParkingOperation", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationAsync(string xmlIn) {
            this.QueryUnParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationAsync(string xmlIn, object userState) {
            if ((this.QueryUnParkingOperationOperationCompleted == null)) {
                this.QueryUnParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUnParkingOperationOperationCompleted);
            }
            this.InvokeAsync("QueryUnParkingOperation", new object[] {
                        xmlIn}, this.QueryUnParkingOperationOperationCompleted, userState);
        }
        
        private void OnQueryUnParkingOperationOperationCompleted(object arg) {
            if ((this.QueryUnParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUnParkingOperationCompleted(this, new QueryUnParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryUnParkingOperationQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int QueryUnParkingOperationQuantity(string xmlIn) {
            object[] results = this.Invoke("QueryUnParkingOperationQuantity", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationQuantityAsync(string xmlIn) {
            this.QueryUnParkingOperationQuantityAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationQuantityAsync(string xmlIn, object userState) {
            if ((this.QueryUnParkingOperationQuantityOperationCompleted == null)) {
                this.QueryUnParkingOperationQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUnParkingOperationQuantityOperationCompleted);
            }
            this.InvokeAsync("QueryUnParkingOperationQuantity", new object[] {
                        xmlIn}, this.QueryUnParkingOperationQuantityOperationCompleted, userState);
        }
        
        private void OnQueryUnParkingOperationQuantityOperationCompleted(object arg) {
            if ((this.QueryUnParkingOperationQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUnParkingOperationQuantityCompleted(this, new QueryUnParkingOperationQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmUnParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmUnParkingOperation(string xmlIn) {
            object[] results = this.Invoke("ConfirmUnParkingOperation", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmUnParkingOperationAsync(string xmlIn) {
            this.ConfirmUnParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmUnParkingOperationAsync(string xmlIn, object userState) {
            if ((this.ConfirmUnParkingOperationOperationCompleted == null)) {
                this.ConfirmUnParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmUnParkingOperationOperationCompleted);
            }
            this.InvokeAsync("ConfirmUnParkingOperation", new object[] {
                        xmlIn}, this.ConfirmUnParkingOperationOperationCompleted, userState);
        }
        
        private void OnConfirmUnParkingOperationOperationCompleted(object arg) {
            if ((this.ConfirmUnParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmUnParkingOperationCompleted(this, new ConfirmUnParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFinePaymentQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int QueryFinePaymentQuantity(string xmlIn) {
            object[] results = this.Invoke("QueryFinePaymentQuantity", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void QueryFinePaymentQuantityAsync(string xmlIn) {
            this.QueryFinePaymentQuantityAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryFinePaymentQuantityAsync(string xmlIn, object userState) {
            if ((this.QueryFinePaymentQuantityOperationCompleted == null)) {
                this.QueryFinePaymentQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFinePaymentQuantityOperationCompleted);
            }
            this.InvokeAsync("QueryFinePaymentQuantity", new object[] {
                        xmlIn}, this.QueryFinePaymentQuantityOperationCompleted, userState);
        }
        
        private void OnQueryFinePaymentQuantityOperationCompleted(object arg) {
            if ((this.QueryFinePaymentQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFinePaymentQuantityCompleted(this, new QueryFinePaymentQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmFinePayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmFinePayment(string xmlIn) {
            object[] results = this.Invoke("ConfirmFinePayment", new object[] {
                        xmlIn});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmFinePaymentAsync(string xmlIn) {
            this.ConfirmFinePaymentAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmFinePaymentAsync(string xmlIn, object userState) {
            if ((this.ConfirmFinePaymentOperationCompleted == null)) {
                this.ConfirmFinePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmFinePaymentOperationCompleted);
            }
            this.InvokeAsync("ConfirmFinePayment", new object[] {
                        xmlIn}, this.ConfirmFinePaymentOperationCompleted, userState);
        }
        
        private void OnConfirmFinePaymentOperationCompleted(object arg) {
            if ((this.ConfirmFinePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmFinePaymentCompleted(this, new ConfirmFinePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmUserData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmUserData(string xmlIn) {
            object[] results = this.Invoke("ConfirmUserData", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmUserDataAsync(string xmlIn) {
            this.ConfirmUserDataAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmUserDataAsync(string xmlIn, object userState) {
            if ((this.ConfirmUserDataOperationCompleted == null)) {
                this.ConfirmUserDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmUserDataOperationCompleted);
            }
            this.InvokeAsync("ConfirmUserData", new object[] {
                        xmlIn}, this.ConfirmUserDataOperationCompleted, userState);
        }
        
        private void OnConfirmUserDataOperationCompleted(object arg) {
            if ((this.ConfirmUserDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmUserDataCompleted(this, new ConfirmUserDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateHash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalculateHash(string strInput) {
            object[] results = this.Invoke("CalculateHash", new object[] {
                        strInput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateHashAsync(string strInput) {
            this.CalculateHashAsync(strInput, null);
        }
        
        /// <remarks/>
        public void CalculateHashAsync(string strInput, object userState) {
            if ((this.CalculateHashOperationCompleted == null)) {
                this.CalculateHashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateHashOperationCompleted);
            }
            this.InvokeAsync("CalculateHash", new object[] {
                        strInput}, this.CalculateHashOperationCompleted, userState);
        }
        
        private void OnCalculateHashOperationCompleted(object arg) {
            if ((this.CalculateHashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateHashCompleted(this, new CalculateHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryLoginCompletedEventHandler(object sender, QueryLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryCityCompletedEventHandler(object sender, QueryCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryRechargeCompletedEventHandler(object sender, QueryRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmRechargeCompletedEventHandler(object sender, ConfirmRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryParkingTariffsCompletedEventHandler(object sender, QueryParkingTariffsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingTariffsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingTariffsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryParkingOperationCompletedEventHandler(object sender, QueryParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryParkingOperationWithTimeStepsCompletedEventHandler(object sender, QueryParkingOperationWithTimeStepsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationWithTimeStepsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationWithTimeStepsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryParkingOperationForMinutesCompletedEventHandler(object sender, QueryParkingOperationForMinutesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationForMinutesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationForMinutesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmParkingOperationCompletedEventHandler(object sender, ConfirmParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryUnParkingOperationCompletedEventHandler(object sender, QueryUnParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUnParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUnParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryUnParkingOperationQuantityCompletedEventHandler(object sender, QueryUnParkingOperationQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUnParkingOperationQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUnParkingOperationQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmUnParkingOperationCompletedEventHandler(object sender, ConfirmUnParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmUnParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmUnParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryFinePaymentQuantityCompletedEventHandler(object sender, QueryFinePaymentQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFinePaymentQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFinePaymentQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmFinePaymentCompletedEventHandler(object sender, ConfirmFinePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmFinePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmFinePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmUserDataCompletedEventHandler(object sender, ConfirmUserDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmUserDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmUserDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CalculateHashCompletedEventHandler(object sender, CalculateHashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateHashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateHashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591