//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CSFacturacionBLL.CSFacturacionWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="miserviciowebBinding", Namespace="localhost")]
    public partial class miservicioweb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadarchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDatosticketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public miservicioweb() {
            this.Url = global::CSFacturacionBLL.Properties.Settings.Default.CSFacturacionBLL_CSFacturacionWS_miservicioweb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadarchivoCompletedEventHandler UploadarchivoCompleted;
        
        /// <remarks/>
        public event timbrarTicketCompletedEventHandler timbrarTicketCompleted;
        
        /// <remarks/>
        public event validarTicketCompletedEventHandler validarTicketCompleted;
        
        /// <remarks/>
        public event obtenerDatosticketCompletedEventHandler obtenerDatosticketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("SOAP_SERVER_NAMESPACE#Uploadarchivo", RequestNamespace="SOAP_SERVER_NAMESPACE", ResponseNamespace="SOAP_SERVER_NAMESPACE")]
        [return: System.Xml.Serialization.SoapElementAttribute("respuestaUpload")]
        public respuestaUpload Uploadarchivo(string Password, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] Archivo) {
            object[] results = this.Invoke("Uploadarchivo", new object[] {
                        Password,
                        Archivo});
            return ((respuestaUpload)(results[0]));
        }
        
        /// <remarks/>
        public void UploadarchivoAsync(string Password, byte[] Archivo) {
            this.UploadarchivoAsync(Password, Archivo, null);
        }
        
        /// <remarks/>
        public void UploadarchivoAsync(string Password, byte[] Archivo, object userState) {
            if ((this.UploadarchivoOperationCompleted == null)) {
                this.UploadarchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadarchivoOperationCompleted);
            }
            this.InvokeAsync("Uploadarchivo", new object[] {
                        Password,
                        Archivo}, this.UploadarchivoOperationCompleted, userState);
        }
        
        private void OnUploadarchivoOperationCompleted(object arg) {
            if ((this.UploadarchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadarchivoCompleted(this, new UploadarchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("SOAP_SERVER_NAMESPACE#timbrarTicket", RequestNamespace="SOAP_SERVER_NAMESPACE", ResponseNamespace="SOAP_SERVER_NAMESPACE")]
        [return: System.Xml.Serialization.SoapElementAttribute("respuestaTimbrado")]
        public respuestaTimbrado timbrarTicket(string cRefid, string Password, string cDatosreceptor) {
            object[] results = this.Invoke("timbrarTicket", new object[] {
                        cRefid,
                        Password,
                        cDatosreceptor});
            return ((respuestaTimbrado)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarTicketAsync(string cRefid, string Password, string cDatosreceptor) {
            this.timbrarTicketAsync(cRefid, Password, cDatosreceptor, null);
        }
        
        /// <remarks/>
        public void timbrarTicketAsync(string cRefid, string Password, string cDatosreceptor, object userState) {
            if ((this.timbrarTicketOperationCompleted == null)) {
                this.timbrarTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarTicketOperationCompleted);
            }
            this.InvokeAsync("timbrarTicket", new object[] {
                        cRefid,
                        Password,
                        cDatosreceptor}, this.timbrarTicketOperationCompleted, userState);
        }
        
        private void OntimbrarTicketOperationCompleted(object arg) {
            if ((this.timbrarTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarTicketCompleted(this, new timbrarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("SOAP_SERVER_NAMESPACE#validarTicket", RequestNamespace="SOAP_SERVER_NAMESPACE", ResponseNamespace="SOAP_SERVER_NAMESPACE")]
        [return: System.Xml.Serialization.SoapElementAttribute("respuestaValidarticket")]
        public respuestaValidarticket validarTicket(double dTotal, string cRefid, string cRfcemisor) {
            object[] results = this.Invoke("validarTicket", new object[] {
                        dTotal,
                        cRefid,
                        cRfcemisor});
            return ((respuestaValidarticket)(results[0]));
        }
        
        /// <remarks/>
        public void validarTicketAsync(double dTotal, string cRefid, string cRfcemisor) {
            this.validarTicketAsync(dTotal, cRefid, cRfcemisor, null);
        }
        
        /// <remarks/>
        public void validarTicketAsync(double dTotal, string cRefid, string cRfcemisor, object userState) {
            if ((this.validarTicketOperationCompleted == null)) {
                this.validarTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarTicketOperationCompleted);
            }
            this.InvokeAsync("validarTicket", new object[] {
                        dTotal,
                        cRefid,
                        cRfcemisor}, this.validarTicketOperationCompleted, userState);
        }
        
        private void OnvalidarTicketOperationCompleted(object arg) {
            if ((this.validarTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarTicketCompleted(this, new validarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("SOAP_SERVER_NAMESPACE#obtenerDatosticket", RequestNamespace="SOAP_SERVER_NAMESPACE", ResponseNamespace="SOAP_SERVER_NAMESPACE")]
        [return: System.Xml.Serialization.SoapElementAttribute("respuestaObtenerdatosticket")]
        public respuestaObtenerdatosticket obtenerDatosticket(string cRefid, string Password) {
            object[] results = this.Invoke("obtenerDatosticket", new object[] {
                        cRefid,
                        Password});
            return ((respuestaObtenerdatosticket)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDatosticketAsync(string cRefid, string Password) {
            this.obtenerDatosticketAsync(cRefid, Password, null);
        }
        
        /// <remarks/>
        public void obtenerDatosticketAsync(string cRefid, string Password, object userState) {
            if ((this.obtenerDatosticketOperationCompleted == null)) {
                this.obtenerDatosticketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDatosticketOperationCompleted);
            }
            this.InvokeAsync("obtenerDatosticket", new object[] {
                        cRefid,
                        Password}, this.obtenerDatosticketOperationCompleted, userState);
        }
        
        private void OnobtenerDatosticketOperationCompleted(object arg) {
            if ((this.obtenerDatosticketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDatosticketCompleted(this, new obtenerDatosticketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="localhost")]
    public partial class respuestaUpload {
        
        private string msjField;
        
        private bool resultadoField;
        
        /// <remarks/>
        public string Msj {
            get {
                return this.msjField;
            }
            set {
                this.msjField = value;
            }
        }
        
        /// <remarks/>
        public bool Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="localhost")]
    public partial class respuestaObtenerdatosticket {
        
        private string msjField;
        
        private bool resultadoField;
        
        private string cDatosticketField;
        
        /// <remarks/>
        public string Msj {
            get {
                return this.msjField;
            }
            set {
                this.msjField = value;
            }
        }
        
        /// <remarks/>
        public bool Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string cDatosticket {
            get {
                return this.cDatosticketField;
            }
            set {
                this.cDatosticketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="localhost")]
    public partial class respuestaValidarticket {
        
        private string msjField;
        
        private bool resultadoField;
        
        private string cDatosreceptorField;
        
        private string xML64Field;
        
        private string pDF64Field;
        
        private string nAMEFILEField;
        
        /// <remarks/>
        public string Msj {
            get {
                return this.msjField;
            }
            set {
                this.msjField = value;
            }
        }
        
        /// <remarks/>
        public bool Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string cDatosreceptor {
            get {
                return this.cDatosreceptorField;
            }
            set {
                this.cDatosreceptorField = value;
            }
        }
        
        /// <remarks/>
        public string XML64 {
            get {
                return this.xML64Field;
            }
            set {
                this.xML64Field = value;
            }
        }
        
        /// <remarks/>
        public string PDF64 {
            get {
                return this.pDF64Field;
            }
            set {
                this.pDF64Field = value;
            }
        }
        
        /// <remarks/>
        public string NAMEFILE {
            get {
                return this.nAMEFILEField;
            }
            set {
                this.nAMEFILEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="localhost")]
    public partial class respuestaTimbrado {
        
        private string msjField;
        
        private string xML64Field;
        
        private string pDF64Field;
        
        private byte[] pDFField;
        
        private byte[] xMLField;
        
        private string nAMEFILEField;
        
        /// <remarks/>
        public string Msj {
            get {
                return this.msjField;
            }
            set {
                this.msjField = value;
            }
        }
        
        /// <remarks/>
        public string XML64 {
            get {
                return this.xML64Field;
            }
            set {
                this.xML64Field = value;
            }
        }
        
        /// <remarks/>
        public string PDF64 {
            get {
                return this.pDF64Field;
            }
            set {
                this.pDF64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public string NAMEFILE {
            get {
                return this.nAMEFILEField;
            }
            set {
                this.nAMEFILEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadarchivoCompletedEventHandler(object sender, UploadarchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadarchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadarchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaUpload Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaUpload)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void timbrarTicketCompletedEventHandler(object sender, timbrarTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaTimbrado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaTimbrado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void validarTicketCompletedEventHandler(object sender, validarTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaValidarticket Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaValidarticket)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void obtenerDatosticketCompletedEventHandler(object sender, obtenerDatosticketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDatosticketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDatosticketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaObtenerdatosticket Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaObtenerdatosticket)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591