//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.Domain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ips.integraparking.com/integraSenderWS/integraSender.asmx")]
        public string integraMobile_Domain_integraSenderWS_integraSender {
            get {
                return ((string)(this["integraMobile_Domain_integraSenderWS_integraSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobile;Integrated Securi" +
            "ty=True")]
        public string integraMobileConnectionString2 {
            get {
                return ((string)(this["integraMobileConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobile;Integrated Securi" +
            "ty=False;User ID=iis;Password=iis")]
        public string integraMobileConnectionString4 {
            get {
                return ((string)(this["integraMobileConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobile;Integrated Securi" +
            "ty=False;User ID=iis")]
        public string integraMobileConnectionString5 {
            get {
                return ((string)(this["integraMobileConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=False;User ID=iis;Password=iis")]
        public string integraMobilePreProdConnectionString3 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=True")]
        public string integraMobileConnectionString1 {
            get {
                return ((string)(this["integraMobileConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=True")]
        public string integraMobileConnectionString3 {
            get {
                return ((string)(this["integraMobileConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=False;User ID=iis")]
        public string integraMobilePreProdConnectionString4 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU\\SQLEXPRESS;Initial Catalog=integraMobilePreProd" +
            ";Integrated Security=True")]
        public string integraMobilePreProdConnectionString2 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02;Initial Catalog=integraMobilePreProd;Integrated Security=True")]
        public string integraMobilePreProdConnectionString5 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=True")]
        public string integraMobileConnectionString {
            get {
                return ((string)(this["integraMobileConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=True")]
        public string integraMobileDevConnectionString {
            get {
                return ((string)(this["integraMobileDevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Persist Se" +
            "curity Info=True;User ID=sa")]
        public string integraMobilePreProdConnectionString {
            get {
                return ((string)(this["integraMobilePreProdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobilePreProd;Integrated" +
            " Security=False;User ID=sa")]
        public string integraMobilePreProdConnectionString1 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01;Initial Catalog=integraMobileDevEur;Integrated Security=True")]
        public string integraMobileDevConnectionString1 {
            get {
                return ((string)(this["integraMobileDevConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HBUSQUE-PC\\SQLEXPRESS;Initial Catalog=integraMobileDev;Integrated Sec" +
            "urity=True")]
        public string integraMobileDevConnectionString2 {
            get {
                return ((string)(this["integraMobileDevConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=srv-iparkme.integraparking.com;Initial Catalog=integraMobilePreProd;P" +
            "ersist Security Info=True;User ID=integraMobilePreProd;Min Pool Size=40;Max Pool" +
            " Size=400")]
        public string integraMobilePreProdConnectionString6 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01;Initial Catalog=integraMobileDevEur;Integrated Security=True")]
        public string integraMobileDevEurConnectionString {
            get {
                return ((string)(this["integraMobileDevEurConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=srv-iparkme.integraparking.com;Initial Catalog=integraMobileDev;Persi" +
            "st Security Info=True;User ID=integraMobilePreProd;Password=\"_gISDX\'{gBGKZ:HKy\'d" +
            "$oaWK\";Min Pool Size=40;Max Pool Size=400")]
        public string integraMobileDevConnectionString3 {
            get {
                return ((string)(this["integraMobileDevConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=srv-iparkme.integraparking.com;Initial Catalog=integraMobilePreProd;P" +
            "ersist Security Info=True;User ID=integraMobilePreProd;Password=\"_gISDX\'{gBGKZ:H" +
            "Ky\'d$oaWK\";Min Pool Size=40;Max Pool Size=400")]
        public string integraMobilePreProdConnectionString7 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01;Initial Catalog=integraMobilePreProdEur;Integrated Security=Tr" +
            "ue")]
        public string integraMobilePreProdEurConnectionString {
            get {
                return ((string)(this["integraMobilePreProdEurConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6NLP5KT\\MARIU;Initial Catalog=integraMobileDevEur;Integrated " +
            "Security=True")]
        public string integraMobileDevEurConnectionString1 {
            get {
                return ((string)(this["integraMobileDevEurConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01;Initial Catalog=integraMobileDev;Integrated Security=True")]
        public string integraMobileDevConnectionString4 {
            get {
                return ((string)(this["integraMobileDevConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02;Initial Catalog=integraMobileAmeDev;Integrated Security=True")]
        public string integraMobileAmeDevConnectionString {
            get {
                return ((string)(this["integraMobileAmeDevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01;Initial Catalog=integraMobilePreAme;Integrated Security=True")]
        public string integraMobilePreAmeConnectionString {
            get {
                return ((string)(this["integraMobilePreAmeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01\\MSSQLSERVER2019;Initial Catalog=integraMobilePreProdEur;Integr" +
            "ated Security=True")]
        public string integraMobilePreProdEurConnectionString1 {
            get {
                return ((string)(this["integraMobilePreProdEurConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02\\MSSQLSERVER01;Initial Catalog=integraMobileDevAme;Integrated S" +
            "ecurity=True;Min Pool Size=40;Max Pool Size=400")]
        public string integraMobileDevAmeConnectionString {
            get {
                return ((string)(this["integraMobileDevAmeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02\\MSSQLSERVER01;Initial Catalog=integraMobileDevEur;Integrated S" +
            "ecurity=True;Min Pool Size=40;Max Pool Size=400")]
        public string integraMobileDevEurConnectionString2 {
            get {
                return ((string)(this["integraMobileDevEurConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01\\MSSQLSERVER2019;Initial Catalog=integraMobileDevEur;Integrated" +
            " Security=True;Min Pool Size=40;Max Pool Size=400")]
        public string integraMobileDevEurConnectionString3 {
            get {
                return ((string)(this["integraMobileDevEurConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02\\MSSQLSERVER01;Initial Catalog=integraMobilePreProdEur;Integrat" +
            "ed Security=True")]
        public string integraMobilePreProdEurConnectionString2 {
            get {
                return ((string)(this["integraMobilePreProdEurConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01\\MSSQLSERVER2019;Initial Catalog=integraMobilePreProdAme;Integr" +
            "ated Security=True")]
        public string integraMobilePreProdAmeConnectionString {
            get {
                return ((string)(this["integraMobilePreProdAmeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE02\\MSSQLSERVER01;Initial Catalog=integraMobileDevEur;Integrated S" +
            "ecurity=True")]
        public string integraMobileDevEurConnectionString4 {
            get {
                return ((string)(this["integraMobileDevEurConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI\\MSSQLSERVER01;Initial Catalog=integraMobileDev;Integrated Securit" +
            "y=True")]
        public string integraMobileDevConnectionString5 {
            get {
                return ((string)(this["integraMobileDevConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HBUSQUE-PC\\SQL2019;Initial Catalog=integraMobileDev;Integrated Securi" +
            "ty=True")]
        public string integraMobileDevConnectionString6 {
            get {
                return ((string)(this["integraMobileDevConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI\\MSSQLSERVER01;Initial Catalog=integraMobilePreProd;Integrated Sec" +
            "urity=True")]
        public string integraMobilePreProdConnectionString8 {
            get {
                return ((string)(this["integraMobilePreProdConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIKE01\\MSSQLSERVER2019;Initial Catalog=integraMobileDevAme;Integrated" +
            " Security=True")]
        public string integraMobileDevAmeConnectionString1 {
            get {
                return ((string)(this["integraMobileDevAmeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HBUSQUE-PC\\SQL2019;Initial Catalog=integraMobileDevAme;Integrated Sec" +
            "urity=True")]
        public string integraMobileDevAmeConnectionString2 {
            get {
                return ((string)(this["integraMobileDevAmeConnectionString2"]));
            }
        }
    }
}
