//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobileNotificationService.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobileNotificationService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} your parking expires at  {1:HH:mm}.
        /// </summary>
        public static string AndroidExpiringParkingNotificationTextMessage {
            get {
                return ResourceManager.GetString("AndroidExpiringParkingNotificationTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle with user plate {0} has accessed in the parking..
        /// </summary>
        public static string AndroidOffstreetEntryNotificationTextMessage {
            get {
                return ResourceManager.GetString("AndroidOffstreetEntryNotificationTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle with user plate {0} has left the parking..
        /// </summary>
        public static string AndroidOffstreetExitNotificationTextMessage {
            get {
                return ResourceManager.GetString("AndroidOffstreetExitNotificationTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle with user plate {0} has parked. .
        /// </summary>
        public static string AndroidParkingNotificationTextMessage {
            get {
                return ResourceManager.GetString("AndroidParkingNotificationTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License plate {1} has received a ticket, numbered {0}.
        /// </summary>
        public static string AndroidTicketNotificationTextMessage {
            get {
                return ResourceManager.GetString("AndroidTicketNotificationTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security code for password recovery: {0}. The code will expire in {1} min..
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticket {0}     .
        /// </summary>
        public static string WPTicketNotificationText1 {
            get {
                return ResourceManager.GetString("WPTicketNotificationText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payable until {0:HH:mm}    .
        /// </summary>
        public static string WPTicketNotificationText2 {
            get {
                return ResourceManager.GetString("WPTicketNotificationText2", resourceCulture);
            }
        }
    }
}
