//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.WS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobile.WS.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue el registro pulsando &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt; una vez haya recibido el SMS.&lt;br&gt;&lt;br&gt;&lt;br&gt;El equipo de EYSAMobile.
        /// </summary>
        internal static string Activation_EmailBody {
            get {
                return ResourceManager.GetString("Activation_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de EYSAMobile.
        /// </summary>
        internal static string Activation_EmailHeader {
            get {
                return ResourceManager.GetString("Activation_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es un mensaje de EYSAMobile. Compruebe su e-mail para continuar con el registro. Su codigo de activacion es {0}..
        /// </summary>
        internal static string Activation_SMS {
            get {
                return ResourceManager.GetString("Activation_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px;&quot;&gt;Saldo:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Confirm_EmailBody_Balance {
            get {
                return ResourceManager.GetString("Confirm_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Recarga Automática realizada.
        /// </summary>
        internal static string ConfirmAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Recarga realizada.
        /// </summary>
        internal static string ConfirmNoAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmNoAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;page&quot; style=&quot;font-family: Arial, Helvetica, sans-serif; color: #666; margin:auto; width:650px;&quot;&gt;
        ///
        ///	&lt;!--	HEADER	--&gt;
        ///    &lt;div id=&quot;header&quot; style=&quot;background-color: #004f7c; color: #fff; padding: 10px 20px;&quot;&gt;    	
        ///        &lt;h2 style=&quot;font-weight:lighter; font-size: 24pt; margin:0px; padding: 0px; line-height:0px; display: inline;&quot;&gt;
        ///			&lt;img id=&quot;logo&quot; src=&quot;https://www.eysamobile.com/integraMobile/Content/img/offp_icon.png&quot; width=&quot;92&quot; height=&quot;92&quot; alt=&quot;iParkMe&quot; style=&quot;vertical-align: middle; margin-rig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; class=&quot;label&quot; style=&quot;padding: 10px 5px; white-space: nowrap; vertical-align: baseline; border-bottom: 1px solid #ccc; font-style: italic; color: #999; font-size: 10pt;&quot;&gt;Saldo&lt;/td&gt;
        ///	&lt;td width=&quot;5%&quot; class=&quot;label&quot; style=&quot;padding: 10px 5px; white-space: nowrap; vertical-align: baseline; border-bottom: 1px solid #ccc; font-style: italic; color: #999; font-size: 10pt;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///	&lt;td colspan=&quot;2&quot; class=&quot;money data empha&quot; style=&quot;text-align: right; padding: 10px 5px; white-space: nowrap; ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody_Balance {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparcamiento realizado.
        /// </summary>
        internal static string ConfirmOffstreet_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;ParkingDone&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img/o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Aparcamiento realizado.
        /// </summary>
        internal static string ConfirmParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;iParkMe | RechargeDone&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmRecharge_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmRecharge_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Denuncia Anulada&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #DF2D46;&quot;&gt;
        ///			&lt;td style=&quot;padding: 20px 0 20px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Denuncia Anulada.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;UnparkingDone&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmUnParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Desaparcamiento realizado.
        /// </summary>
        internal static string ConfirmUnParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Welcome&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img/offp_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Body {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a EYSAMobile.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Subject {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px; vertical-align: bottom;&quot;&gt;Subtotal:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_LayoutSubtotal {
            get {
                return ResourceManager.GetString("Email_LayoutSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px; vertical-align: bottom;&quot;&gt;Base:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, san [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_LayoutTotal {
            get {
                return ResourceManager.GetString("Email_LayoutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px; vertical-align: bottom;&quot;&gt;Base:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, san [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_LayoutTotalBonus {
            get {
                return ResourceManager.GetString("Email_LayoutTotalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolet&amp;iacute;n: {0}&lt;br&gt;Matr&amp;iacute;cula: {1}&lt;br&gt;Ciudad: {2}&lt;br&gt;Fecha: {3:HH:mm:ss dd/MM/yyyy}&lt;br&gt;Descripci&amp;oacute;n: {4}&lt;br&gt;Cantidad A Pagar: {5}&lt;br&gt;&lt;br&gt;&lt;a href=&quot;{6}&quot;&gt;&lt;img src=&quot;{7}&quot; border=&quot;0&quot;&gt;&lt;/a&gt;&lt;br&gt;&lt;br&gt;.
        /// </summary>
        internal static string ExternalTicket_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: {0} ha sido denunciado con boletín {1}.
        /// </summary>
        internal static string ExternalTicket_EmailHeader {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolet&amp;iacute;n: {0}&lt;br&gt;Matr&amp;iacute;cula: {1}&lt;br&gt;Ciudad: {2}&lt;br&gt;Fecha: {3:HH:mm:ss dd/MM/yyyy}&lt;br&gt;Descripci&amp;oacute;n: {4}&lt;br&gt;DENUNCIA NO ANULABLE&lt;br&gt;&lt;br&gt;&lt;a href=&quot;{5}&quot;&gt;&lt;img src=&quot;{6}&quot; border=&quot;0&quot;&gt;&lt;/a&gt;&lt;br&gt;&lt;br&gt;.
        /// </summary>
        internal static string ExternalTicketNotPayable_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicketNotPayable_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su usuario de EYSAMobile? .
        /// </summary>
        internal static string ForgetUsername_EmailHeader {
            get {
                return ResourceManager.GetString("ForgetUsername_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Según su solicitud, le estamos enviando su nombre de usuario de EYSAMobile.&lt;br&gt;Usuario: {0}&lt;br&gt;&lt;br&gt;El equipo de EYSAMobile  .
        /// </summary>
        internal static string ForgeUsername_EmailBody {
            get {
                return ResourceManager.GetString("ForgeUsername_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtenga su contraseña pulsando  &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt; una vez que haya recibido el SMS.  &lt;br&gt;&lt;br&gt;&lt;br&gt;El equipo de EYSAMobile.
        /// </summary>
        internal static string ForgotPassword_EmailBody {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYSAMobile: Recuperación de contraseña.
        /// </summary>
        internal static string ForgotPassword_EmailHeader {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es un mensaje de EYSAMobile. Su codigo para la recuperación de la contraseña es  {0}..
        /// </summary>
        internal static string ForgotPassword_SMS {
            get {
                return ResourceManager.GetString("ForgotPassword_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;Welcome&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img/offp_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InviteFriend_Email_Body {
            get {
                return ResourceManager.GetString("InviteFriend_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitación a EYSAMobile.
        /// </summary>
        internal static string InviteFriend_Email_Subject {
            get {
                return ResourceManager.GetString("InviteFriend_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Body {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Subject {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img/recharge_ico [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransferBalanceDst_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EysaMobile: Transferencia de Saldo Recibida.
        /// </summary>
        internal static string TransferBalanceDst_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.eysamobile.com/integraMobile/Content/img/recharge_ico [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransferBalanceSrc_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EysaMobile: Transferencia de Saldo Enviada.
        /// </summary>
        internal static string TransferBalanceSrc_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailHeader", resourceCulture);
            }
        }
    }
}
