//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobilePaymentsService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobilePaymentsService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iParkMe: Credit Added Automatically.
        /// </summary>
        public static string ConfirmAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iParkMe: Credit Added.
        /// </summary>
        public static string ConfirmNoAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmNoAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;iParkMe | RechargeDone&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; style=&quot;border-collapse: collapse; border-spacing: 0; margin: 0 auto; padding: 0; width: 650px;&quot;&gt;
        ///		&lt;tr style=&quot;background: #0F4F7B;&quot;&gt;
        ///			&lt;td style=&quot;padding: 15px 0 15px 25px; width: 60px&quot;&gt;&lt;img src=&quot;https://www.iparkme.com/integraMobile/Conte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmRecharge_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmRecharge_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px; vertical-align: bottom;&quot;&gt;Subtotal:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_LayoutSubtotal {
            get {
                return ResourceManager.GetString("Email_LayoutSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, sans-serif; font-size: 13px; font-style: italic; padding: 10px 1px; vertical-align: bottom;&quot;&gt;Base:&lt;/td&gt;
        ///	&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 2px solid #C2C2C2; color: #0F4F7B; font-family: Arial, sans-serif; font-size: 16px; padding: 10px 1px; text-align: center; vertical-align: bottom;&quot;&gt;{0}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid #C2C2C2; color: #8B8B8B; font-family: Arial, san [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_LayoutTotal {
            get {
                return ResourceManager.GetString("Email_LayoutTotal", resourceCulture);
            }
        }
    }
}
