//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en la activación de su cuenta, contacte con soporte en el teléfono de la OTA: 944-XXX-XXX o por correo electrónico a: xxxxxx@xxxxxx.com.
        /// </summary>
        public static string Activate_Account_Message1 {
            get {
                return ResourceManager.GetString("Activate_Account_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación Errónea.
        /// </summary>
        public static string ActivateAccount_Title {
            get {
                return ResourceManager.GetString("ActivateAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su cuenta de usuario ha sido activada con éxito, ya puede iniciar sesión y utilizar BILBAOPARK..
        /// </summary>
        public static string ActivateAccountSuccess_Message1 {
            get {
                return ResourceManager.GetString("ActivateAccountSuccess_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación correcta.
        /// </summary>
        public static string ActivateAccountSuccess_Title {
            get {
                return ResourceManager.GetString("ActivateAccountSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de activación ya ha sido usado.
        /// </summary>
        public static string ErrMsg_ActivationCodeAlreadyUsed {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationCodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de activación ha expirado.
        /// </summary>
        public static string ErrMsg_ActivationCodeExpired_2 {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationCodeExpired_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La url de activación es incorrecta.
        /// </summary>
        public static string ErrMsg_ActivationURLIncorrect {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationURLIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima del campo {0} es {1}.
        /// </summary>
        public static string ErrorsMsg_InvalidLengthWithMinimum {
            get {
                return ResourceManager.GetString("ErrorsMsg_InvalidLengthWithMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben coincidir.
        /// </summary>
        public static string ErrorsMsg_PasswordsMustMatch {
            get {
                return ResourceManager.GetString("ErrorsMsg_PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatario.
        /// </summary>
        public static string ErrorsMsg_RequiredField {
            get {
                return ResourceManager.GetString("ErrorsMsg_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme la nueva contraseña:.
        /// </summary>
        public static string ForgotPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cambiar la contraseña de {0},debe introducir la nueva contraseña..
        /// </summary>
        public static string ForgotPassword_Message1 {
            get {
                return ResourceManager.GetString("ForgotPassword_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca su nueva contraseña:.
        /// </summary>
        public static string ForgotPassword_Message2 {
            get {
                return ResourceManager.GetString("ForgotPassword_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña:.
        /// </summary>
        public static string ForgotPassword_Password {
            get {
                return ResourceManager.GetString("ForgotPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Repita la contraseña.
        /// </summary>
        public static string ForgotPassword_WriteYourConfirmPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_WriteYourConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Min.- {0} Max {1} caracteres.
        /// </summary>
        public static string ForgotPassword_WriteYourPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_WriteYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña se cambió correctamente..
        /// </summary>
        public static string ForgotPasswordConfirmation_Message1 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña cambiada correctamente.
        /// </summary>
        public static string ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
    }
}
