//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.WS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobile.WS.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string Activation_EmailBody {
            get {
                return ResourceManager.GetString("Activation_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay registration.
        /// </summary>
        internal static string Activation_EmailHeader {
            get {
                return ResourceManager.GetString("Activation_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is a message from Blinkay. Your activation code is {0}..
        /// </summary>
        internal static string Activation_SMS {
            get {
                return ResourceManager.GetString("Activation_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string CommerceSubscriptionRequest {
            get {
                return ResourceManager.GetString("CommerceSubscriptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay Merchants Program Subscription Request.
        /// </summary>
        internal static string CommerceSubscriptionRequest_Header {
            get {
                return ResourceManager.GetString("CommerceSubscriptionRequest_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string Confirm_EmailBody_Balance {
            get {
                return ResourceManager.GetString("Confirm_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Automatic Balance Recharge.
        /// </summary>
        internal static string ConfirmAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmCampaignUserUse_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmCampaignUserUse_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmCampaignUserUse_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmCampaignUserUse_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Balance Recharge.
        /// </summary>
        internal static string ConfirmNoAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmNoAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody_Balance {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking Finished.
        /// </summary>
        internal static string ConfirmOffstreet_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmParking_EmailBody_SpaceSection {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailBody_SpaceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Parking operation.
        /// </summary>
        internal static string ConfirmParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmRecharge_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmRecharge_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Fine Paid.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmUnParking_0_1_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmUnParking_0_1_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ConfirmUnParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Unparking.
        /// </summary>
        internal static string ConfirmUnParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Body {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Blinkay.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Subject {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string Email_LayoutSubtotal {
            get {
                return ResourceManager.GetString("Email_LayoutSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string Email_LayoutTotal {
            get {
                return ResourceManager.GetString("Email_LayoutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string Email_LayoutTotalBonus {
            get {
                return ResourceManager.GetString("Email_LayoutTotalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} {2} - {3}, {4} {5}.
        /// </summary>
        internal static string Emisalba_TicketDescription {
            get {
                return ResourceManager.GetString("Emisalba_TicketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ExternalTicket_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: {0} has a ticket with number {1}.
        /// </summary>
        internal static string ExternalTicket_EmailHeader {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ExternalTicketNotPayable_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicketNotPayable_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget your username for Blinkay? .
        /// </summary>
        internal static string ForgetUsername_EmailHeader {
            get {
                return ResourceManager.GetString("ForgetUsername_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ForgeUsername_EmailBody {
            get {
                return ResourceManager.GetString("ForgeUsername_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ForgotPassword_EmailBody {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string ForgotPassword_EmailHeader {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is a message from Blinkay. The code to recover your password is {0}..
        /// </summary>
        internal static string ForgotPassword_SMS {
            get {
                return ResourceManager.GetString("ForgotPassword_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendByCampaing_EmailBody {
            get {
                return ResourceManager.GetString("InvitedAFriendByCampaing_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendByCampaing_EmailHeader {
            get {
                return ResourceManager.GetString("InvitedAFriendByCampaing_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendCongratInvited_EmailBody {
            get {
                return ResourceManager.GetString("InvitedAFriendCongratInvited_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendCongratInvited_EmailHeader {
            get {
                return ResourceManager.GetString("InvitedAFriendCongratInvited_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendCongratInviter_EmailBody {
            get {
                return ResourceManager.GetString("InvitedAFriendCongratInviter_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InvitedAFriendCongratInviter_EmailHeader {
            get {
                return ResourceManager.GetString("InvitedAFriendCongratInviter_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string InviteFriend_Email_Body {
            get {
                return ResourceManager.GetString("InviteFriend_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay Invitation.
        /// </summary>
        internal static string InviteFriend_Email_Subject {
            get {
                return ResourceManager.GetString("InviteFriend_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Body {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Subject {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string SignupStep1_Email_Body {
            get {
                return ResourceManager.GetString("SignupStep1_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay Sign Up.
        /// </summary>
        internal static string SignupStep1_Email_Subject {
            get {
                return ResourceManager.GetString("SignupStep1_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string TransferBalanceDst_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Balance Transfer Received.
        /// </summary>
        internal static string TransferBalanceDst_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM:en-US.
        /// </summary>
        internal static string TransferBalanceSrc_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blinkay: Balance Transfer Sent.
        /// </summary>
        internal static string TransferBalanceSrc_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailHeader", resourceCulture);
            }
        }
    }
}
