/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD
	INS_LIMIT_ZONE_WARNING int NULL,
	INS_LIMIT_ZONE_WARNING_METERS int NULL,
	INS_INVALID_PLATE_FORMAT_WARNING int NULL,
	INS_VALID_PLATE_REGEX nvarchar(1024) NULL
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_LIMIT_ZONE_WARNING DEFAULT 0 FOR INS_LIMIT_ZONE_WARNING
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_INVALID_PLATE_FORMAT_WARNING DEFAULT 0 FOR INS_INVALID_PLATE_FORMAT_WARNING
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
