/****** Object:  Table [dbo].[PAYSAFE_CONFIGURATION]    Script Date: 13/05/2019 15:48:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PAYSAFE_CONFIGURATION](
	[PYSCON_ID] [numeric](18, 0) NOT NULL IDENTITY (1, 1),
	[PYSCON_GUID] [varchar](100) NOT NULL,
	[PYSCON_INCLUDE_JS_URL] [varchar](255) NOT NULL,
	[PYSCON_ENVIRONMENT] [varchar](50) NOT NULL,
	[PYSCON_ACCOUNT_NUMBER] [int] NOT NULL,
	[PYSCON_API_KEY] [varchar](255) NOT NULL,
	[PYSCON_API_SECRET] [varchar](255) NULL,
	[PYSCON_JS_API_KEY] varchar(255) NOT NULL,
	[PYSCON_JS_API_SECRET] varchar(255) NULL,
	[PYSCON_SERVICE_TIMEOUT] [int] NOT NULL,
	[PYSCON_CHECK_DATE_AND_HASH] [int] NOT NULL,
	[PYSCON_CONFIRMATION_TIME] [int] NOT NULL,
	[PYSCON_HASH_SEED] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PAYSAFE_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[PYSCON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PAYSAFE_CONFIGURATION] ADD  CONSTRAINT [DF_PAYSAFE_CONFIGURATION_PYSCON_ENVIRONMENT]  DEFAULT ('LIVE') FOR [PYSCON_ENVIRONMENT]
GO

ALTER TABLE [dbo].[PAYSAFE_CONFIGURATION] ADD  CONSTRAINT [DF_PAYSAFE_CONFIGURATION_BSRCON_CHECK_DATE_AND_HASH]  DEFAULT ((1)) FOR [PYSCON_CHECK_DATE_AND_HASH]
GO

ALTER TABLE [dbo].[PAYSAFE_CONFIGURATION] ADD  CONSTRAINT [DF_PAYSAFE_CONFIGURATION_BSRCON_CONFIRMATION_TIME]  DEFAULT ((300)) FOR [PYSCON_CONFIRMATION_TIME]
GO

ALTER TABLE [dbo].[PAYSAFE_CONFIGURATION] ADD  CONSTRAINT [DF_PAYSAFE_CONFIGURATION_BSRCON_HASH_SEED]  DEFAULT ((1)) FOR [PYSCON_HASH_SEED]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Identifier' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Identifier GUID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_GUID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Environment: TEST or LIVE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_ENVIRONMENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Check date and hash or not?' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_CHECK_DATE_AND_HASH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Max Number of seconds to confirm transaction' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_CONFIRMATION_TIME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hash Seed' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PAYSAFE_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'PYSCON_HASH_SEED'
GO



/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PAYSAFE_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD
	CPTGC_PYSCON_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Paysafe configuration'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG', N'COLUMN', N'CPTGC_PYSCON_ID'
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_PAYSAFE_CONFIGURATION FOREIGN KEY
	(
	CPTGC_PYSCON_ID
	) REFERENCES dbo.PAYSAFE_CONFIGURATION
	(
	PYSCON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
