CREATE TABLE [dbo].[RESTRICTED_TARIFF_MESSAGE](
	[RTM_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[RTM_GRP_ID] [numeric](18, 0) NOT NULL,
	[RTM_LIT_ID] [numeric](18, 0) NOT NULL,
	[RTM_INIDATE] [datetime] NOT NULL,
	[RTM_ENDDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_RESTRICTED_TARIFF_MESSAGE] PRIMARY KEY CLUSTERED 
(
	[RTM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RESTRICTED_TARIFF_MESSAGE]  WITH CHECK ADD  CONSTRAINT [FK_RESTRICTED_TARIFF_MESSAGE_RESTRICTED_TARIFF_MESSAGE] FOREIGN KEY([RTM_ID])
REFERENCES [dbo].[RESTRICTED_TARIFF_MESSAGE] ([RTM_ID])
GO

ALTER TABLE [dbo].[RESTRICTED_TARIFF_MESSAGE] CHECK CONSTRAINT [FK_RESTRICTED_TARIFF_MESSAGE_RESTRICTED_TARIFF_MESSAGE]
GO

/****************************************************************************************************************************/
/****************************************************************************************************************************/
/****************************************************************************************************************************/
Select * from [LITERALS] where LIT_ID in (60000022,60000023)
/*MENSAJE POR DEFECTO*/
INSERT INTO [dbo].[LITERALS]([LIT_ID],[LIT_DESCRIPTION],[LIT_KEY])
VALUES(60000022,'Tarifa no disponible',NULL)
/*MENSAJE PERSONALIZADO*/
INSERT INTO [dbo].[LITERALS]([LIT_ID],[LIT_DESCRIPTION],[LIT_KEY])
VALUES(60000023,'Mensaje Zona 14 Justicia',NULL)
GO

Select * from [LITERAL_LANGUAGES] where [LITL_LIT_ID] in (60000022,60000023)

/*MENSAJE POR DEFECTO*/
----Español (1)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000022,1,'Tarifa no disponible')
----Ingles(2)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000022,2,'Rate not available')
----Frances(3)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000022,3,'Tarif non disponible')
----Catalan(4)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000022,4,'Tarifa no disponible')
----Español Mexico (5)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000022,5,'Tarifa no disponible')

/*MENSAJE PERSONALIZADO*/
----Español (1)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000023,1,'Mensaje Zona 14 Justicia')
----Ingles(2)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000023,2,'Message Area 14 Justice')
----Frances(3)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000023,3,'Zone de message 14 Justice')
----Catalan(4)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000023,4,'Missatge Zona 14 Justícia')
----Español Mexico (5)
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000023,5,'Mensaje Zona 14 Justicia')


INSERT INTO [dbo].[RESTRICTED_TARIFF_MESSAGE]([RTM_GRP_ID],[RTM_LIT_ID],[RTM_INIDATE],[RTM_ENDDATE])
VALUES(301713,60000023,'2019-06-20 00:00:00.000','2019-06-30 00:00:00.000')