ALTER VIEW [dbo].[VW_RECHARGE_COUPONS]
AS
	SELECT ROW_NUMBER() OVER (ORDER BY RCOUP_ID) ROW_NUMBER_ID, RECHARGE_COUPONS.*, RTL_NAME, RTL_EMAIL, RTL_ADDRESS, RTL_DOC_ID, u.RCOUPU_USR_ID, u.RCOUPU_DATE, US.USR_USERNAME
	FROM RECHARGE_COUPONS 
	LEFT JOIN RETAILER_PAYMENTS ON RCOUP_RTLPY_ID = RTLPY_ID
	LEFT JOIN RETAILERS ON RTLPY_RTL_ID = RTL_ID
	LEFT JOIN RECHARGE_COUPONS_USES u ON RCOUP_ID = u.RCOUPU_RCOUP_ID
	LEFT JOIN VW_USERS US ON u.RCOUPU_USR_ID = US.USR_ID
GO