/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_OPERATIONS_DISCOUNTS
GO
ALTER TABLE dbo.OPERATIONS_DISCOUNTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_INSTALLATIONS
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_GROUPS
GO
ALTER TABLE dbo.GROUPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_CUSTOMER_INVOICES
GO
ALTER TABLE dbo.CUSTOMER_INVOICES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_1
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_2
GO
ALTER TABLE dbo.CURRENCIES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_OPE_MOSE_OS
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_UTC_DATE
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_date_utc_offset
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_OPE_AMOUNT_CUR_ID
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_OPE_BALANCE_CUR_ID
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_OPE_CHANGE_APPLIED
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_SUSCRIPTION_TYPE
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_OPE_BALANCE_BEFORE
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_TOTAL_AMOUNT_CHARGED
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_TRANS_STATUS
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_STATUS_DATE
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS
	DROP CONSTRAINT DF_TICKET_PAYMENTS_NON_USERS_TIPANU_RETRIES_NUM
GO
CREATE TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS
	(
	TIPANU_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	TIPANU_MOSE_OS int NOT NULL,
	TIPANU_INS_ID numeric(18, 0) NOT NULL,
	TIPANU_DATE datetime NOT NULL,
	TIPANU_UTC_DATE datetime NOT NULL,
	TIPANU_DATE_UTC_OFFSET int NOT NULL,
	TIPANU_USRP_ID numeric(18, 0) NULL,
	TIPANU_PLATE_STRING varchar(50) NULL,
	TIPANU_TICKET_NUMBER varchar(1024) NOT NULL,
	TIPANU_TICKET_DATA varchar(300) NULL,
	TIPANU_AMOUNT int NOT NULL,
	TIPANU_AMOUNT_CUR_ID numeric(18, 0) NOT NULL,
	TIPANU_BALANCE_CUR_ID numeric(18, 0) NOT NULL,
	TIPANU_CHANGE_APPLIED numeric(18, 6) NOT NULL,
	TIPANU_CHANGE_FEE_APPLIED numeric(18, 6) NOT NULL,
	TIPANU_FINAL_AMOUNT int NOT NULL,
	TIPANU_EXTERNAL_ID varchar(50) NULL,
	TIPANU_INSERTION_UTC_DATE datetime NULL,
	TIPANU_TIPANU_ID numeric(18, 0) NULL,
	TIPANU_OPEDIS_ID numeric(18, 0) NULL,
	TIPANU_SUSCRIPTION_TYPE int NOT NULL,
	TIPANU_BALANCE_BEFORE int NOT NULL,
	TIPANU_CONFIRMED_IN_WS int NULL,
	TIPANU_CONFIRM_IN_WS_RETRIES_NUM int NULL,
	TIPANU_CONFIRM_IN_WS_DATE datetime NULL,
	TIPANU_LATITUDE numeric(18, 12) NULL,
	TIPANU_LONGITUDE numeric(18, 12) NULL,
	TIPANU_APP_VERSION varchar(20) NULL,
	TIPANU_CONFIRMATION_TIME_IN_WS decimal(18, 0) NULL,
	TIPANU_QUEUE_LENGTH_BEFORE_CONFIRM_WS int NULL,
	TIPANU_GRP_ID numeric(18, 0) NULL,
	TIPANU_PERC_VAT1 numeric(18, 5) NULL,
	TIPANU_PERC_VAT2 numeric(18, 5) NULL,
	TIPANU_PARTIAL_VAT1 numeric(18, 0) NULL,
	TIPANU_PERC_FEE numeric(18, 5) NULL,
	TIPANU_PERC_FEE_TOPPED numeric(18, 0) NULL,
	TIPANU_PARTIAL_PERC_FEE numeric(18, 0) NULL,
	TIPANU_FIXED_FEE numeric(18, 0) NULL,
	TIPANU_PARTIAL_FIXED_FEE numeric(18, 0) NULL,
	TIPANU_TOTAL_AMOUNT int NULL,
	TIPANU_CUSINV_ID numeric(18, 0) NULL,
	TIPANU_OP_REFERENCE varchar(50) NULL,
	TIPANU_TRANSACTION_ID varchar(50) NULL,
	TIPANU_GATEWAY_DATE varchar(50) NULL,
	TIPANU_AUTH_CODE varchar(50) NULL,
	TIPANU_AUTH_RESULT varchar(50) NULL,
	TIPANU_SECOND_OP_REFERENCE varchar(50) NULL,
	TIPANU_SECOND_TRANSACTION_ID varchar(50) NULL,
	TIPANU_SECOND_GATEWAY_DATE varchar(50) NULL,
	TIPANU_SECOND_AUTH_RESULT varchar(50) NULL,
	TIPANU_CARD_HASH varchar(50) NULL,
	TIPANU_CARD_REFERENCE varchar(50) NULL,
	TIPANU_CARD_SCHEME varchar(50) NULL,
	TIPANU_MASKED_CARD_NUMBER varchar(50) NULL,
	TIPANU_CARD_EXPIRATION_DATE datetime NULL,
	TIPANU_PAYPAL_3T_TOKEN varchar(50) NULL,
	TIPANU_PAYPAL_3T_PAYER_ID varchar(50) NULL,
	TIPANU_PAYPAL_PREAPPROVED_PAY_KEY varchar(50) NULL,
	TIPANU_TOTAL_AMOUNT_CHARGED numeric(18, 0) NOT NULL,
	TIPANU_TRANS_STATUS int NOT NULL,
	TIPANU_STATUS_DATE datetime NULL,
	TIPANU_RETRIES_NUM int NOT NULL,
	TIPANU_CREDIT_CARD_PAYMENT_PROVIDER int NULL,
	TIPANU_CPTGC_ID numeric(18, 0) NULL,
	TIPANU_BACKOFFICE_USR_ID numeric(18, 0) NULL,
	TIPANU_PAYMENT_TYPE numeric(18, 0) NULL,
	TIPANU_ADDITIONAL_INFO varchar(255) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Table to store Ticket payments'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', NULL, NULL
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_ID'
GO
DECLARE @v sql_variant 
SET @v = N'1: Android; 2: Windows Phone; 3: iOS; 4:Blackberry; 5: Web'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_MOSE_OS'
GO
DECLARE @v sql_variant 
SET @v = N'Installation'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_INS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Date of payment'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Date of payment'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'UTC offset'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_DATE_UTC_OFFSET'
GO
DECLARE @v sql_variant 
SET @v = N'Plate related with ticket'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_USRP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'String of the plate related with the ticket'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PLATE_STRING'
GO
DECLARE @v sql_variant 
SET @v = N'Ticket Number'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TICKET_NUMBER'
GO
DECLARE @v sql_variant 
SET @v = N'Ticket Data'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TICKET_DATA'
GO
DECLARE @v sql_variant 
SET @v = N'Payed amount in Cents'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Amount Currency'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_AMOUNT_CUR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Customer Balance Currency'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_BALANCE_CUR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Change Applied between currencies'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CHANGE_APPLIED'
GO
DECLARE @v sql_variant 
SET @v = N'Change Fee Applied to the ticket Payment'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CHANGE_FEE_APPLIED'
GO
DECLARE @v sql_variant 
SET @v = N'Final Amount with change and fee applied'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_FINAL_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'ID returnted by third party service'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_EXTERNAL_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Insertion UTC DATE'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_INSERTION_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Linked recharge id if exist'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TIPANU_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Discount id if exist'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_OPEDIS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Suscription type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_SUSCRIPTION_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Balance before'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_BALANCE_BEFORE'
GO
DECLARE @v sql_variant 
SET @v = N'Confirmed in ws?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CONFIRMED_IN_WS'
GO
DECLARE @v sql_variant 
SET @v = N'Confirmation retries num'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CONFIRM_IN_WS_RETRIES_NUM'
GO
DECLARE @v sql_variant 
SET @v = N'Confirm in WS date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CONFIRM_IN_WS_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Latitude'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_LATITUDE'
GO
DECLARE @v sql_variant 
SET @v = N'Longitude'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_LONGITUDE'
GO
DECLARE @v sql_variant 
SET @v = N'App version'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_APP_VERSION'
GO
DECLARE @v sql_variant 
SET @v = N'Confirmation time in ws'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CONFIRMATION_TIME_IN_WS'
GO
DECLARE @v sql_variant 
SET @v = N'Queue before confirmation'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_QUEUE_LENGTH_BEFORE_CONFIRM_WS'
GO
DECLARE @v sql_variant 
SET @v = N'Group id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_GRP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'VAT 1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PERC_VAT1'
GO
DECLARE @v sql_variant 
SET @v = N'VAT 2'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PERC_VAT2'
GO
DECLARE @v sql_variant 
SET @v = N'VAT 1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PARTIAL_VAT1'
GO
DECLARE @v sql_variant 
SET @v = N'Percentage Fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PERC_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'Topped fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PERC_FEE_TOPPED'
GO
DECLARE @v sql_variant 
SET @v = N'Partial perc fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PARTIAL_PERC_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'Fixed Fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_FIXED_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'Partial fixed fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PARTIAL_FIXED_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'total amount'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TOTAL_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Assigned Invoice'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CUSINV_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Operation Reference'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_OP_REFERENCE'
GO
DECLARE @v sql_variant 
SET @v = N'Transaction ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TRANSACTION_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Credit call Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_GATEWAY_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Auth Code from Credit Call'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_AUTH_CODE'
GO
DECLARE @v sql_variant 
SET @v = N'Auth Result from Credit Call'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_AUTH_RESULT'
GO
DECLARE @v sql_variant 
SET @v = N'Op Reference'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_SECOND_OP_REFERENCE'
GO
DECLARE @v sql_variant 
SET @v = N'Secundary Transaction ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_SECOND_TRANSACTION_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Confirmation Gateway Result'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_SECOND_GATEWAY_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Confirmation Result'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_SECOND_AUTH_RESULT'
GO
DECLARE @v sql_variant 
SET @v = N'Card Hash'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CARD_HASH'
GO
DECLARE @v sql_variant 
SET @v = N'Card Reference'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CARD_REFERENCE'
GO
DECLARE @v sql_variant 
SET @v = N'Card Scheme'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CARD_SCHEME'
GO
DECLARE @v sql_variant 
SET @v = N'Card PAN'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_MASKED_CARD_NUMBER'
GO
DECLARE @v sql_variant 
SET @v = N'Card Expiration Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_CARD_EXPIRATION_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Paypal Token'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PAYPAL_3T_TOKEN'
GO
DECLARE @v sql_variant 
SET @v = N'Paypal ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PAYPAL_3T_PAYER_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Paypal Key with preapproved payments'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_PAYPAL_PREAPPROVED_PAY_KEY'
GO
DECLARE @v sql_variant 
SET @v = N'Total amount charged'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TOTAL_AMOUNT_CHARGED'
GO
DECLARE @v sql_variant 
SET @v = N'Transaction status'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TRANS_STATUS'
GO
DECLARE @v sql_variant 
SET @v = N'Status Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_STATUS_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Retries to confirm'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_RETRIES_NUM'
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_OPE_MOSE_OS DEFAULT ((1)) FOR TIPANU_MOSE_OS
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_UTC_DATE DEFAULT (getutcdate()) FOR TIPANU_UTC_DATE
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_date_utc_offset DEFAULT ((0)) FOR TIPANU_DATE_UTC_OFFSET
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_OPE_AMOUNT_CUR_ID DEFAULT ((50)) FOR TIPANU_AMOUNT_CUR_ID
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_OPE_BALANCE_CUR_ID DEFAULT ((50)) FOR TIPANU_BALANCE_CUR_ID
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_OPE_CHANGE_APPLIED DEFAULT ((1)) FOR TIPANU_CHANGE_APPLIED
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_SUSCRIPTION_TYPE DEFAULT ((1)) FOR TIPANU_SUSCRIPTION_TYPE
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_OPE_BALANCE_BEFORE DEFAULT ((0)) FOR TIPANU_BALANCE_BEFORE
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_TOTAL_AMOUNT_CHARGED DEFAULT ((0)) FOR TIPANU_TOTAL_AMOUNT_CHARGED
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_TRANS_STATUS DEFAULT ((4)) FOR TIPANU_TRANS_STATUS
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_STATUS_DATE DEFAULT (getdate()) FOR TIPANU_STATUS_DATE
GO
ALTER TABLE dbo.Tmp_TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_RETRIES_NUM DEFAULT ((0)) FOR TIPANU_RETRIES_NUM
GO
SET IDENTITY_INSERT dbo.Tmp_TICKET_PAYMENTS_NON_USERS ON
GO
IF EXISTS(SELECT * FROM dbo.TICKET_PAYMENTS_NON_USERS)
	 EXEC('INSERT INTO dbo.Tmp_TICKET_PAYMENTS_NON_USERS (TIPANU_ID, TIPANU_MOSE_OS, TIPANU_INS_ID, TIPANU_DATE, TIPANU_UTC_DATE, TIPANU_DATE_UTC_OFFSET, TIPANU_USRP_ID, TIPANU_PLATE_STRING, TIPANU_TICKET_NUMBER, TIPANU_TICKET_DATA, TIPANU_AMOUNT, TIPANU_AMOUNT_CUR_ID, TIPANU_BALANCE_CUR_ID, TIPANU_CHANGE_APPLIED, TIPANU_CHANGE_FEE_APPLIED, TIPANU_FINAL_AMOUNT, TIPANU_EXTERNAL_ID, TIPANU_INSERTION_UTC_DATE, TIPANU_TIPANU_ID, TIPANU_OPEDIS_ID, TIPANU_SUSCRIPTION_TYPE, TIPANU_BALANCE_BEFORE, TIPANU_CONFIRMED_IN_WS, TIPANU_CONFIRM_IN_WS_RETRIES_NUM, TIPANU_CONFIRM_IN_WS_DATE, TIPANU_LATITUDE, TIPANU_LONGITUDE, TIPANU_APP_VERSION, TIPANU_CONFIRMATION_TIME_IN_WS, TIPANU_QUEUE_LENGTH_BEFORE_CONFIRM_WS, TIPANU_GRP_ID, TIPANU_PERC_VAT1, TIPANU_PERC_VAT2, TIPANU_PARTIAL_VAT1, TIPANU_PERC_FEE, TIPANU_PERC_FEE_TOPPED, TIPANU_PARTIAL_PERC_FEE, TIPANU_FIXED_FEE, TIPANU_PARTIAL_FIXED_FEE, TIPANU_TOTAL_AMOUNT, TIPANU_CUSINV_ID, TIPANU_OP_REFERENCE, TIPANU_TRANSACTION_ID, TIPANU_GATEWAY_DATE, TIPANU_AUTH_CODE, TIPANU_AUTH_RESULT, TIPANU_SECOND_OP_REFERENCE, TIPANU_SECOND_TRANSACTION_ID, TIPANU_SECOND_GATEWAY_DATE, TIPANU_SECOND_AUTH_RESULT, TIPANU_CARD_HASH, TIPANU_CARD_REFERENCE, TIPANU_CARD_SCHEME, TIPANU_MASKED_CARD_NUMBER, TIPANU_CARD_EXPIRATION_DATE, TIPANU_PAYPAL_3T_TOKEN, TIPANU_PAYPAL_3T_PAYER_ID, TIPANU_PAYPAL_PREAPPROVED_PAY_KEY, TIPANU_TOTAL_AMOUNT_CHARGED, TIPANU_TRANS_STATUS, TIPANU_STATUS_DATE, TIPANU_RETRIES_NUM, TIPANU_CREDIT_CARD_PAYMENT_PROVIDER, TIPANU_CPTGC_ID, TIPANU_BACKOFFICE_USR_ID, TIPANU_PAYMENT_TYPE, TIPANU_ADDITIONAL_INFO)
		SELECT TIPANU_ID, TIPANU_MOSE_OS, TIPANU_INS_ID, TIPANU_DATE, TIPANU_UTC_DATE, TIPANU_DATE_UTC_OFFSET, TIPANU_USRP_ID, TIPANU_PLATE_STRING, TIPANU_TICKET_NUMBER, TIPANU_TICKET_DATA, TIPANU_AMOUNT, TIPANU_AMOUNT_CUR_ID, TIPANU_BALANCE_CUR_ID, TIPANU_CHANGE_APPLIED, TIPANU_CHANGE_FEE_APPLIED, TIPANU_FINAL_AMOUNT, TIPANU_EXTERNAL_ID, TIPANU_INSERTION_UTC_DATE, TIPANU_TIPANU_ID, TIPANU_OPEDIS_ID, TIPANU_SUSCRIPTION_TYPE, TIPANU_BALANCE_BEFORE, TIPANU_CONFIRMED_IN_WS, TIPANU_CONFIRM_IN_WS_RETRIES_NUM, TIPANU_CONFIRM_IN_WS_DATE, TIPANU_LATITUDE, TIPANU_LONGITUDE, TIPANU_APP_VERSION, TIPANU_CONFIRMATION_TIME_IN_WS, TIPANU_QUEUE_LENGTH_BEFORE_CONFIRM_WS, TIPANU_GRP_ID, TIPANU_PERC_VAT1, TIPANU_PERC_VAT2, TIPANU_PARTIAL_VAT1, TIPANU_PERC_FEE, TIPANU_PERC_FEE_TOPPED, TIPANU_PARTIAL_PERC_FEE, TIPANU_FIXED_FEE, TIPANU_PARTIAL_FIXED_FEE, TIPANU_TOTAL_AMOUNT, TIPANU_CUSINV_ID, TIPANU_OP_REFERENCE, TIPANU_TRANSACTION_ID, TIPANU_GATEWAY_DATE, TIPANU_AUTH_CODE, TIPANU_AUTH_RESULT, TIPANU_SECOND_OP_REFERENCE, TIPANU_SECOND_TRANSACTION_ID, TIPANU_SECOND_GATEWAY_DATE, TIPANU_SECOND_AUTH_RESULT, TIPANU_CARD_HASH, TIPANU_CARD_REFERENCE, TIPANU_CARD_SCHEME, TIPANU_MASKED_CARD_NUMBER, TIPANU_CARD_EXPIRATION_DATE, TIPANU_PAYPAL_3T_TOKEN, TIPANU_PAYPAL_3T_PAYER_ID, TIPANU_PAYPAL_PREAPPROVED_PAY_KEY, TIPANU_TOTAL_AMOUNT_CHARGED, TIPANU_TRANS_STATUS, TIPANU_STATUS_DATE, TIPANU_RETRIES_NUM, TIPANU_CREDIT_CARD_PAYMENT_PROVIDER, TIPANU_CPTGC_ID, TIPANU_BACKOFFICE_USR_ID, TIPANU_PAYMENT_TYPE, TIPANU_ADDITIONAL_INFO FROM dbo.TICKET_PAYMENTS_NON_USERS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_TICKET_PAYMENTS_NON_USERS OFF
GO
DROP TABLE dbo.TICKET_PAYMENTS_NON_USERS
GO
EXECUTE sp_rename N'dbo.Tmp_TICKET_PAYMENTS_NON_USERS', N'TICKET_PAYMENTS_NON_USERS', 'OBJECT' 
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	PK_TICKET_PAYMENTS_NON_USERS PRIMARY KEY CLUSTERED 
	(
	TIPANU_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_1 FOREIGN KEY
	(
	TIPANU_AMOUNT_CUR_ID
	) REFERENCES dbo.CURRENCIES
	(
	CUR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_2 FOREIGN KEY
	(
	TIPANU_BALANCE_CUR_ID
	) REFERENCES dbo.CURRENCIES
	(
	CUR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_CUSTOMER_INVOICES FOREIGN KEY
	(
	TIPANU_CUSINV_ID
	) REFERENCES dbo.CUSTOMER_INVOICES
	(
	CUSINV_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_GROUPS FOREIGN KEY
	(
	TIPANU_GRP_ID
	) REFERENCES dbo.GROUPS
	(
	GRP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_INSTALLATIONS FOREIGN KEY
	(
	TIPANU_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_OPERATIONS_DISCOUNTS FOREIGN KEY
	(
	TIPANU_OPEDIS_ID
	) REFERENCES dbo.OPERATIONS_DISCOUNTS
	(
	OPEDIS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_NON_USERS_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG FOREIGN KEY
	(
	TIPANU_CPTGC_ID
	) REFERENCES dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
	(
	CPTGC_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT