/****** Object:  Table [dbo].[GATEWAY_BENEFIT]    Script Date: 10/11/2019 5:18:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GATEWAY_BENEFIT](
	[GTWB_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[GTWB_CPTGC_ID] [numeric](18, 0) NOT NULL,
	[GTWB_DATE] [datetime] NOT NULL,
	[GTWB_BACKOFFICE_PAYMENTS] [int] NOT NULL,
	[GTWB_BACKOFFICE_REFUNDS] [int] NOT NULL,
	[GTWB_BACKOFFICE_BASE] [numeric](18, 0) NOT NULL,
	[GTWB_BACKOFFICE_GROSS] [numeric](18, 0) NOT NULL,
	[GTWB_BACKOFFICE_FEE_INTEGRA] [numeric](18, 0) NOT NULL,
	[GTWB_BACKOFFICE_FEE_GATEWAY] [numeric](18, 0) NOT NULL,
	[GTWB_BACKOFFICE_NET]  AS ([GTWB_BACKOFFICE_GROSS]-[GTWB_BACKOFFICE_FEE_GATEWAY]) PERSISTED,
	[GTWB_BACKOFFICE_BENEFIT]  AS (([GTWB_BACKOFFICE_GROSS]-[GTWB_BACKOFFICE_FEE_GATEWAY])-[GTWB_BACKOFFICE_BASE]) PERSISTED,
	[GTWB_BANK_GROSS] [numeric](18, 0) NOT NULL,
	[GTWB_BANK_FEE] [numeric](18, 0) NOT NULL,
	[GTWB_BANK_NET]  AS ([GTWB_BANK_GROSS]-[GTWB_BANK_FEE]) PERSISTED,
	[GTWB_BANK_BENEFIT]  AS (([GTWB_BANK_GROSS]-[GTWB_BANK_FEE])-[GTWB_BACKOFFICE_BASE]) PERSISTED,
	[GTWB_IMBALANCE_GROSS]  AS (case when [GTWB_BANK_GROSS]=(0) then NULL else ([GTWB_BANK_GROSS]-[GTWB_BACKOFFICE_GROSS])/[GTWB_BANK_GROSS] end) PERSISTED,
	[GTWB_IMBALANCE_FEE]  AS (case when [GTWB_BANK_FEE]=(0) then NULL else ([GTWB_BANK_FEE]-[GTWB_BACKOFFICE_FEE_GATEWAY])/[GTWB_BANK_FEE] end) PERSISTED,
	[GTWB_IMBALANCE_NET]  AS (case when ([GTWB_BANK_GROSS]-[GTWB_BANK_FEE])=(0) then NULL else (([GTWB_BANK_GROSS]-[GTWB_BANK_FEE])-([GTWB_BACKOFFICE_GROSS]-[GTWB_BACKOFFICE_FEE_GATEWAY]))/([GTWB_BANK_GROSS]-[GTWB_BANK_FEE]) end) PERSISTED,
 CONSTRAINT [PK_GATEWAY_BENEFIT] PRIMARY KEY CLUSTERED 
(
	[GTWB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_PAYMENTS]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_PAYMENTS]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_REFUNDS]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_REFUNDS]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_BASE]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_BASE]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_GROSS]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_GROSS]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_FEE_INTEGRA]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_FEE_INTEGRA]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BACKOFFICE_FEE_GATEWAY]  DEFAULT ((0)) FOR [GTWB_BACKOFFICE_FEE_GATEWAY]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BANK_GROSS]  DEFAULT ((0)) FOR [GTWB_BANK_GROSS]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] ADD  CONSTRAINT [DF_GATEWAY_BENEFIT_GTWB_BANK_FEE]  DEFAULT ((0)) FOR [GTWB_BANK_FEE]
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT]  WITH CHECK ADD  CONSTRAINT [FK_GATEWAY_BENEFIT_CPTGC] FOREIGN KEY([GTWB_CPTGC_ID])
REFERENCES [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG] ([CPTGC_ID])
GO

ALTER TABLE [dbo].[GATEWAY_BENEFIT] CHECK CONSTRAINT [FK_GATEWAY_BENEFIT_CPTGC]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'GROSS - BASE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_BACKOFFICE_FEE_INTEGRA'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'GROSS - FEE GATEWAY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_BACKOFFICE_NET'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NET - BASE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_BACKOFFICE_BENEFIT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'GROSS - FEE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_BANK_NET'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NET - BASE BACKOFFICE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_BANK_BENEFIT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'BANK GROSS - BACKOFFICE GROSS / BANK GROSS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'GATEWAY_BENEFIT', @level2type=N'COLUMN',@level2name=N'GTWB_IMBALANCE_GROSS'
GO


