/****** Object:  Table [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION]    Script Date: 21/10/2019 16:50:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION](
	[CPTGCL_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CPTGCL_CPTGC_ID] [numeric](18, 0) NOT NULL,
	[CPTGCL_DATE] [datetime] NOT NULL,
	[CPTGCL_UTC_DATE] [datetime] NOT NULL,
	[CPTGCL_GATEWAY_CUR_ID] [numeric](18, 0) NOT NULL,
	[CPTGCL_USER_CUR_ID] [numeric](18, 0) NOT NULL,
	[CPTGCL_CHANGE_APPLIED] [numeric](18, 0) NOT NULL,
	[CPTGCL_USR_AMOUNT] [int] NOT NULL,
	[CPTGCL_AMOUNT] [int] NOT NULL,
	[CPTGCL_USR_ID] [numeric](18, 0) NOT NULL,
	[CPTGCL_OPE_TYPE] [int] NOT NULL,
	[CPTGCL_OPE_ID] [numeric](18, 0) NULL,
	[CPTGCL_TIPA_ID] [numeric](18, 0) NULL,
	[CPTGCL_OPEOFF_ID] [numeric](18, 0) NULL,
	[CPTGCL_TOLM_ID] [numeric](18, 0) NULL,
	[CPTGCL_SECH_ID] [numeric](18, 0) NULL,
 CONSTRAINT [PK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION] PRIMARY KEY CLUSTERED 
(
	[CPTGCL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION]  WITH CHECK ADD  CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES] FOREIGN KEY([CPTGCL_GATEWAY_CUR_ID])
REFERENCES [dbo].[CURRENCIES] ([CUR_ID])
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION] CHECK CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES]
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION]  WITH CHECK ADD  CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG] FOREIGN KEY([CPTGCL_CPTGC_ID])
REFERENCES [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG] ([CPTGC_ID])
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION] CHECK CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG]
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION]  WITH CHECK ADD  CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES1] FOREIGN KEY([CPTGCL_USER_CUR_ID])
REFERENCES [dbo].[CURRENCIES] ([CUR_ID])
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION] CHECK CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_CURRENCIES1]
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION]  WITH CHECK ADD  CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_USERS] FOREIGN KEY([CPTGCL_USR_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION] CHECK CONSTRAINT [FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LIQUIDATION_USERS]
GO
