ALTER VIEW [dbo].[VW_ACTIVE_PERMIT_OPERATIONS]
AS
SELECT        o1.OPE_ID, o1.OPE_USR_ID, o1.OPE_MOSE_OS, o1.OPE_USRP_ID, o1.OPE_INS_ID, o1.OPE_TYPE, o1.OPE_GRP_ID, o1.OPE_TAR_ID, o1.OPE_DATE, o1.OPE_INIDATE, o1.OPE_ENDDATE, o1.OPE_UTC_DATE, 
                         o1.OPE_UTC_INIDATE, o1.OPE_UTC_ENDDATE, o1.OPE_DATE_UTC_OFFSET, o1.OPE_INIDATE_UTC_OFFSET, o1.OPE_ENDDATE_UTC_OFFSET, o1.OPE_AMOUNT, o1.OPE_TIME, o1.OPE_AMOUNT_CUR_ID, 
                         o1.OPE_BALANCE_CUR_ID, o1.OPE_CHANGE_APPLIED, o1.OPE_CHANGE_FEE_APPLIED, o1.OPE_FINAL_AMOUNT, o1.OPE_EXTERNAL_ID1, o1.OPE_EXTERNAL_ID2, o1.OPE_EXTERNAL_ID3, o1.OPE_INSERTION_UTC_DATE, 
                         o1.OPE_CUSPMR_ID, o1.OPE_OPEDIS_ID, o1.OPE_BALANCE_BEFORE, o1.OPE_SUSCRIPTION_TYPE, o1.OPE_CONFIRMED_IN_WS1, o1.OPE_CONFIRMED_IN_WS2, o1.OPE_CONFIRMED_IN_WS3, 
                         o1.OPE_CONFIRM_IN_WS1_RETRIES_NUM, o1.OPE_CONFIRM_IN_WS2_RETRIES_NUM, o1.OPE_CONFIRM_IN_WS3_RETRIES_NUM, o1.OPE_CONFIRM_IN_WS1_DATE, o1.OPE_CONFIRM_IN_WS2_DATE, 
                         o1.OPE_CONFIRM_IN_WS3_DATE, o1.OPE_MOSE_ID, o1.OPE_LATITUDE, o1.OPE_LONGITUDE, o1.OPE_APP_VERSION, o1.OPE_CONFIRMATION_TIME_IN_WS1, o1.OPE_CONFIRMATION_TIME_IN_WS2, 
                         o1.OPE_CONFIRMATION_TIME_IN_WS3, o1.OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS1, o1.OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS2, o1.OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS3, o1.OPE_PERC_VAT1, 
                         o1.OPE_PERC_VAT2, o1.OPE_PARTIAL_VAT1, o1.OPE_PERC_FEE, o1.OPE_PERC_FEE_TOPPED, o1.OPE_PARTIAL_PERC_FEE, o1.OPE_FIXED_FEE, o1.OPE_PARTIAL_FIXED_FEE, o1.OPE_PERC_BONUS, 
                         o1.OPE_PARTIAL_BONUS_FEE, o1.OPE_TOTAL_AMOUNT, o1.OPE_CUSINV_ID, o1.OPE_BONUS_ID, o1.OPE_BONUS_MARCA, o1.OPE_BONUS_TYPE, o1.OPE_SPACE_STRING, o1.OPE_TIME_BALANCE_USED, 
                         o1.OPE_TIME_BALANCE_BEFORE, o1.OPE_REAL_AMOUNT, o1.OPE_POSTPAY, o1.OPE_REFUND_PREVIOUS_ENDDATE, o1.OPE_SHOPKEEPER_OP, o1.OPE_SHOPKEEPER_PROFIT, o1.OPE_SHOPKEEPER_AMOUNT, 
                         o1.OPE_AUTH_ID, o1.OPE_AMOUNT_WITHOUT_BON, o1.OPE_BON_MLT, o1.OPE_VEHICLE_TYPE, o1.OPE_BACKOFFICE_USR, o1.OPE_STOP_DATE, o1.OPE_UTC_STOP_DATE, o1.OPE_PARKING_MODE, 
                         o1.OPE_PARKING_MODE_STATUS, o1.OPE_EXTERNAL_BASE_ID1, o1.OPE_EXTERNAL_BASE_ID2, o1.OPE_EXTERNAL_BASE_ID3, o1.OPE_PERMIT_AUTO_RENEW, o1.OPE_PERMIT_EXPIRATION_TIME, 
                         o1.OPE_PERMIT_LAST_AUTORENEWAL_DATE, o1.OPE_PERMIT_LAST_AUTORENEWAL_NUM_RETRIES, o1.OPE_PERMIT_LAST_AUTORENEWAL_STATUS, o1.OPE_PERMIT_EXPIRATION_UTC_TIME, 
                         o1.OPE_PLATE2_USRP_ID, o1.OPE_PLATE3_USRP_ID, o1.OPE_PLATE4_USRP_ID, o1.OPE_PLATE5_USRP_ID, o1.OPE_PLATE6_USRP_ID, o1.OPE_PLATE7_USRP_ID, o1.OPE_PLATE8_USRP_ID, o1.OPE_PLATE9_USRP_ID, 
                         o1.OPE_PLATE10_USRP_ID, o1.OPE_REL_OPE_ID, o1.OPE_CONFIRM_MODE, o1.OPE_PERMIT_LAST_AUTORENEWAL_RESULT, o1.OPE_ADDITIONAL_PARAMS, o1.OPE_EXPIRE_SMS_SENT, 
                         c.CUR_ISO_CODE AS OPE_AMOUNT_CUR_ISO_CODE, c.CUR_MINOR_UNIT AS OPE_AMOUNT_CUR_MINOR_UNIT, t.TAR_DESCRIPTION, p1.USRP_PLATE, p1.USRP_ID, g.GRP_DESCRIPTION, u.USR_USERNAME, 
                         i.INS_STANDARD_CITY_ID, i.INS_DESCRIPTION, p2.USRP_PLATE AS USRP_PLATE2, p3.USRP_PLATE AS USRP_PLATE3, p4.USRP_PLATE AS USRP_PLATE4, p5.USRP_PLATE AS USRP_PLATE5, 
                         p6.USRP_PLATE AS USRP_PLATE6, p7.USRP_PLATE AS USRP_PLATE7, p8.USRP_PLATE AS USRP_PLATE8, p9.USRP_PLATE AS USRP_PLATE9, p10.USRP_PLATE AS USRP_PLATE10, g.GRP_PERMIT_MAX_MONTHS, 
                         g.GRP_INS_ID
FROM            dbo.OPERATIONS AS o1 LEFT OUTER JOIN
                         dbo.USER_PLATES AS p2 ON p2.USRP_ID = o1.OPE_PLATE2_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p3 ON p3.USRP_ID = o1.OPE_PLATE3_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p4 ON p4.USRP_ID = o1.OPE_PLATE4_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p5 ON p5.USRP_ID = o1.OPE_PLATE5_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p6 ON p6.USRP_ID = o1.OPE_PLATE6_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p7 ON p7.USRP_ID = o1.OPE_PLATE7_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p8 ON p8.USRP_ID = o1.OPE_PLATE8_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p9 ON p9.USRP_ID = o1.OPE_PLATE9_USRP_ID LEFT OUTER JOIN
                         dbo.USER_PLATES AS p10 ON p10.USRP_ID = o1.OPE_PLATE10_USRP_ID INNER JOIN
                         dbo.TARIFFS AS t ON o1.OPE_TAR_ID = t.TAR_ID INNER JOIN
                         dbo.USER_PLATES AS p1 ON o1.OPE_USRP_ID = p1.USRP_ID INNER JOIN
                         dbo.CURRENCIES AS c ON o1.OPE_AMOUNT_CUR_ID = c.CUR_ID INNER JOIN
                         dbo.GROUPS AS g ON o1.OPE_GRP_ID = g.GRP_ID INNER JOIN
                         dbo.USERS AS u ON o1.OPE_USR_ID = u.USR_ID INNER JOIN
                         dbo.INSTALLATIONS AS i ON o1.OPE_INS_ID = i.INS_ID
WHERE        (o1.OPE_UTC_ENDDATE >= GETUTCDATE()) AND (t.TAR_TYPE = 1) OR
                         (t.TAR_TYPE = 1) AND (o1.OPE_PERMIT_EXPIRATION_UTC_TIME >= GETUTCDATE()) AND
                             ((SELECT        COUNT(*) AS Expr1
                                 FROM            dbo.OPERATIONS AS o2 INNER JOIN
                                                          dbo.TARIFFS AS t2 ON o2.OPE_TAR_ID = t2.TAR_ID
                                 WHERE        (o2.OPE_TAR_ID = o1.OPE_TAR_ID) AND (t2.TAR_TYPE = 1) AND (o2.OPE_INS_ID = o1.OPE_INS_ID) AND (o2.OPE_GRP_ID = o1.OPE_GRP_ID) AND (o2.OPE_INIDATE BETWEEN o1.OPE_ENDDATE AND 
                                                          o2.OPE_PERMIT_EXPIRATION_TIME) AND (dbo.OperationPlatesString(o2.OPE_ID) = dbo.OperationPlatesString(o1.OPE_ID))) = 0)