/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD
	INS_PAYPAL_CPTGC_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	FK_INSTALLATIONS_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG1 FOREIGN KEY
	(
	INS_PAYPAL_CPTGC_ID
	) REFERENCES dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
	(
	CPTGC_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT



--INSERT INTO [dbo].[CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG]([CPTGC_DESCRIPTION],[CPTGC_PAT_ID],[CPTGC_CUR_ID],[CPTGC_PAT_FIXED_FEE],[CPTGC_PAT_PERC_FEE],[CPTGC_PROVIDER],[CPTGC_PP_RESTAPI_URL_PREFIX]
--,[CPTGC_PP_RESTAPI_CLIENT_ID],[CPTGC_PP_RESTAPI_CLIENT_SECRET],[CPTGC_PP_RESTAPI_ENVIRONMENT],[CPTGC_ENABLED],[CPTGC_FORM_URL],[CPTGC_STRCON_ID],[CPTGC_MIN_CHARGE],[CPTGC_IECCON_ID]
--,[CPTGC_CCCON_ID],[CPTGC_MONCON_ID],[CPTGC_TRBACON_ID],[CPTGC_PAYUCON_ID],[CPTGC_CTG_ID],[CPTGC_IS_INTERNAL],[CPTGC_BSRCON_ID],[CPTGC_PYSCON_ID],[CPTGC_LOCAL_BATCH_TIME],[CPTGC_TIMEZONE]
--,[CPTGC_FIXED_FEE],[CPTGC_PERC_FEE],[CPTGC_MIN_FEE])
--VALUES('Paypal CAD Canada Wide Parking',2,28,0,0.00000,3,'https://api.sandbox.paypal.com/v1/','AYHorKnEhOo7Wni9WkNCCTF1nTa4wr2_-8izgrDsRXGlBqO7gCG8RyPFkuAOAkB-QC9JThQS_5MN8G_G'
--,'EHyjggDTu0LZadQ_EFhKjtN5Iw77B42EzzlvZhHbx4J3xXTLBaaDhrRzUagpws3XSHsSh-9fIjXHQm8g'
--,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,'23:00','Eastern Standard Time',0,0.00000,1)