CREATE TABLE [dbo].[CAMPAINGS_GROUPS](
	[CAMP_GRP_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CAMP_GRP_CAMP_ID] [numeric](18, 0) NOT NULL,
	[CAMP_GRP_GRP_ID] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_CAMPAINGS_GROUPS] PRIMARY KEY CLUSTERED 
(
	[CAMP_GRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CAMPAINGS_GROUPS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAINGS_GROUPS_CAMPAING] FOREIGN KEY([CAMP_GRP_CAMP_ID])
REFERENCES [dbo].[CAMPAING] ([CAMP_ID])
GO

ALTER TABLE [dbo].[CAMPAINGS_GROUPS] CHECK CONSTRAINT [FK_CAMPAINGS_GROUPS_CAMPAING]
GO

ALTER TABLE [dbo].[CAMPAINGS_GROUPS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAINGS_GROUPS_GROUPS] FOREIGN KEY([CAMP_GRP_GRP_ID])
REFERENCES [dbo].[GROUPS] ([GRP_ID])
GO

ALTER TABLE [dbo].[CAMPAINGS_GROUPS] CHECK CONSTRAINT [FK_CAMPAINGS_GROUPS_GROUPS]
GO


