CREATE TABLE [dbo].[CAMPAING_OPERATIONS](
	[CAMP_OPE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CAMP_OPE_OPE_ID] [numeric](18, 0) NOT NULL,
	[CAMP_OPE_USR_ID] [numeric](18, 0) NOT NULL,
	[CAMP_OPE_GRP_ID] [numeric](18, 0) NOT NULL,
	[CAMP_OPE_CAMP_ID] [numeric](18, 0) NOT NULL,
	[CAMP_OPE_NUM_BON_PARK] [numeric](18, 0) NOT NULL,
	[CAMP_OPE_APPLY_DISCOUNT] [int] NOT NULL,
 CONSTRAINT [PK_CAMPAING_OPERATIONS] PRIMARY KEY CLUSTERED 
(
	[CAMP_OPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS] ADD  CONSTRAINT [DF_CAMPAING_OPERATIONS_CAMP_OPE_APPLY_DISCOUNT]  DEFAULT ((0)) FOR [CAMP_OPE_APPLY_DISCOUNT]
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_OPERATIONS_CAMPAING] FOREIGN KEY([CAMP_OPE_CAMP_ID])
REFERENCES [dbo].[CAMPAING] ([CAMP_ID])
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS] CHECK CONSTRAINT [FK_CAMPAING_OPERATIONS_CAMPAING]
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_OPERATIONS_GROUPS] FOREIGN KEY([CAMP_OPE_GRP_ID])
REFERENCES [dbo].[GROUPS] ([GRP_ID])
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS] CHECK CONSTRAINT [FK_CAMPAING_OPERATIONS_GROUPS]
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_OPERATIONS_HIS_OPERATIONS] FOREIGN KEY([CAMP_OPE_OPE_ID])
REFERENCES [dbo].[HIS_OPERATIONS] ([OPE_ID])
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS] CHECK CONSTRAINT [FK_CAMPAING_OPERATIONS_HIS_OPERATIONS]
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_OPERATIONS_USERS] FOREIGN KEY([CAMP_OPE_USR_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[CAMPAING_OPERATIONS] CHECK CONSTRAINT [FK_CAMPAING_OPERATIONS_USERS]
GO


