CREATE TABLE [dbo].[SERVICES_STATUS](
	[SERSTA_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SERSTA_DESCRIPTION] [varchar](200) NOT NULL,
	[SERSTA_LIT_ID] [numeric](18, 0) NULL,
 CONSTRAINT [PK_SERVICES_STATUS] PRIMARY KEY CLUSTERED 
(
	[SERSTA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SERVICES_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_SERVICES_STATUS_LITERALS] FOREIGN KEY([SERSTA_LIT_ID])
REFERENCES [dbo].[LITERALS] ([LIT_ID])
GO

ALTER TABLE [dbo].[SERVICES_STATUS] CHECK CONSTRAINT [FK_SERVICES_STATUS_LITERALS]
GO


