CREATE TABLE [dbo].[SERVICES_USER_PLATES](
	[SERUP_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SERUP_SERSTA_ID] [numeric](18, 0) NOT NULL,
	[SERUP_USRP_ID] [numeric](18, 0) NOT NULL,
	[SERUP_FIRST_NAME] [varchar](200) NULL,
	[SERUP_LAST_NAME] [varchar](200) NULL,
	[SERUP_CARD_REDUCED_MOVILITY] [varchar](200) NULL,
	[SERUP_COMPANY_NAME] [varchar](200) NULL,
	[SERUP_CIF_NIF_COMPANY] [varchar](200) NULL,
	[SERUP_ENABLED] [int] NOT NULL,
	[SERUP_DATE_LAST_UPDATE] [datetime] NULL,
 CONSTRAINT [PK_SERVICES_USER_PLATES] PRIMARY KEY CLUSTERED 
(
	[SERUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SERVICES_USER_PLATES] ADD  CONSTRAINT [DF_SERVICES_USER_PLATES_SERUP_ENABLED]  DEFAULT ((1)) FOR [SERUP_ENABLED]
GO

ALTER TABLE [dbo].[SERVICES_USER_PLATES]  WITH CHECK ADD  CONSTRAINT [FK_SERVICES_USER_PLATES_SERVICES_STATUS] FOREIGN KEY([SERUP_SERSTA_ID])
REFERENCES [dbo].[SERVICES_STATUS] ([SERSTA_ID])
GO

ALTER TABLE [dbo].[SERVICES_USER_PLATES] CHECK CONSTRAINT [FK_SERVICES_USER_PLATES_SERVICES_STATUS]
GO

ALTER TABLE [dbo].[SERVICES_USER_PLATES]  WITH CHECK ADD  CONSTRAINT [FK_SERVICES_USER_PLATES_USER_PLATES] FOREIGN KEY([SERUP_USRP_ID])
REFERENCES [dbo].[USER_PLATES] ([USRP_ID])
GO

ALTER TABLE [dbo].[SERVICES_USER_PLATES] CHECK CONSTRAINT [FK_SERVICES_USER_PLATES_USER_PLATES]
GO