CREATE TABLE [dbo].[TARIFFS_CUSTOM_MESSAGE](
	[TARCME_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TARCME_TAR_ID] [numeric](18, 0) NOT NULL,
	[TARCME_ENABLED] [int] NOT NULL,
	[TARCME_UNDER_WHEEL_LIT_ID] [numeric](18, 0) NULL,
	[TARCME_BUTTON_STOP_LIT_ID] [numeric](18, 0) NULL,
	[TARCME_END_PARKING_LIT_ID] [numeric](18, 0) NULL,
	[TARCME_BUTTON_END_PARKING_LIT_ID] [numeric](18, 0) NULL,
	[TARCME_DATE_INI] [datetime] NULL,
	[TARCME_DATE_END] [datetime] NULL,
 CONSTRAINT [PK_TARIFFS_CUSTOM_MESSAGE] PRIMARY KEY CLUSTERED 
(
	[TARCME_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TARIFFS_CUSTOM_MESSAGE] ADD  CONSTRAINT [DF_TARIFFS_CUSTOM_MESSAGE_TARCME_ENABLED]  DEFAULT ((1)) FOR [TARCME_ENABLED]
GO

ALTER TABLE [dbo].[TARIFFS_CUSTOM_MESSAGE]  WITH CHECK ADD  CONSTRAINT [FK_TARIFFS_CUSTOM_MESSAGE_TARIFFS] FOREIGN KEY([TARCME_TAR_ID])
REFERENCES [dbo].[TARIFFS] ([TAR_ID])
GO

ALTER TABLE [dbo].[TARIFFS_CUSTOM_MESSAGE] CHECK CONSTRAINT [FK_TARIFFS_CUSTOM_MESSAGE_TARIFFS]
GO


