/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
/*NO PASAR A PRODUCCION*/
/*NO PASAR A PRODUCCION*/
/*NO PASAR A PRODUCCION*/
/*NO PASAR A PRODUCCION*/
/*NO PASAR A PRODUCCION*/
/*
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SERVICES_TYPE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	FK_TARIFFS_SERVICES_TYPE FOREIGN KEY
	(
	TAR_SERTYP_ID
	) REFERENCES dbo.SERVICES_TYPE
	(
	SERTYP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT*/