/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ADD
	CUSPMR_BALANCE_BONIFICATION_AMOUNT int NOT NULL CONSTRAINT DF_CUSTOMER_PAYMENT_MEANS_RECHARGES_CUSPMR_AMOUNT1 DEFAULT ((0))
GO
DECLARE @v sql_variant 
SET @v = N'Bonified Amount in recharges'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS_RECHARGES', N'COLUMN', N'CUSPMR_BALANCE_BONIFICATION_AMOUNT'
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
