/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SERVICES_USER_PLATES ADD
	SERUP_INS_ID numeric(18, 0) NULL,
	SERUP_SERTYP_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.SERVICES_USER_PLATES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SERVICES_TYPE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SERVICES_USER_PLATES ADD CONSTRAINT
	FK_SERVICES_USER_PLATES_INSTALLATIONS FOREIGN KEY
	(
	SERUP_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SERVICES_USER_PLATES ADD CONSTRAINT
	FK_SERVICES_USER_PLATES_SERVICES_TYPE FOREIGN KEY
	(
	SERUP_SERTYP_ID
	) REFERENCES dbo.SERVICES_TYPE
	(
	SERTYP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SERVICES_USER_PLATES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

