/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SESSION_VARIABLES_STORE
	DROP CONSTRAINT DF_SESSION_VARIABLES_STORE_SVS_INSERTION_DATE
GO
CREATE TABLE dbo.Tmp_SESSION_VARIABLES_STORE
	(
	SVS_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	SVS_KEY varchar(100) NOT NULL,
	SVS_VALUE ntext NOT NULL,
	SVS_INSERTION_DATE datetime NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_SESSION_VARIABLES_STORE SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_SESSION_VARIABLES_STORE', N'COLUMN', N'SVS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Key'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_SESSION_VARIABLES_STORE', N'COLUMN', N'SVS_KEY'
GO
DECLARE @v sql_variant 
SET @v = N'Session info'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_SESSION_VARIABLES_STORE', N'COLUMN', N'SVS_VALUE'
GO
DECLARE @v sql_variant 
SET @v = N'UTC Insertion Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_SESSION_VARIABLES_STORE', N'COLUMN', N'SVS_INSERTION_DATE'
GO
ALTER TABLE dbo.Tmp_SESSION_VARIABLES_STORE ADD CONSTRAINT
	DF_SESSION_VARIABLES_STORE_SVS_INSERTION_DATE DEFAULT (getutcdate()) FOR SVS_INSERTION_DATE
GO
SET IDENTITY_INSERT dbo.Tmp_SESSION_VARIABLES_STORE ON
GO
IF EXISTS(SELECT * FROM dbo.SESSION_VARIABLES_STORE)
	 EXEC('INSERT INTO dbo.Tmp_SESSION_VARIABLES_STORE (SVS_ID, SVS_KEY, SVS_VALUE, SVS_INSERTION_DATE)
		SELECT SVS_ID, SVS_KEY, CONVERT(ntext, SVS_VALUE), SVS_INSERTION_DATE FROM dbo.SESSION_VARIABLES_STORE WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_SESSION_VARIABLES_STORE OFF
GO
DROP TABLE dbo.SESSION_VARIABLES_STORE
GO
EXECUTE sp_rename N'dbo.Tmp_SESSION_VARIABLES_STORE', N'SESSION_VARIABLES_STORE', 'OBJECT' 
GO
ALTER TABLE dbo.SESSION_VARIABLES_STORE ADD CONSTRAINT
	PK_SESSION_VARIABLES_STORE PRIMARY KEY CLUSTERED 
	(
	SVS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX IND_SVS_KEY ON dbo.SESSION_VARIABLES_STORE
	(
	SVS_KEY
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
COMMIT