/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION1
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_USERS
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS
GO
ALTER TABLE dbo.TICKET_PAYMENTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_OPERATIONS
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_CAMPAIGN_USER_USE
	(
	CAUSS_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CAUSS_CAUS_ID numeric(18, 0) NULL,
	CAUSS_DATE date NOT NULL,
	CAUSS_UTC_DATE date NOT NULL,
	CAUSS_OPE_ID numeric(18, 0) NULL,
	CAUSS_TIPA_ID numeric(18, 0) NULL,
	CAUSS_CUSPMR_ID numeric(18, 0) NULL,
	CAUSS_USRF_ACCEPT_USR_ID numeric(18, 0) NULL,
	CAUSS_CELL_IMEI varchar(100) NULL,
	CAUSS_CAMP_ID numeric(18, 0) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CAMPAIGN_USER_USE SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAIGN_USER_USE ON
GO
IF EXISTS(SELECT * FROM dbo.CAMPAIGN_USER_USE)
	 EXEC('INSERT INTO dbo.Tmp_CAMPAIGN_USER_USE (CAUSS_ID, CAUSS_CAUS_ID, CAUSS_DATE, CAUSS_UTC_DATE, CAUSS_OPE_ID, CAUSS_TIPA_ID, CAUSS_CUSPMR_ID, CAUSS_USRF_ACCEPT_USR_ID, CAUSS_CELL_IMEI, CAUSS_CAMP_ID)
		SELECT CAUSS_ID, CAUSS_CAUS_ID, CAUSS_DATE, CAUSS_UTC_DATE, CAUSS_OPE_ID, CAUSS_TIPA_ID, CAUSS_CUSPMR_ID, CAUSS_USRF_ACCEPT_USR_ID, CAUSS_CELL_IMEI, CAUSS_CAMP_ID FROM dbo.CAMPAIGN_USER_USE WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAIGN_USER_USE OFF
GO
DROP TABLE dbo.CAMPAIGN_USER_USE
GO
EXECUTE sp_rename N'dbo.Tmp_CAMPAIGN_USER_USE', N'CAMPAIGN_USER_USE', 'OBJECT' 
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	PK_CAMPAIGN_USER_USE PRIMARY KEY CLUSTERED 
	(
	CAUSS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES FOREIGN KEY
	(
	CAUSS_CUSPMR_ID
	) REFERENCES dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES
	(
	CUSPMR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_OPERATIONS FOREIGN KEY
	(
	CAUSS_OPE_ID
	) REFERENCES dbo.HIS_OPERATIONS
	(
	OPE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS FOREIGN KEY
	(
	CAUSS_TIPA_ID
	) REFERENCES dbo.TICKET_PAYMENTS
	(
	TIPA_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_USERS FOREIGN KEY
	(
	CAUSS_USRF_ACCEPT_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION1 FOREIGN KEY
	(
	CAUSS_CAUS_ID
	) REFERENCES dbo.CAMPAING_USER_ASSIGNATION
	(
	CAUS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CAMPAING FOREIGN KEY
	(
	CAUSS_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_SESSION_INFO ADD
	OSI_CAMPAIGN_OPE_INDEX int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Campaing 4 operation index'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'OPERATIONS_SESSION_INFO', N'COLUMN', N'OSI_CAMPAIGN_OPE_INDEX'
GO
ALTER TABLE dbo.OPERATIONS_SESSION_INFO SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
