/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING
	DROP CONSTRAINT FK_CAMPAING_COUNTRIES
GO
ALTER TABLE dbo.COUNTRIES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_USERS
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION
	DROP CONSTRAINT FK_CAMPAING_USER_ASSIGNATION_USERS
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS
GO
ALTER TABLE dbo.TICKET_PAYMENTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_OPERATIONS
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING
	DROP CONSTRAINT DF_CAMPAING_CAMP_STATUS
GO
CREATE TABLE dbo.Tmp_CAMPAING
	(
	CAMP_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CAMP_DESCRIPTION nvarchar(100) NULL,
	CAMP_SCHEMA numeric(18, 0) NOT NULL,
	CAMP_STATUS int NOT NULL,
	CAMP_COU_ID numeric(18, 0) NOT NULL,
	CAMP_MAX_DELIVER_AMOUNT int NOT NULL,
	CAMP_INSERTION_UTC_DATE datetime NOT NULL,
	CAMP_INITIAL_DELIVERY_DATE datetime NOT NULL,
	CAMP_END_DELIVERY_DATE datetime NULL,
	CAMP_USER_DELIVER_AMOUNT int NOT NULL,
	CAMP_USER_MAX_USES int NOT NULL,
	CAMP_PARKING_NUMBER numeric(18, 0) NULL,
	CAMP_NUMBER_BONIFYED_PARKING nvarchar(1024) NULL,
	CAMP_DISCOUNT numeric(18, 5) NULL,
	CAMP_LAYOUT_ID numeric(18, 0) NULL,
	CAMP_TOTAL_DISCOUNT_DELIVERED numeric(18, 0) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CAMPAING SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_CAMPAING ADD CONSTRAINT
	DF_CAMPAING_CAMP_STATUS DEFAULT ((1)) FOR CAMP_STATUS
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAING ON
GO
IF EXISTS(SELECT * FROM dbo.CAMPAING)
	 EXEC('INSERT INTO dbo.Tmp_CAMPAING (CAMP_ID, CAMP_DESCRIPTION, CAMP_SCHEMA, CAMP_STATUS, CAMP_COU_ID, CAMP_MAX_DELIVER_AMOUNT, CAMP_INSERTION_UTC_DATE, CAMP_INITIAL_DELIVERY_DATE, CAMP_END_DELIVERY_DATE, CAMP_USER_DELIVER_AMOUNT, CAMP_USER_MAX_USES, CAMP_PARKING_NUMBER, CAMP_NUMBER_BONIFYED_PARKING, CAMP_DISCOUNT, CAMP_LAYOUT_ID, CAMP_TOTAL_DISCOUNT_DELIVERED)
		SELECT CAMP_ID, CAMP_DESCRIPTION, CAMP_SCHEMA, CAMP_STATUS, CAMP_COU_ID, CAMP_MAX_DELIVER_AMOUNT, CONVERT(datetime, CAMP_INSERTION_UTC_DATE), CONVERT(datetime, CAMP_INITIAL_DELIVERY_DATE), CONVERT(datetime, CAMP_END_DELIVERY_DATE), CAMP_USER_DELIVER_AMOUNT, CAMP_USER_MAX_USES, CAMP_PARKING_NUMBER, CAMP_NUMBER_BONIFYED_PARKING, CAMP_DISCOUNT, CAMP_LAYOUT_ID, CAMP_TOTAL_DISCOUNT_DELIVERED FROM dbo.CAMPAING WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAING OFF
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CAMPAING
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION
	DROP CONSTRAINT FK_CAMPAING_USER_ASSIGNATION_CAMPAING
GO
ALTER TABLE dbo.CAMPAINGS_GROUPS
	DROP CONSTRAINT FK_CAMPAINGS_GROUPS_CAMPAING
GO
ALTER TABLE dbo.CAMPAING_OPERATIONS
	DROP CONSTRAINT FK_CAMPAING_OPERATIONS_CAMPAING
GO
ALTER TABLE dbo.OPERATIONS
	DROP CONSTRAINT FK_OPERATIONS_CAMPAING
GO
DROP TABLE dbo.CAMPAING
GO
EXECUTE sp_rename N'dbo.Tmp_CAMPAING', N'CAMPAING', 'OBJECT' 
GO
ALTER TABLE dbo.CAMPAING ADD CONSTRAINT
	PK_CAMPAING PRIMARY KEY CLUSTERED 
	(
	CAMP_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAING ADD CONSTRAINT
	FK_CAMPAING_COUNTRIES FOREIGN KEY
	(
	CAMP_COU_ID
	) REFERENCES dbo.COUNTRIES
	(
	COU_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS ADD CONSTRAINT
	FK_OPERATIONS_CAMPAING FOREIGN KEY
	(
	OPE_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING_OPERATIONS ADD CONSTRAINT
	FK_CAMPAING_OPERATIONS_CAMPAING FOREIGN KEY
	(
	CAMP_OPE_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAINGS_GROUPS ADD CONSTRAINT
	FK_CAMPAINGS_GROUPS_CAMPAING FOREIGN KEY
	(
	CAMP_GRP_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAINGS_GROUPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION
	DROP CONSTRAINT DF_CAMPAING_USER_ASSIGNATION_CAUS_STATUS
GO
CREATE TABLE dbo.Tmp_CAMPAING_USER_ASSIGNATION
	(
	CAUS_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CAUS_CAMP_ID numeric(18, 0) NOT NULL,
	CAUS_USR_ID numeric(18, 0) NOT NULL,
	CAUS_CURRENT_NUMBER_ID_USES numeric(18, 0) NOT NULL,
	CAUS_STATUS int NOT NULL,
	CAUS_INSERTION_UTC_DATE datetime NOT NULL,
	CAUS_STATUS_UTC_DATE datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CAMPAING_USER_ASSIGNATION SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_CAMPAING_USER_ASSIGNATION ADD CONSTRAINT
	DF_CAMPAING_USER_ASSIGNATION_CAUS_STATUS DEFAULT ((1)) FOR CAUS_STATUS
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAING_USER_ASSIGNATION ON
GO
IF EXISTS(SELECT * FROM dbo.CAMPAING_USER_ASSIGNATION)
	 EXEC('INSERT INTO dbo.Tmp_CAMPAING_USER_ASSIGNATION (CAUS_ID, CAUS_CAMP_ID, CAUS_USR_ID, CAUS_CURRENT_NUMBER_ID_USES, CAUS_STATUS, CAUS_INSERTION_UTC_DATE, CAUS_STATUS_UTC_DATE)
		SELECT CAUS_ID, CAUS_CAMP_ID, CAUS_USR_ID, CAUS_CURRENT_NUMBER_ID_USES, CAUS_STATUS, CONVERT(datetime, CAUS_INSERTION_UTC_DATE), CONVERT(datetime, CAUS_STATUS_UTC_DATE) FROM dbo.CAMPAING_USER_ASSIGNATION WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAING_USER_ASSIGNATION OFF
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION1
GO
DROP TABLE dbo.CAMPAING_USER_ASSIGNATION
GO
EXECUTE sp_rename N'dbo.Tmp_CAMPAING_USER_ASSIGNATION', N'CAMPAING_USER_ASSIGNATION', 'OBJECT' 
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION ADD CONSTRAINT
	PK_CAMPAING_USER_ASSIGNATION PRIMARY KEY CLUSTERED 
	(
	CAUS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION ADD CONSTRAINT
	FK_CAMPAING_USER_ASSIGNATION_USERS FOREIGN KEY
	(
	CAUS_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_USER_ASSIGNATION ADD CONSTRAINT
	FK_CAMPAING_USER_ASSIGNATION_CAMPAING FOREIGN KEY
	(
	CAUS_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_CAMPAIGN_USER_USE
	(
	CAUSS_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CAUSS_CAUS_ID numeric(18, 0) NULL,
	CAUSS_DATE datetime NOT NULL,
	CAUSS_UTC_DATE datetime NOT NULL,
	CAUSS_OPE_ID numeric(18, 0) NULL,
	CAUSS_TIPA_ID numeric(18, 0) NULL,
	CAUSS_CUSPMR_ID numeric(18, 0) NULL,
	CAUSS_USRF_ACCEPT_USR_ID numeric(18, 0) NULL,
	CAUSS_CELL_IMEI varchar(100) NULL,
	CAUSS_CAMP_ID numeric(18, 0) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CAMPAIGN_USER_USE SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAIGN_USER_USE ON
GO
IF EXISTS(SELECT * FROM dbo.CAMPAIGN_USER_USE)
	 EXEC('INSERT INTO dbo.Tmp_CAMPAIGN_USER_USE (CAUSS_ID, CAUSS_CAUS_ID, CAUSS_DATE, CAUSS_UTC_DATE, CAUSS_OPE_ID, CAUSS_TIPA_ID, CAUSS_CUSPMR_ID, CAUSS_USRF_ACCEPT_USR_ID, CAUSS_CELL_IMEI, CAUSS_CAMP_ID)
		SELECT CAUSS_ID, CAUSS_CAUS_ID, CONVERT(datetime, CAUSS_DATE), CONVERT(datetime, CAUSS_UTC_DATE), CAUSS_OPE_ID, CAUSS_TIPA_ID, CAUSS_CUSPMR_ID, CAUSS_USRF_ACCEPT_USR_ID, CAUSS_CELL_IMEI, CAUSS_CAMP_ID FROM dbo.CAMPAIGN_USER_USE WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CAMPAIGN_USER_USE OFF
GO
DROP TABLE dbo.CAMPAIGN_USER_USE
GO
EXECUTE sp_rename N'dbo.Tmp_CAMPAIGN_USER_USE', N'CAMPAIGN_USER_USE', 'OBJECT' 
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	PK_CAMPAIGN_USER_USE PRIMARY KEY CLUSTERED 
	(
	CAUSS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES FOREIGN KEY
	(
	CAUSS_CUSPMR_ID
	) REFERENCES dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES
	(
	CUSPMR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_OPERATIONS FOREIGN KEY
	(
	CAUSS_OPE_ID
	) REFERENCES dbo.HIS_OPERATIONS
	(
	OPE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS FOREIGN KEY
	(
	CAUSS_TIPA_ID
	) REFERENCES dbo.TICKET_PAYMENTS
	(
	TIPA_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_USERS FOREIGN KEY
	(
	CAUSS_USRF_ACCEPT_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION1 FOREIGN KEY
	(
	CAUSS_CAUS_ID
	) REFERENCES dbo.CAMPAING_USER_ASSIGNATION
	(
	CAUS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CAMPAING FOREIGN KEY
	(
	CAUSS_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
