/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING
	DROP CONSTRAINT FK_CAMPAING_RECHARGE_COUPONS
GO
ALTER TABLE dbo.RECHARGE_COUPONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING ADD
	CAMP_MAX_NUM_DAILY_COUPONS int NULL,
	CAMP_MIN_NUM_DAILY_COUPONS int NULL,
	CAMP_MAX_NUM_WEEKLY_COUPONS int NULL,
	CAMP_MIN_NUM_WEEKLY_COUPONS int NULL,
	CAMP_MAX_NUM_MONTHLY_COUPONS int NULL,
	CAMP_MIN_NUM_MONTHLY_COUPONS int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Max number of coupons in a day (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MAX_NUM_DAILY_COUPONS'
GO
DECLARE @v sql_variant 
SET @v = N'Max number of coupons in a week (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MIN_NUM_DAILY_COUPONS'
GO
DECLARE @v sql_variant 
SET @v = N'Max number of coupons in a month (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MAX_NUM_WEEKLY_COUPONS'
GO
DECLARE @v sql_variant 
SET @v = N'Min number of different coupons in a day (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MIN_NUM_WEEKLY_COUPONS'
GO
DECLARE @v sql_variant 
SET @v = N'Min number of different coupons in a week (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MAX_NUM_MONTHLY_COUPONS'
GO
DECLARE @v sql_variant 
SET @v = N'Min number of different coupons in a month (null or -1 for not apply)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_MIN_NUM_MONTHLY_COUPONS'
GO
ALTER TABLE dbo.CAMPAING ADD CONSTRAINT
	FK_CAMPAING_RECHARGE_COUPONS FOREIGN KEY
	(
	CAMP_RCOUP_ID
	) REFERENCES dbo.RECHARGE_COUPONS
	(
	RCOUP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.CAMPAING_RECHARGE_COUPONS
	(
	CMRECP_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CMRECP_DESCRIPTION nvarchar(100) NULL,
	CMRECP_RCOUP_ID numeric(18, 0) NULL,
	CMRECP_ACTIVE int NULL,
	CMRECP_CAMP_ID numeric(18, 0) NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS', N'COLUMN', N'CMRECP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS', N'COLUMN', N'CMRECP_DESCRIPTION'
GO
DECLARE @v sql_variant 
SET @v = N'Coupon ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS', N'COLUMN', N'CMRECP_RCOUP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Active (yes/no)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS', N'COLUMN', N'CMRECP_ACTIVE'
GO
DECLARE @v sql_variant 
SET @v = N'Campaing id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS', N'COLUMN', N'CMRECP_CAMP_ID'
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS ADD CONSTRAINT
	PK_CAMPAING_RECHARGE_COUPONS PRIMARY KEY CLUSTERED 
	(
	CMRECP_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS ADD CONSTRAINT
	FK_CAMPAING_RECHARGE_COUPONS_RECHARGE_COUPONS FOREIGN KEY
	(
	CMRECP_RCOUP_ID
	) REFERENCES dbo.RECHARGE_COUPONS
	(
	RCOUP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS ADD CONSTRAINT
	FK_CAMPAING_RECHARGE_COUPONS_CAMPAING FOREIGN KEY
	(
	CMRECP_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.CAMPAING_RECHARGE_COUPONS_MONTHLY_USES
	(
	CARCMU_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CARCMU_DESCRIPTION_CAMPAING nvarchar(100) NULL,
	CARCMU_DESCRIPTION_COUPON nvarchar(100) NULL,
	CARCMU_CAMP_ID numeric(18, 0) NULL,
	CARCMU_CMRECP_ID numeric(18, 0) NULL,
	CARCMU_INI_DATE datetime NULL,
	CARCMU_END_DATE datetime NULL,
	CARCMU_USE_NUMBER int NULL,
	CARCMU_USE_AMOUNT int NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Campaign description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_DESCRIPTION_CAMPAING'
GO
DECLARE @v sql_variant 
SET @v = N'Campaign Coupon description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_DESCRIPTION_COUPON'
GO
DECLARE @v sql_variant 
SET @v = N'Campaing id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_CAMP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Campaing Coupon id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_CMRECP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Period ini date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_INI_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Period end date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_END_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Total Use number'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_USE_NUMBER'
GO
DECLARE @v sql_variant 
SET @v = N'Total Use Amount'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING_RECHARGE_COUPONS_MONTHLY_USES', N'COLUMN', N'CARCMU_USE_AMOUNT'
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS_MONTHLY_USES ADD CONSTRAINT
	PK_CAMPAING_RECHARGE_COUPONS_MONTHLY_USES PRIMARY KEY CLUSTERED 
	(
	CARCMU_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS_MONTHLY_USES ADD CONSTRAINT
	FK_CAMPAING_RECHARGE_COUPONS_MONTHLY_USES_CAMPAING FOREIGN KEY
	(
	CARCMU_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS_MONTHLY_USES ADD CONSTRAINT
	FK_CAMPAING_RECHARGE_COUPONS_MONTHLY_USES_CAMPAING_RECHARGE_COUPONS FOREIGN KEY
	(
	CARCMU_CMRECP_ID
	) REFERENCES dbo.CAMPAING_RECHARGE_COUPONS
	(
	CMRECP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING_RECHARGE_COUPONS_MONTHLY_USES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
