/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LITERALS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS ADD
	TAR_NOTICE_CHARGES_NOW int NULL,
	TAR_NOTICE_CHARGES_NOW_LIT_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_NOTICE_CHARGES_NOW DEFAULT 0 FOR TAR_NOTICE_CHARGES_NOW
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	FK_TARIFFS_LITERALS1 FOREIGN KEY
	(
	TAR_NOTICE_CHARGES_NOW_LIT_ID
	) REFERENCES dbo.LITERALS
	(
	LIT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


--UPDATE TARIFFS SET TAR_NOTICE_CHARGES_NOW=0