/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MONERIS_CONFIGURATION ADD
	MONCON_HOSTED_TOKENIZATION_PROFILE_ID varchar(50) NULL,
	MONCON_3DS_TRANSACTIONS int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Check Card Status: 0/1'
EXECUTE sp_updateextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_CONFIGURATION', N'COLUMN', N'MONCON_CHECK_CARD_STATUS'
GO
DECLARE @v sql_variant 
SET @v = N'Hosted Tokenization Profile ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_CONFIGURATION', N'COLUMN', N'MONCON_HOSTED_TOKENIZATION_PROFILE_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Activate Moneris 3DS/MPI  transaction process 0/1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_CONFIGURATION', N'COLUMN', N'MONCON_3DS_TRANSACTIONS'
GO
ALTER TABLE dbo.MONERIS_CONFIGURATION ADD CONSTRAINT
	DF_MONERIS_CONFIGURATION_MONCON_3DS_TRANSACTIONS DEFAULT 0 FOR MONCON_3DS_TRANSACTIONS
GO
ALTER TABLE dbo.MONERIS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.MONERIS_3DS_TRANSACTION_INFO
	(
	MON3IN_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	MON3IN_MD varchar(50) NOT NULL,
	MON3IN_UTC_DATE datetime NOT NULL,
	MON3IN_INLINE_FORM varchar(MAX) NOT NULL,
	MON3IN_MONCON_ID numeric(18, 0) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Internal Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_MD'
GO
DECLARE @v sql_variant 
SET @v = N'UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Inline Form returned by moneris'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_INLINE_FORM'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris configuration'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_MONCON_ID'
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	DF_MONERIS_3DS_TRANSACTION_INFO_MON3IN_UTC_DATE DEFAULT GetUTCDate() FOR MON3IN_UTC_DATE
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	PK_MONERIS_3DS_TRANSACTION_INFO PRIMARY KEY CLUSTERED 
	(
	MON3IN_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	FK_MONERIS_3DS_TRANSACTION_INFO_MONERIS_CONFIGURATION FOREIGN KEY
	(
	MON3IN_MONCON_ID
	) REFERENCES dbo.MONERIS_CONFIGURATION
	(
	MONCON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
