/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ADD
	CUSPMR_MONERIS_MD varchar(50) NULL,
	CUSPMR_MONERIS_CAVV varchar(50) NULL,
	CUSPMR_MONERIS_ECI varchar(20) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Moneris MPI MD'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS_RECHARGES', N'COLUMN', N'CUSPMR_MONERIS_MD'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris MPI CAVV'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS_RECHARGES', N'COLUMN', N'CUSPMR_MONERIS_CAVV'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris MPI ECI'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS_RECHARGES', N'COLUMN', N'CUSPMR_MONERIS_ECI'
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO
	DROP CONSTRAINT FK_MONERIS_3DS_TRANSACTION_INFO_MONERIS_CONFIGURATION
GO
ALTER TABLE dbo.MONERIS_CONFIGURATION ADD
	MONCON_HOSTED_TOKENIZATION_URL varchar(255) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Hosted Tokenization URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MONERIS_CONFIGURATION', N'COLUMN', N'MONCON_HOSTED_TOKENIZATION_URL'
GO
ALTER TABLE dbo.MONERIS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO
	DROP CONSTRAINT DF_MONERIS_3DS_TRANSACTION_INFO_MON3IN_UTC_DATE
GO
CREATE TABLE dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO
	(
	MON3IN_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	MON3IN_MD varchar(50) NOT NULL,
	MON3IN_EMAIL varchar(100) NOT NULL,
	MON3IN_AMOUNT int NOT NULL,
	MON3IN_CREATION_UTC_DATE datetime NOT NULL,
	MON3IN_INLINE_FORM varchar(MAX) NOT NULL,
	MON3IN_MONCON_ID numeric(18, 0) NOT NULL,
	MON3IN_RESPONSE_UTC_DATE datetime NULL,
	MON3IN_CAVV varchar(50) NULL,
	MON3IN_ECI varchar(20) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Internal Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_MD'
GO
DECLARE @v sql_variant 
SET @v = N'Email'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_EMAIL'
GO
DECLARE @v sql_variant 
SET @v = N'Amount to be charged'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Creation UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_CREATION_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Inline Form returned by moneris'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_INLINE_FORM'
GO
DECLARE @v sql_variant 
SET @v = N'Moneris configuration'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_MONCON_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Response UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_RESPONSE_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'CAVV'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_CAVV'
GO
DECLARE @v sql_variant 
SET @v = N'ECI'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_MONERIS_3DS_TRANSACTION_INFO', N'COLUMN', N'MON3IN_ECI'
GO
ALTER TABLE dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	DF_MONERIS_3DS_TRANSACTION_INFO_MON3IN_UTC_DATE DEFAULT (getutcdate()) FOR MON3IN_CREATION_UTC_DATE
GO
SET IDENTITY_INSERT dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO ON
GO
IF EXISTS(SELECT * FROM dbo.MONERIS_3DS_TRANSACTION_INFO)
	 EXEC('INSERT INTO dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO (MON3IN_ID, MON3IN_MD, MON3IN_CREATION_UTC_DATE, MON3IN_INLINE_FORM, MON3IN_MONCON_ID)
		SELECT MON3IN_ID, MON3IN_MD, MON3IN_UTC_DATE, MON3IN_INLINE_FORM, MON3IN_MONCON_ID FROM dbo.MONERIS_3DS_TRANSACTION_INFO WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO OFF
GO
DROP TABLE dbo.MONERIS_3DS_TRANSACTION_INFO
GO
EXECUTE sp_rename N'dbo.Tmp_MONERIS_3DS_TRANSACTION_INFO', N'MONERIS_3DS_TRANSACTION_INFO', 'OBJECT' 
GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	PK_MONERIS_3DS_TRANSACTION_INFO PRIMARY KEY CLUSTERED 
	(
	MON3IN_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.MONERIS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	FK_MONERIS_3DS_TRANSACTION_INFO_MONERIS_CONFIGURATION FOREIGN KEY
	(
	MON3IN_MONCON_ID
	) REFERENCES dbo.MONERIS_CONFIGURATION
	(
	MONCON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
