INSERT INTO PARAMETERS(PAR_NAME, PAR_VALUE, PAR_DESCRIPTION) SELECT 'BlinkaySuiteApp_PICWS_Url', 'http://localhost/TariffComputer.WS/PIC_WS.asmx', 'Blinkay.Suite App PIC_WS url'
GO
INSERT INTO PARAMETERS(PAR_NAME, PAR_VALUE, PAR_DESCRIPTION) SELECT 'BlinkaySuiteApp_PICWS_HashKey', 'Q=Khg!450=%({?!/3*23mQ(%', 'Blinkay.Suite App PIC_WS hash key'
GO
INSERT INTO PARAMETERS(PAR_NAME, PAR_VALUE, PAR_DESCRIPTION) SELECT 'BlinkaySuiteApp_PICWS_User', '', 'Blinkay.Suite App PIC_WS user'
GO
INSERT INTO PARAMETERS(PAR_NAME, PAR_VALUE, PAR_DESCRIPTION) SELECT 'BlinkaySuiteApp_PICWS_Pwd', '', 'Blinkay.Suite App PIC_WS pwd'
GO
INSERT INTO PARAMETERS(PAR_NAME, PAR_VALUE, PAR_DESCRIPTION) SELECT 'BlinkaySuiteApp_PICWS_Prov', 'IPARKME', 'Blinkay.Suite App PIC_WS provider'
GO
