/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.COUNTRIES_REDIRECTIONS ADD
	COURE_COUNTRY_REDIRECTION_PICWS_URL varchar(500) NULL,
	COURE_COUNTRY_REDIRECTION_PICWS_HASH_KEY varchar(50) NULL,
	COURE_COUNTRY_REDIRECTION_PICWS_HTTP_USER varchar(50) NULL,
	COURE_COUNTRY_REDIRECTION_PICWS_PASSWORD varchar(50) NULL,
	COURE_COUNTRY_REDIRECTION_PICWS_PROVIDER varchar(50) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Country ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COU_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Blinkay WS URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_WS_URL'
GO
DECLARE @v sql_variant 
SET @v = N'Blinkay WS Auth Key Seed'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_AUTH_HASH_KEY'
GO
DECLARE @v sql_variant 
SET @v = N'Blinkay WS HTTP User'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_HTTP_USER'
GO
DECLARE @v sql_variant 
SET @v = N'Blinkay WS HTTP Password'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PASSWORD'
GO
DECLARE @v sql_variant 
SET @v = N'Blinkay Webapp URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_WEBAPP_URL'
GO
DECLARE @v sql_variant 
SET @v = N'PIC WS URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PICWS_URL'
GO
DECLARE @v sql_variant 
SET @v = N'PIC WS Auth Key Seed'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PICWS_HASH_KEY'
GO
DECLARE @v sql_variant 
SET @v = N'PIC WS HTTP User'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PICWS_HTTP_USER'
GO
DECLARE @v sql_variant 
SET @v = N'PIC WS HTTP Password'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PICWS_PASSWORD'
GO
DECLARE @v sql_variant 
SET @v = N'PIC WS Provider'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'COUNTRIES_REDIRECTIONS', N'COLUMN', N'COURE_COUNTRY_REDIRECTION_PICWS_PROVIDER'
GO
ALTER TABLE dbo.COUNTRIES_REDIRECTIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
