ALTER VIEW [dbo].[VW_CUSTOMER_PAYMENT_MEANS_RECHARGES]
AS
SELECT        5 OPE_TYPE, CUSPMR_USR_ID, CUSPMR_MOSE_OS, CUSPMR_DATE, CUSPMR_UTC_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                          CUR_ISO_CODE, CUSPMR_SUSCRIPTION_TYPE, CUSPMR_BALANCE_BEFORE, 
                          CUSPMR_INSERTION_UTC_DATE, CUSPMR_OP_REFERENCE, 
                          CUSPMR_TRANSACTION_ID, CUSPMR_AUTH_CODE, CUSPMR_CARD_HASH, CUSPMR_CARD_REFERENCE, CUSPMR_CARD_SCHEME, CUSPMR_MASKED_CARD_NUMBER, CUSPMR_CARD_EXPIRATION_DATE,
                          CUSPMR_DATE_UTC_OFFSET, USR_USERNAME, CUSPMR_LATITUDE, CUSPMR_LONGITUDE, CUSPMR_ID,CUSPMR_APP_VERSION,						  
						  CUSPMR_PERC_VAT1, CUSPMR_PERC_VAT2, CUSPMR_PARTIAL_VAT1,
						  CUSPMR_PERC_FEE, CUSPMR_PERC_FEE_TOPPED, CUSPMR_PARTIAL_PERC_FEE,
						  CUSPMR_FIXED_FEE, CUSPMR_PARTIAL_FIXED_FEE,
						  ISNULL(CUSPMR_TOTAL_AMOUNT_CHARGED, CUSPMR_AMOUNT) CUSPMR_TOTAL_AMOUNT,
						  USR_MAIN_TEL,
						  CUSPMR_TYPE, CUSPMR_PAGATELIA_NEW_BALANCE,
						  CUSPMR_CREATION_TYPE,
						  CUSPMR_PAYPAL_INTENT, CUSPMR_PAYPAL_TRANSACTION_FEE_VALUE, CUSPMR_PAYPAL_TRANSACTION_FEE_CURRENCY_ISOCODE, CUSPMR_PAYPAL_TRANSACTION_URL, CUSPMR_PAYPAL_TRANSACTION_REFUND_URL,
						  CUSPMR_INS_ID, INS_DESCRIPTION, INS_SHORTDESC,
						  CUSPMR_FDO_ID, CUSPMR_BACKOFFICE_USR,						  
						  CUSPMR_SRC_CUR_ID, CUSPMR_SRC_AMOUNT, CUSPMR_SRC_CHANGE_APPLIED, CUSPMR_SRC_CHANGE_FEE_APPLIED,
						  CUSPMR_CASHPAY_EXPIRATION_DATE, CUSPMR_CASHPAY_BARCODE, CUSPMR_CASHPAY_REFERENCE, CUSPMR_CASHPAY_PAYU_URL,
						  CUSPMR_BALANCE_BONIFICATION_AMOUNT
FROM            dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES INNER JOIN
                         dbo.USERS ON CUSPMR_USR_ID = USR_ID
						 LEFT JOIN INSTALLATIONS ON CUSPMR_INS_ID = INS_ID
						 , dbo.CURRENCIES
WHERE        CUSPMR_CUR_ID = CUR_ID AND (CUSPMR_SUSCRIPTION_TYPE = 1 OR
                         CUSPMR_SUSCRIPTION_TYPE IS NULL) AND (CUSPMR_TRANS_STATUS IN (1, 2, 3, 4, 7) OR CUSPMR_RCOUP_ID IS NOT NULL OR CUSPMR_TYPE IN (3,4, 6))
GO