/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_CUSTOMER_INVOICES
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_CUSTOMER_INVOICES1
GO
ALTER TABLE dbo.CUSTOMER_INVOICES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_CURRENCIES
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_CURRENCIES1
GO
ALTER TABLE dbo.CURRENCIES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.COUNTRIES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.SOURCE_APPS
	(
	SOAPP_ID numeric(18, 0) NOT NULL,
	SOAPP_DESCRIPTION varchar(100) NOT NULL,
	SOAPP_CODE varchar(100) NOT NULL,
	SOAPP_DEFAULT int NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS', N'COLUMN', N'SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'App Name'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS', N'COLUMN', N'SOAPP_DESCRIPTION'
GO
DECLARE @v sql_variant 
SET @v = N'App Code'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS', N'COLUMN', N'SOAPP_CODE'
GO
DECLARE @v sql_variant 
SET @v = N'Is Default app'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS', N'COLUMN', N'SOAPP_DEFAULT'
GO
ALTER TABLE dbo.SOURCE_APPS ADD CONSTRAINT
	DF_SOURCE_APPS_SOAPP_DEFAULT DEFAULT 0 FOR SOAPP_DEFAULT
GO
ALTER TABLE dbo.SOURCE_APPS ADD CONSTRAINT
	PK_SOURCE_APPS PRIMARY KEY CLUSTERED 
	(
	SOAPP_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO


INSERT INTO  dbo.SOURCE_APPS (SOAPP_ID, SOAPP_DESCRIPTION,SOAPP_CODE,SOAPP_DEFAULT) VALUES (1, 'BLINKAY', 'BLINKAY', 1)
GO
INSERT INTO  dbo.SOURCE_APPS (SOAPP_ID, SOAPP_DESCRIPTION,SOAPP_CODE,SOAPP_DEFAULT) VALUES (2, 'RIKIP$', 'RIKIPS', 0)
GO


COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_DISCOUNTS ADD
	OPEDIS_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'OPERATIONS_DISCOUNTS', N'COLUMN', N'OPEDIS_SOAPP_ID'
GO
ALTER TABLE dbo.OPERATIONS_DISCOUNTS ADD CONSTRAINT
	DF_OPERATIONS_DISCOUNTS_BAT_SRC_SOAPP_ID DEFAULT 1 FOR OPEDIS_SOAPP_ID
GO
ALTER TABLE dbo.OPERATIONS_DISCOUNTS ADD CONSTRAINT
	FK_OPERATIONS_DISCOUNTS_SOURCE_APPS FOREIGN KEY
	(
	OPEDIS_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS_DISCOUNTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_MOBILE_SESSIONS
GO
ALTER TABLE dbo.MOBILE_SESSIONS ADD
	MOSE_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MOBILE_SESSIONS', N'COLUMN', N'MOSE_SOAPP_ID'
GO
ALTER TABLE dbo.MOBILE_SESSIONS ADD CONSTRAINT
	DF_MOBILE_SESSIONS_CUSPMR_SOAPP_ID DEFAULT 1 FOR MOSE_SOAPP_ID
GO
ALTER TABLE dbo.MOBILE_SESSIONS ADD CONSTRAINT
	FK_MOBILE_SESSIONS_SOURCE_APPS FOREIGN KEY
	(
	MOSE_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.MOBILE_SESSIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HIS_OPERATIONS ADD
	OPE_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'HIS_OPERATIONS', N'COLUMN', N'OPE_SOAPP_ID'
GO
ALTER TABLE dbo.HIS_OPERATIONS ADD CONSTRAINT
	DF_HIS_OPERATIONS_CUSPMR_SOAPP_ID DEFAULT 1 FOR OPE_SOAPP_ID
GO
ALTER TABLE dbo.HIS_OPERATIONS ADD CONSTRAINT
	FK_HIS_OPERATIONS_SOURCE_APPS FOREIGN KEY
	(
	OPE_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS ADD
	OPE_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'OPERATIONS', N'COLUMN', N'OPE_SOAPP_ID'
GO
ALTER TABLE dbo.OPERATIONS ADD CONSTRAINT
	DF_OPERATIONS_CUSPMR_SOAPP_ID DEFAULT 1 FOR OPE_SOAPP_ID
GO
ALTER TABLE dbo.OPERATIONS ADD CONSTRAINT
	FK_OPERATIONS_SOURCE_APPS FOREIGN KEY
	(
	OPE_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_USERS
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT FK_BALANCE_TRANSFERS_USERS1
GO
ALTER TABLE dbo.USERS ADD
	USR_SIGNUP_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS', N'COLUMN', N'USR_SIGNUP_SOAPP_ID'
GO
ALTER TABLE dbo.USERS ADD CONSTRAINT
	DF_USERS_CUSPMR_SOAPP_ID DEFAULT 1 FOR USR_SIGNUP_SOAPP_ID
GO
ALTER TABLE dbo.USERS ADD CONSTRAINT
	FK_USERS_SOURCE_APPS FOREIGN KEY
	(
	USR_SIGNUP_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_MOSE_OS
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_UTC_DATE
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_DATE_UTC_OFFSET
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_AMOUNT_CUR_ID
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_BALANCE_CUR_ID
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_CHANGE_APPLIED
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_BALANCE_BEFORE
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_BALANCE_BEFORE1
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_BAT_SHOPKEEPER_OP
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_SHOPKEEPER_PROFIT
GO
ALTER TABLE dbo.BALANCE_TRANSFERS
	DROP CONSTRAINT DF_BALANCE_TRANSFERS_OPE_SHOPKEEPER_AMOUNT
GO
CREATE TABLE dbo.Tmp_BALANCE_TRANSFERS
	(
	BAT_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	BAT_SRC_USR_ID numeric(18, 0) NOT NULL,
	BAT_DST_USR_ID numeric(18, 0) NOT NULL,
	BAT_MOSE_OS int NOT NULL,
	BAT_DATE datetime NOT NULL,
	BAT_UTC_DATE datetime NOT NULL,
	BAT_DATE_UTC_OFFSET int NOT NULL,
	BAT_INSERTION_UTC_DATE datetime NULL,
	BAT_AMOUNT int NOT NULL,
	BAT_AMOUNT_CUR_ID numeric(18, 0) NOT NULL,
	BAT_DST_BALANCE_CUR_ID numeric(18, 0) NOT NULL,
	BAT_CHANGE_APPLIED numeric(18, 6) NOT NULL,
	BAT_CHANGE_FEE_APPLIED numeric(18, 6) NOT NULL,
	BAT_DST_AMOUNT int NOT NULL,
	BAT_SRC_BALANCE_BEFORE int NOT NULL,
	BAT_DST_BALANCE_BEFORE int NOT NULL,
	BAT_MOSE_ID numeric(18, 0) NULL,
	BAT_APP_VERSION varchar(20) NULL,
	BAT_SRC_CUSINV_ID numeric(18, 0) NULL,
	BAT_DST_CUSINV_ID numeric(18, 0) NULL,
	BAT_SHOPKEEPER_OP int NULL,
	BAT_SHOPKEEPER_PROFIT int NULL,
	BAT_SHOPKEEPER_COLLECTED_AMOUNT int NULL,
	BAT_SRC_SOAPP_ID numeric(18, 0) NULL,
	BAT_DST_SOAPP_ID numeric(18, 0) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Table to store the information about Balance Transfers'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', NULL, NULL
GO
DECLARE @v sql_variant 
SET @v = N'Transfer id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Source User ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SRC_USR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Destination user id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_USR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'1: Android; 2: Windows Phone; 3: iOS; 4:Blackberry; 5: Web'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_MOSE_OS'
GO
DECLARE @v sql_variant 
SET @v = N'Transfer local time date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Transfer UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Transfer utc offset'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DATE_UTC_OFFSET'
GO
DECLARE @v sql_variant 
SET @v = N'Insertion utc date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_INSERTION_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Transfer amount'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Amount Currency ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_AMOUNT_CUR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Destination Balance currency id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_BALANCE_CUR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Change applied'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_CHANGE_APPLIED'
GO
DECLARE @v sql_variant 
SET @v = N'Change fee applied'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_CHANGE_FEE_APPLIED'
GO
DECLARE @v sql_variant 
SET @v = N'Destination amount in cents'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Source balance before'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SRC_BALANCE_BEFORE'
GO
DECLARE @v sql_variant 
SET @v = N'Destination balance before'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_BALANCE_BEFORE'
GO
DECLARE @v sql_variant 
SET @v = N'Mobile session id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_MOSE_ID'
GO
DECLARE @v sql_variant 
SET @v = N'App version'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_APP_VERSION'
GO
DECLARE @v sql_variant 
SET @v = N'Assigned Invoice'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SRC_CUSINV_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Assigned Invoice'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_CUSINV_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Is Shopkeeper operation: 0: No ; 1:yes'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SHOPKEEPER_OP'
GO
DECLARE @v sql_variant 
SET @v = N'Shopkeeper Profit'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SHOPKEEPER_PROFIT'
GO
DECLARE @v sql_variant 
SET @v = N'Shopkeeper Total Amount'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SHOPKEEPER_COLLECTED_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Source Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_SRC_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Destination Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BALANCE_TRANSFERS', N'COLUMN', N'BAT_DST_SOAPP_ID'
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_MOSE_OS DEFAULT ((1)) FOR BAT_MOSE_OS
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_UTC_DATE DEFAULT (getutcdate()) FOR BAT_UTC_DATE
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_DATE_UTC_OFFSET DEFAULT ((0)) FOR BAT_DATE_UTC_OFFSET
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_AMOUNT_CUR_ID DEFAULT ((50)) FOR BAT_AMOUNT_CUR_ID
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_BALANCE_CUR_ID DEFAULT ((50)) FOR BAT_DST_BALANCE_CUR_ID
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_CHANGE_APPLIED DEFAULT ((1)) FOR BAT_CHANGE_APPLIED
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_BALANCE_BEFORE DEFAULT ((0)) FOR BAT_SRC_BALANCE_BEFORE
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_BALANCE_BEFORE1 DEFAULT ((0)) FOR BAT_DST_BALANCE_BEFORE
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_BAT_SHOPKEEPER_OP DEFAULT ((0)) FOR BAT_SHOPKEEPER_OP
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_SHOPKEEPER_PROFIT DEFAULT ((0)) FOR BAT_SHOPKEEPER_PROFIT
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_OPE_SHOPKEEPER_AMOUNT DEFAULT ((0)) FOR BAT_SHOPKEEPER_COLLECTED_AMOUNT
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_CUSPMR_SOAPP_ID DEFAULT 1 FOR BAT_SRC_SOAPP_ID
GO
ALTER TABLE dbo.Tmp_BALANCE_TRANSFERS ADD CONSTRAINT
	DF_BALANCE_TRANSFERS_BAT_SRC_SOAPP_ID1 DEFAULT 1 FOR BAT_DST_SOAPP_ID
GO
SET IDENTITY_INSERT dbo.Tmp_BALANCE_TRANSFERS ON
GO
IF EXISTS(SELECT * FROM dbo.BALANCE_TRANSFERS)
	 EXEC('INSERT INTO dbo.Tmp_BALANCE_TRANSFERS (BAT_ID, BAT_SRC_USR_ID, BAT_DST_USR_ID, BAT_MOSE_OS, BAT_DATE, BAT_UTC_DATE, BAT_DATE_UTC_OFFSET, BAT_INSERTION_UTC_DATE, BAT_AMOUNT, BAT_AMOUNT_CUR_ID, BAT_DST_BALANCE_CUR_ID, BAT_CHANGE_APPLIED, BAT_CHANGE_FEE_APPLIED, BAT_DST_AMOUNT, BAT_SRC_BALANCE_BEFORE, BAT_DST_BALANCE_BEFORE, BAT_MOSE_ID, BAT_APP_VERSION, BAT_SRC_CUSINV_ID, BAT_DST_CUSINV_ID, BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_PROFIT, BAT_SHOPKEEPER_COLLECTED_AMOUNT)
		SELECT BAT_ID, BAT_SRC_USR_ID, BAT_DST_USR_ID, BAT_MOSE_OS, BAT_DATE, BAT_UTC_DATE, BAT_DATE_UTC_OFFSET, BAT_INSERTION_UTC_DATE, BAT_AMOUNT, BAT_AMOUNT_CUR_ID, BAT_DST_BALANCE_CUR_ID, BAT_CHANGE_APPLIED, BAT_CHANGE_FEE_APPLIED, BAT_DST_AMOUNT, BAT_SRC_BALANCE_BEFORE, BAT_DST_BALANCE_BEFORE, BAT_MOSE_ID, BAT_APP_VERSION, BAT_SRC_CUSINV_ID, BAT_DST_CUSINV_ID, BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_PROFIT, BAT_SHOPKEEPER_COLLECTED_AMOUNT FROM dbo.BALANCE_TRANSFERS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_BALANCE_TRANSFERS OFF
GO
DROP TABLE dbo.BALANCE_TRANSFERS
GO
EXECUTE sp_rename N'dbo.Tmp_BALANCE_TRANSFERS', N'BALANCE_TRANSFERS', 'OBJECT' 
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	PK_BALANCE_TRANSFERS PRIMARY KEY CLUSTERED 
	(
	BAT_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_USERS FOREIGN KEY
	(
	BAT_SRC_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_USERS1 FOREIGN KEY
	(
	BAT_DST_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_CURRENCIES FOREIGN KEY
	(
	BAT_AMOUNT_CUR_ID
	) REFERENCES dbo.CURRENCIES
	(
	CUR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_CURRENCIES1 FOREIGN KEY
	(
	BAT_DST_BALANCE_CUR_ID
	) REFERENCES dbo.CURRENCIES
	(
	CUR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_CUSTOMER_INVOICES FOREIGN KEY
	(
	BAT_SRC_CUSINV_ID
	) REFERENCES dbo.CUSTOMER_INVOICES
	(
	CUSINV_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_CUSTOMER_INVOICES1 FOREIGN KEY
	(
	BAT_DST_CUSINV_ID
	) REFERENCES dbo.CUSTOMER_INVOICES
	(
	CUSINV_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_MOBILE_SESSIONS FOREIGN KEY
	(
	BAT_MOSE_ID
	) REFERENCES dbo.MOBILE_SESSIONS
	(
	MOSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_SRC_SOURCE_APPS FOREIGN KEY
	(
	BAT_SRC_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BALANCE_TRANSFERS ADD CONSTRAINT
	FK_BALANCE_TRANSFERS_DST_SOURCE_APPS FOREIGN KEY
	(
	BAT_DST_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET ADD
	OPEOFF_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'OPERATIONS_OFFSTREET', N'COLUMN', N'OPEOFF_SOAPP_ID'
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET ADD CONSTRAINT
	DF_OPERATIONS_OFFSTREET_CUSPMR_SOAPP_ID DEFAULT 1 FOR OPEOFF_SOAPP_ID
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET ADD CONSTRAINT
	FK_OPERATIONS_OFFSTREET_SOURCE_APPS FOREIGN KEY
	(
	OPEOFF_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS ADD
	TIPA_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TICKET_PAYMENTS', N'COLUMN', N'TIPA_SOAPP_ID'
GO
ALTER TABLE dbo.TICKET_PAYMENTS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_CUSPMR_SOAPP_ID DEFAULT 1 FOR TIPA_SOAPP_ID
GO
ALTER TABLE dbo.TICKET_PAYMENTS ADD CONSTRAINT
	FK_TICKET_PAYMENTS_SOURCE_APPS FOREIGN KEY
	(
	TIPA_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TICKET_PAYMENTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SERVICE_CHARGES ADD
	SECH_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SERVICE_CHARGES', N'COLUMN', N'SECH_SOAPP_ID'
GO
ALTER TABLE dbo.SERVICE_CHARGES ADD CONSTRAINT
	DF_SERVICE_CHARGES_CUSPMR_SOAPP_ID DEFAULT 1 FOR SECH_SOAPP_ID
GO
ALTER TABLE dbo.SERVICE_CHARGES ADD CONSTRAINT
	FK_SERVICE_CHARGES_SOURCE_APPS FOREIGN KEY
	(
	SECH_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SERVICE_CHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ADD
	CUSPMR_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS_RECHARGES', N'COLUMN', N'CUSPMR_SOAPP_ID'
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ADD CONSTRAINT
	DF_CUSTOMER_PAYMENT_MEANS_RECHARGES_CUSPMR_SOAPP_ID DEFAULT 1 FOR CUSPMR_SOAPP_ID
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ADD CONSTRAINT
	FK_CUSTOMER_PAYMENT_MEANS_RECHARGES_SOURCE_APPS FOREIGN KEY
	(
	CUSPMR_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TOLL_MOVEMENTS ADD
	TOLM_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TOLL_MOVEMENTS', N'COLUMN', N'TOLM_SOAPP_ID'
GO
ALTER TABLE dbo.TOLL_MOVEMENTS ADD CONSTRAINT
	DF_TOLL_MOVEMENTS_BAT_SRC_SOAPP_ID DEFAULT 1 FOR TOLM_SOAPP_ID
GO
ALTER TABLE dbo.TOLL_MOVEMENTS ADD CONSTRAINT
	FK_TOLL_MOVEMENTS_SOURCE_APPS FOREIGN KEY
	(
	TOLM_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TOLL_MOVEMENTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.SOURCE_APP_COUNTRIES
	(
	SOAPPCO_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	SOAPPCO_DESCRITPION varchar(100) NOT NULL,
	SOAPPCO_SOAPP_ID numeric(18, 0) NOT NULL,
	SOAPPCO_COU_ID numeric(18, 0) NOT NULL,
	SOAPPCO_ENABLED int NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APP_COUNTRIES', N'COLUMN', N'SOAPPCO_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APP_COUNTRIES', N'COLUMN', N'SOAPPCO_DESCRITPION'
GO
DECLARE @v sql_variant 
SET @v = N'Source App ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APP_COUNTRIES', N'COLUMN', N'SOAPPCO_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Country ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APP_COUNTRIES', N'COLUMN', N'SOAPPCO_COU_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Enabled?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APP_COUNTRIES', N'COLUMN', N'SOAPPCO_ENABLED'
GO
ALTER TABLE dbo.SOURCE_APP_COUNTRIES ADD CONSTRAINT
	PK_SOURCE_APP_COUNTRIES PRIMARY KEY CLUSTERED 
	(
	SOAPPCO_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SOURCE_APP_COUNTRIES ADD CONSTRAINT
	FK_SOURCE_APP_COUNTRIES_SOURCE_APPS FOREIGN KEY
	(
	SOAPPCO_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SOURCE_APP_COUNTRIES ADD CONSTRAINT
	FK_SOURCE_APP_COUNTRIES_COUNTRIES FOREIGN KEY
	(
	SOAPPCO_COU_ID
	) REFERENCES dbo.COUNTRIES
	(
	COU_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SOURCE_APP_COUNTRIES SET (LOCK_ESCALATION = TABLE)
GO

INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('SPAIN BLINKAY', 1, 198, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('CANADA BLINKAY', 1, 39, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('ARUBA BLINKAY', 1, 12, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('COSTA RICA BLINKAY', 1, 51, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('MEXICO BLINKAY', 1, 135, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('IRELAND BLINKAY', 1, 99, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('PANAMA BLINKAY', 1, 162, 1)
GO
INSERT INTO dbo.SOURCE_APP_COUNTRIES (SOAPPCO_DESCRITPION, SOAPPCO_SOAPP_ID, SOAPPCO_COU_ID, SOAPPCO_ENABLED) VALUES ('CANADA RIKIP$', 2, 39, 1)
GO


COMMIT
