/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USER_APPROVAL_QUESTIONS ADD
	UAQ_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USER_APPROVAL_QUESTIONS', N'COLUMN', N'UAQ_SOAPP_ID'
GO
ALTER TABLE dbo.USER_APPROVAL_QUESTIONS ADD CONSTRAINT
	DF_USER_APPROVAL_QUESTIONS_USR_SIGNUP_SOAPP_ID DEFAULT ((1)) FOR UAQ_SOAPP_ID
GO
ALTER TABLE dbo.USER_APPROVAL_QUESTIONS ADD CONSTRAINT
	FK_USER_APPROVAL_QUESTIONS_SOURCE_APPS FOREIGN KEY
	(
	UAQ_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USER_APPROVAL_QUESTIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS_PUSH_ID ADD
	UPID_CREATION_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Last Source App Identifier'
EXECUTE sp_updateextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS_PUSH_ID', N'COLUMN', N'UPID_LAST_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Creation Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS_PUSH_ID', N'COLUMN', N'UPID_CREATION_SOAPP_ID'
GO
ALTER TABLE dbo.USERS_PUSH_ID ADD CONSTRAINT
	DF_USERS_PUSH_ID_UPID_LAST_SOAPP_ID1 DEFAULT ((1)) FOR UPID_CREATION_SOAPP_ID
GO
ALTER TABLE dbo.USERS_PUSH_ID ADD CONSTRAINT
	FK_USERS_PUSH_ID_CREATION_SOURCE_APPS FOREIGN KEY
	(
	UPID_CREATION_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_PUSH_ID SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS ADD
	USR_LAST_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Signup Source App Identifier'
EXECUTE sp_updateextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS', N'COLUMN', N'USR_SIGNUP_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Last Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS', N'COLUMN', N'USR_LAST_SOAPP_ID'
GO
ALTER TABLE dbo.USERS ADD CONSTRAINT
	DF_USERS_USR_SIGNUP_SOAPP_ID1 DEFAULT ((1)) FOR USR_LAST_SOAPP_ID
GO
ALTER TABLE dbo.USERS ADD CONSTRAINT
	FK_USERS_LAST_SOURCE_APPS FOREIGN KEY
	(
	USR_LAST_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD
	CUSPM_LAST_SOAPP_ID numeric(18, 0) NULL,
	CUSPM_CREATION_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Last Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_LAST_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Creation Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_CREATION_SOAPP_ID'
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD CONSTRAINT
	DF_CUSTOMER_PAYMENT_MEANS_UPID_LAST_SOAPP_ID DEFAULT ((1)) FOR CUSPM_LAST_SOAPP_ID
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD CONSTRAINT
	DF_CUSTOMER_PAYMENT_MEANS_UPID_CREATION_SOAPP_ID DEFAULT ((1)) FOR CUSPM_CREATION_SOAPP_ID
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD CONSTRAINT
	FK_CUSTOMER_PAYMENT_MEANS_LAST_SOURCE_APPS FOREIGN KEY
	(
	CUSPM_LAST_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD CONSTRAINT
	FK_CUSTOMER_PAYMENT_MEANS_CREATION_SOURCE_APPS FOREIGN KEY
	(
	CUSPM_CREATION_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS SET (LOCK_ESCALATION = TABLE)
GO


UPDATE USER_APPROVAL_QUESTIONS SET UAQ_SOAPP_ID=1
GO

UPDATE USERS_PUSH_ID SET UPID_CREATION_SOAPP_ID=1
GO

UPDATE USERS SET USR_LAST_SOAPP_ID=1
GO

UPDATE CUSTOMER_PAYMENT_MEANS SET CUSPM_LAST_SOAPP_ID=1
GO

UPDATE CUSTOMER_PAYMENT_MEANS SET CUSPM_CREATION_SOAPP_ID=1
GO

COMMIT