/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING ADD
	CAMP_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAING', N'COLUMN', N'CAMP_SOAPP_ID'
GO
ALTER TABLE dbo.CAMPAING ADD CONSTRAINT
	DF_CAMPAING_CASCV_SOAPP_ID DEFAULT ((1)) FOR CAMP_SOAPP_ID
GO
ALTER TABLE dbo.CAMPAING ADD CONSTRAINT
	FK_CAMPAING_SOURCE_APPS FOREIGN KEY
	(
	CAMP_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAING SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CARROUSEL_SCREEN_VERSIONS ADD
	CASCV_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CARROUSEL_SCREEN_VERSIONS', N'COLUMN', N'CASCV_SOAPP_ID'
GO
ALTER TABLE dbo.CARROUSEL_SCREEN_VERSIONS ADD CONSTRAINT
	DF_CARROUSEL_SCREEN_VERSIONS_TIPA_SOAPP_ID DEFAULT ((1)) FOR CASCV_SOAPP_ID
GO
ALTER TABLE dbo.CARROUSEL_SCREEN_VERSIONS ADD CONSTRAINT
	FK_CARROUSEL_SCREEN_VERSIONS_SOURCE_APPS FOREIGN KEY
	(
	CASCV_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CARROUSEL_SCREEN_VERSIONS SET (LOCK_ESCALATION = TABLE)
GO

update CAMPAING set camp_soapp_id=1
go

UPDATE CARROUSEL_SCREEN_VERSIONS SET CASCV_SOAPP_ID=1
GO

COMMIT
