/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.SOURCE_APPS_CONFIGURATION
	(
	SOAPC_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	SOAPC_SOAPP_ID numeric(18, 0) NOT NULL,
	SOAPC_SENDER_WS_URL varchar(512) NOT NULL,
	SOAPC_SENDER_WS_USERNAME varchar(100) NOT NULL,
	SOAPC_SENDER_WS_PASSWORD varchar(100) NOT NULL,
	SOAPC_SENDER_DBNAME varchar(100) NOT NULL,
	SOAPC_SENDER_SEND_SMS int NOT NULL,
	SOAPC_PUSH_GCM_AUTH_TOKEN varchar(512) NOT NULL,
	SOAPC_PUSH_GCM_SENDER_ID varchar(100) NOT NULL,
	SOAPC_PUSH_GCM_OVERRIDE_URL varchar(512) NOT NULL,
	SOAPC_PUSH_FIREBASE_AUTH_TOKEN varchar(512) NOT NULL,
	SOAPC_PUSH_FIREBASE_SENDER_ID varchar(100) NOT NULL,
	SOAPC_PUSH_APNS_FILECERT varchar(100) NOT NULL,
	SOAPC_PUSH_APNS_PASSWORD varchar(100) NOT NULL,
	SOAPC_PUSH_APNS_IS_PRODUCTION_KEY int NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Source App Id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SOAPP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Sender WS url'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SENDER_WS_URL'
GO
DECLARE @v sql_variant 
SET @v = N'Sender WS Username'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SENDER_WS_USERNAME'
GO
DECLARE @v sql_variant 
SET @v = N'Sender WS Password'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SENDER_WS_PASSWORD'
GO
DECLARE @v sql_variant 
SET @v = N'Sender DB Name'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SENDER_DBNAME'
GO
DECLARE @v sql_variant 
SET @v = N'Sender Send SMS?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SENDER_SEND_SMS'
GO
DECLARE @v sql_variant 
SET @v = N'GCM Auth Token'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_GCM_AUTH_TOKEN'
GO
DECLARE @v sql_variant 
SET @v = N'GCM Sender ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_GCM_SENDER_ID'
GO
DECLARE @v sql_variant 
SET @v = N'GCM Override URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_GCM_OVERRIDE_URL'
GO
DECLARE @v sql_variant 
SET @v = N'Firebase Auth Token'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_FIREBASE_AUTH_TOKEN'
GO
DECLARE @v sql_variant 
SET @v = N'Firebase Sender ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_FIREBASE_SENDER_ID'
GO
DECLARE @v sql_variant 
SET @v = N'APNS File cert'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_FILECERT'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Password'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_PASSWORD'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Is production key'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_IS_PRODUCTION_KEY'
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_SENDER_SEND_SMS DEFAULT 0 FOR SOAPC_SENDER_SEND_SMS
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_SENDER_SEND_SMS1 DEFAULT 0 FOR SOAPC_PUSH_GCM_AUTH_TOKEN
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_GCM_AUTH_TOKEN1 DEFAULT 0 FOR SOAPC_PUSH_GCM_SENDER_ID
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_GCM_SENDER_ID1 DEFAULT 0 FOR SOAPC_PUSH_GCM_OVERRIDE_URL
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_GCM_AUTH_TOKEN1_1 DEFAULT 0 FOR SOAPC_PUSH_FIREBASE_AUTH_TOKEN
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_GCM_SENDER_ID1_1 DEFAULT 0 FOR SOAPC_PUSH_FIREBASE_SENDER_ID
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_FIREBASE_SENDER_ID1 DEFAULT 0 FOR SOAPC_PUSH_APNS_FILECERT
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_FILECERT1 DEFAULT 0 FOR SOAPC_PUSH_APNS_PASSWORD
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_PASSWORD1 DEFAULT 1 FOR SOAPC_PUSH_APNS_IS_PRODUCTION_KEY
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	PK_SOURCE_APPS_CONFIGURATION PRIMARY KEY CLUSTERED 
	(
	SOAPC_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD CONSTRAINT
	FK_SOURCE_APPS_CONFIGURATION_SOURCE_APPS FOREIGN KEY
	(
	SOAPC_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
