drop index  [IND_USER_CUS_ID] ON [dbo].[USERS]
go

ALTER TABLE dbo.users
 ALTER COLUMN usr_main_tel varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
go

 CREATE NONCLUSTERED INDEX [IND_USER_CUS_ID] ON [dbo].[USERS]
(
	[USR_CUS_ID] ASC
)
INCLUDE ( 	[USR_ID],
	[USR_INSERT_UTC_DATE],
	[USR_COU_ID],
	[USR_EMAIL],
	[USR_MAIN_TEL_COUNTRY],
	[USR_MAIN_TEL],
	[USR_SECUND_TEL_COUNTRY],
	[USR_SECUND_TEL],
	[USR_USERNAME],
	[USR_SUSCRIPTION_TYPE],
	[USR_CUSPM_ID],
	[USR_BALANCE],
	[USR_CUR_ID],
	[USR_CULTURE_LANG],
	[USR_UTC_OFFSET],
	[USR_ENABLED],
	[USR_LCT_ID],
	[USR_INSERT_MOSE_OS],
	[USR_DISABLE_UTC_DATE],
	[USR_OPERATIVE_UTC_DATE],
	[USR_PAGATELIA_LAST_USER],
	[USR_PAGATELIA_LAST_PWD]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


