/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PUSHID_NOTIFICATIONS ADD
	PNO_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'PUSHID_NOTIFICATIONS', N'COLUMN', N'PNO_SOAPP_ID'
GO
ALTER TABLE dbo.PUSHID_NOTIFICATIONS ADD CONSTRAINT
	DF_PUSHID_NOTIFICATIONS_TIPA_SOAPP_ID DEFAULT ((1)) FOR PNO_SOAPP_ID
GO
ALTER TABLE dbo.PUSHID_NOTIFICATIONS ADD CONSTRAINT
	FK_PUSHID_NOTIFICATIONS_SOURCE_APPS FOREIGN KEY
	(
	PNO_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PUSHID_NOTIFICATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS_WARNINGS ADD
	UWA_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Source App Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS_WARNINGS', N'COLUMN', N'UWA_SOAPP_ID'
GO
ALTER TABLE dbo.USERS_WARNINGS ADD CONSTRAINT
	DF_USERS_WARNINGS_PNO_SOAPP_ID DEFAULT ((1)) FOR UWA_SOAPP_ID
GO
ALTER TABLE dbo.USERS_WARNINGS ADD CONSTRAINT
	FK_USERS_WARNINGS_SOURCE_APPS FOREIGN KEY
	(
	UWA_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_WARNINGS SET (LOCK_ESCALATION = TABLE)
GO

UPDATE dbo.USERS_WARNINGS SET UWA_SOAPP_ID=1
GO

UPDATE dbo.PUSHID_NOTIFICATIONS SET PNO_SOAPP_ID=1
GO

COMMIT
