/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CARRAUSEL_SCREENS ADD
	CASCR_ANDROID_URL varchar(512) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Animation Android URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CARRAUSEL_SCREENS', N'COLUMN', N'CASCR_ANDROID_URL'
GO
ALTER TABLE dbo.CARRAUSEL_SCREENS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
