/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD
	SOAPC_IOS_APPSTORE_URL varchar(512) NULL,
	SOAPC_ANDROID_GOOGLE_PLAY_URL varchar(512) NULL,
	SOAPC_ANDROID_APPSCHEMA varchar(100) NULL,
	SOAPC_SIGNUP_URL varchar(512) NULL
GO
DECLARE @v sql_variant 
SET @v = N'APPSTORE URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_IOS_APPSTORE_URL'
GO
DECLARE @v sql_variant 
SET @v = N'GOOGLE PLAY URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_ANDROID_GOOGLE_PLAY_URL'
GO
DECLARE @v sql_variant 
SET @v = N'Android Deep Link AppSchema'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_ANDROID_APPSCHEMA'
GO
DECLARE @v sql_variant 
SET @v = N'Signup URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_SIGNUP_URL'
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
