/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO
	DROP CONSTRAINT FK_BSREDSYS_3DS_TRANSACTION_INFO_BSREDSYS_CONFIGURATION
GO
ALTER TABLE dbo.BSREDSYS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO
	DROP CONSTRAINT DF_BSREDSYS_3DS_TRANSACTION_INFO_MON3IN_CREATION_UTC_DATE
GO
ALTER TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO
	DROP CONSTRAINT DF_BSREDSYS_3DS_TRANSACTION_INFO_BSR3IN_NUM_FORMS
GO
CREATE TABLE dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO
	(
	BSR3IN_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	BSR3IN_3DS_TRANS_ID varchar(100) NOT NULL,
	BSR3IN_ORDER_ID varchar(100) NOT NULL,
	BSR3IN_EMAIL varchar(100) NOT NULL,
	BSR3IN_AMOUNT int NOT NULL,
	BSR3IN_CREATION_UTC_DATE datetime NOT NULL,
	BSR3IN_NUM_INLINE_FORMS int NOT NULL,
	BSR3IN_INLINE_FORM1 varchar(MAX) NOT NULL,
	BSR3IN_INLINE_FORM2 varchar(MAX) NULL,
	BSR3IN_BSRCON_ID numeric(18, 0) NOT NULL,
	BSR3IN_RESPONSE_UTC_DATE datetime NULL,
	BSR3IN_PROTOCOL_VERSION varchar(50) NULL,
	BSR3IN_PARES varchar(MAX) NULL,
	BSR3IN_CRES varchar(MAX) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Internal Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Redsys 3DS Transaction Identifier (MD/threeDSServerTransID)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_3DS_TRANS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Redsys Order ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_ORDER_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Email'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_EMAIL'
GO
DECLARE @v sql_variant 
SET @v = N'Amount to be charged'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_AMOUNT'
GO
DECLARE @v sql_variant 
SET @v = N'Creation UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_CREATION_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Num Inline Forms'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_NUM_INLINE_FORMS'
GO
DECLARE @v sql_variant 
SET @v = N'Inline Form 1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_INLINE_FORM1'
GO
DECLARE @v sql_variant 
SET @v = N'Inline Form 2'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_INLINE_FORM2'
GO
DECLARE @v sql_variant 
SET @v = N'BSRedsys configuration'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_BSRCON_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Response UTC Date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_RESPONSE_UTC_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'Protocol Version'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_PROTOCOL_VERSION'
GO
DECLARE @v sql_variant 
SET @v = N'PARES return parameter'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_PARES'
GO
DECLARE @v sql_variant 
SET @v = N'CRES return parameter'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'COLUMN', N'BSR3IN_CRES'
GO
ALTER TABLE dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	DF_BSREDSYS_3DS_TRANSACTION_INFO_MON3IN_CREATION_UTC_DATE DEFAULT (getutcdate()) FOR BSR3IN_CREATION_UTC_DATE
GO
ALTER TABLE dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	DF_BSREDSYS_3DS_TRANSACTION_INFO_BSR3IN_NUM_FORMS DEFAULT ((0)) FOR BSR3IN_NUM_INLINE_FORMS
GO
SET IDENTITY_INSERT dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO ON
GO
IF EXISTS(SELECT * FROM dbo.BSREDSYS_3DS_TRANSACTION_INFO)
	 EXEC('INSERT INTO dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO (BSR3IN_ID, BSR3IN_3DS_TRANS_ID, BSR3IN_ORDER_ID, BSR3IN_EMAIL, BSR3IN_AMOUNT, BSR3IN_CREATION_UTC_DATE, BSR3IN_NUM_INLINE_FORMS, BSR3IN_INLINE_FORM1, BSR3IN_INLINE_FORM2, BSR3IN_BSRCON_ID, BSR3IN_RESPONSE_UTC_DATE, BSR3IN_PROTOCOL_VERSION, BSR3IN_PARES, BSR3IN_CRES)
		SELECT BSR3IN_ID, BSR3IN_3DS_TRANS_ID, BSR3IN_ORDER_ID, BSR3IN_EMAIL, BSR3IN_AMOUNT, BSR3IN_CREATION_UTC_DATE, BSR3IN_NUM_INLINE_FORMS, BSR3IN_INLINE_FORM1, BSR3IN_INLINE_FORM2, BSR3IN_BSRCON_ID, BSR3IN_RESPONSE_UTC_DATE, BSR3IN_PROTOCOL_VERSION, BSR3IN_PARES, BSR3IN_CRES FROM dbo.BSREDSYS_3DS_TRANSACTION_INFO WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO OFF
GO
DROP TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO
GO
EXECUTE sp_rename N'dbo.Tmp_BSREDSYS_3DS_TRANSACTION_INFO', N'BSREDSYS_3DS_TRANSACTION_INFO', 'OBJECT' 
GO
ALTER TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	PK_BSREDSYS_3DS_TRANSACTION_INFO PRIMARY KEY CLUSTERED 
	(
	BSR3IN_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BSREDSYS_3DS_TRANSACTION_INFO ADD CONSTRAINT
	FK_BSREDSYS_3DS_TRANSACTION_INFO_BSREDSYS_CONFIGURATION FOREIGN KEY
	(
	BSR3IN_BSRCON_ID
	) REFERENCES dbo.BSREDSYS_CONFIGURATION
	(
	BSRCON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT