

/****** Object:  Table [dbo].[DB_OPERATIONS_HOUR]    Script Date: 22/03/2021 12:22:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB_OPERATIONS_HOUR_HIS](
	[DBOH_ID] [numeric](18, 0) NOT NULL,
	[HOUR] [datetime] NOT NULL,
	[OPE_INS_ID] [numeric](18, 0) NOT NULL,
	[GRP_ID] [numeric](18, 0) NOT NULL,
	[OPE_AMOUNT_CUR_ISO_CODE] [varchar](10) NOT NULL,
	[PARKINGS_COUNT] [int] NULL,
	[EXTENSIONS_COUNT] [int] NULL,
	[REFUNDS_COUNT] [int] NULL,
	[TICKETPAYMENTS_COUNT] [int] NULL,
	[RECHARGES_COUNT] [int] NULL,
	[RECHARGEREFUNDS_COUNT] [int] NULL,
	[COUPONS_COUNT] [int] NULL,
	[COUPONREFUNDS_COUNT] [int] NULL,
	[SERVICES_COUNT] [int] NULL,
	[PARKINGS_AMOUNT] [int] NULL,
	[PARKINGS_VAT] [int] NULL,
	[PARKINGS_PERC_FEE] [int] NULL,
	[PARKINGS_PERC_FEE_VAT] [int] NULL,
	[PARKINGS_FIXED_FEE] [int] NULL,
	[PARKINGS_FIXED_FEE_VAT] [int] NULL,
	[PARKINGS_TOTAL_AMOUNT] [int] NULL,
	[EXTENSIONS_AMOUNT] [int] NULL,
	[EXTENSIONS_VAT] [int] NULL,
	[EXTENSIONS_PERC_FEE] [int] NULL,
	[EXTENSIONS_PERC_FEE_VAT] [int] NULL,
	[EXTENSIONS_FIXED_FEE] [int] NULL,
	[EXTENSIONS_FIXED_FEE_VAT] [int] NULL,
	[EXTENSIONS_TOTAL_AMOUNT] [int] NULL,
	[REFUNDS_AMOUNT] [int] NULL,
	[REFUNDS_VAT] [int] NULL,
	[REFUNDS_PERC_FEE] [int] NULL,
	[REFUNDS_PERC_FEE_VAT] [int] NULL,
	[REFUNDS_FIXED_FEE] [int] NULL,
	[REFUNDS_FIXED_FEE_VAT] [int] NULL,
	[REFUNDS_TOTAL_AMOUNT] [int] NULL,
	[TICKETPAYMENTS_AMOUNT] [int] NULL,
	[TICKETPAYMENTS_VAT] [int] NULL,
	[TICKETPAYMENTS_PERC_FEE] [int] NULL,
	[TICKETPAYMENTS_PERC_FEE_VAT] [int] NULL,
	[TICKETPAYMENTS_FIXED_FEE] [int] NULL,
	[TICKETPAYMENTS_FIXED_FEE_VAT] [int] NULL,
	[TICKETPAYMENTS_TOTAL_AMOUNT] [int] NULL,
	[RECHARGES_AMOUNT] [int] NULL,
	[RECHARGES_VAT] [int] NULL,
	[RECHARGES_PERC_FEE] [int] NULL,
	[RECHARGES_PERC_FEE_VAT] [int] NULL,
	[RECHARGES_FIXED_FEE] [int] NULL,
	[RECHARGES_FIXED_FEE_VAT] [int] NULL,
	[RECHARGES_TOTAL_AMOUNT] [int] NULL,
	[RECHARGEREFUNDS_TOTAL_AMOUNT] [int] NULL,
	[COUPONS_AMOUNT] [int] NULL,
	[COUPONS_VAT] [int] NULL,
	[COUPONS_PERC_FEE] [int] NULL,
	[COUPONS_PERC_FEE_VAT] [int] NULL,
	[COUPONS_FIXED_FEE] [int] NULL,
	[COUPONS_FIXED_FEE_VAT] [int] NULL,
	[COUPONS_TOTAL_AMOUNT] [int] NULL,
	[COUPONREFUNDS_TOTAL_AMOUNT] [int] NULL,
	[SERVICES_AMOUNT] [int] NULL,
	[SERVICES_VAT] [int] NULL,
	[SERVICES_PERC_FEE] [int] NULL,
	[SERVICES_PERC_FEE_VAT] [int] NULL,
	[SERVICES_FIXED_FEE] [int] NULL,
	[SERVICES_FIXED_FEE_VAT] [int] NULL,
	[SERVICES_TOTAL_AMOUNT] [int] NULL,
	[PARKINGS_TIME] [int] NULL,
	[EXTENSIONS_TIME] [int] NULL,
	[REFUNDS_TIME] [int] NULL,
	[HOUR_UTC] [datetime] NULL,
	[PAGATELIA_COUNT] [int] NULL,
	[PAGATELIA_AMOUNT] [int] NULL,
	[PAGATELIA_VAT] [int] NULL,
	[PAGATELIA_PERC_FEE] [int] NULL,
	[PAGATELIA_PERC_FEE_VAT] [int] NULL,
	[PAGATELIA_FIXED_FEE] [int] NULL,
	[PAGATELIA_FIXED_FEE_VAT] [int] NULL,
	[PAGATELIA_TOTAL_AMOUNT] [int] NULL,
	[RECHARGES_REGULAR_COUNT] [int] NULL,
	[RECHARGES_AUTOMATIC_COUNT] [int] NULL,
	[RECHARGES_USERCREATION_COUNT] [int] NULL,
	[RECHARGES_CHANGEPM_COUNT] [int] NULL,
	[RECHARGES_REGULAR_AMOUNT] [int] NULL,
	[RECHARGES_REGULAR_VAT] [int] NULL,
	[RECHARGES_REGULAR_PERC_FEE] [int] NULL,
	[RECHARGES_REGULAR_PERC_FEE_VAT] [int] NULL,
	[RECHARGES_REGULAR_FIXED_FEE] [int] NULL,
	[RECHARGES_REGULAR_FIXED_FEE_VAT] [int] NULL,
	[RECHARGES_REGULAR_TOTAL_AMOUNT] [int] NULL,
	[RECHARGES_AUTOMATIC_AMOUNT] [int] NULL,
	[RECHARGES_AUTOMATIC_VAT] [int] NULL,
	[RECHARGES_AUTOMATIC_PERC_FEE] [int] NULL,
	[RECHARGES_AUTOMATIC_PERC_FEE_VAT] [int] NULL,
	[RECHARGES_AUTOMATIC_FIXED_FEE] [int] NULL,
	[RECHARGES_AUTOMATIC_FIXED_FEE_VAT] [int] NULL,
	[RECHARGES_AUTOMATIC_TOTAL_AMOUNT] [int] NULL,
	[RECHARGES_USERCREATION_AMOUNT] [int] NULL,
	[RECHARGES_USERCREATION_VAT] [int] NULL,
	[RECHARGES_USERCREATION_PERC_FEE] [int] NULL,
	[RECHARGES_USERCREATION_PERC_FEE_VAT] [int] NULL,
	[RECHARGES_USERCREATION_FIXED_FEE] [int] NULL,
	[RECHARGES_USERCREATION_FIXED_FEE_VAT] [int] NULL,
	[RECHARGES_USERCREATION_TOTAL_AMOUNT] [int] NULL,
	[RECHARGES_CHANGEPM_AMOUNT] [int] NULL,
	[RECHARGES_CHANGEPM_VAT] [int] NULL,
	[RECHARGES_CHANGEPM_PERC_FEE] [int] NULL,
	[RECHARGES_CHANGEPM_PERC_FEE_VAT] [int] NULL,
	[RECHARGES_CHANGEPM_FIXED_FEE] [int] NULL,
	[RECHARGES_CHANGEPM_FIXED_FEE_VAT] [int] NULL,
	[RECHARGES_CHANGEPM_TOTAL_AMOUNT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_COUNT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_AMOUNT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_VAT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_PERC_FEE] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_PERC_FEE_VAT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_FIXED_FEE] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_FIXED_FEE_VAT] [int] NULL,
	[TICKETPAYMENTS_NON_USERS_TOTAL_AMOUNT] [int] NULL,
 CONSTRAINT [PK_DB_OPERATIONS_HOUR_HIS] PRIMARY KEY CLUSTERED 
(
	[DBOH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Table to store Operations Data consolidated per hour for dashboard and finantial reports' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_HOUR_HIS'
GO




/****** Object:  Table [dbo].[DB_OPERATIONS_HOUR_DIST_HIS]    Script Date: 22/03/2021 12:25:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB_OPERATIONS_HOUR_DIST_HIS](
	[OHD_ID] [numeric](18, 0) NOT NULL,
	[OHD_DBOH_ID] [numeric](18, 0) NOT NULL,
	[OHD_FDO_ID] [numeric](18, 0) NOT NULL,
	[OHD_PARKINGS_AMOUNT] [int] NOT NULL,
	[OHD_PARKINGS_VAT] [int] NOT NULL,
	[OHD_PARKINGS_PERC_FEE] [int] NOT NULL,
	[OHD_PARKINGS_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_PARKINGS_FIXED_FEE] [int] NOT NULL,
	[OHD_PARKINGS_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_PARKINGS_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_EXTENSIONS_AMOUNT] [int] NOT NULL,
	[OHD_EXTENSIONS_VAT] [int] NOT NULL,
	[OHD_EXTENSIONS_PERC_FEE] [int] NOT NULL,
	[OHD_EXTENSIONS_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_EXTENSIONS_FIXED_FEE] [int] NOT NULL,
	[OHD_EXTENSIONS_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_EXTENSIONS_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_REFUNDS_AMOUNT] [int] NOT NULL,
	[OHD_REFUNDS_VAT] [int] NOT NULL,
	[OHD_REFUNDS_PERC_FEE] [int] NOT NULL,
	[OHD_REFUNDS_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_REFUNDS_FIXED_FEE] [int] NOT NULL,
	[OHD_REFUNDS_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_REFUNDS_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_AMOUNT] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_VAT] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_PERC_FEE] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_FIXED_FEE] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_TICKETPAYMENTS_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_RECHARGES_AMOUNT] [int] NOT NULL,
	[OHD_RECHARGES_VAT] [int] NOT NULL,
	[OHD_RECHARGES_PERC_FEE] [int] NOT NULL,
	[OHD_RECHARGES_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_RECHARGES_FIXED_FEE] [int] NOT NULL,
	[OHD_RECHARGES_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_RECHARGES_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_COUPONS_AMOUNT] [int] NOT NULL,
	[OHD_COUPONS_VAT] [int] NOT NULL,
	[OHD_COUPONS_PERC_FEE] [int] NOT NULL,
	[OHD_COUPONS_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_COUPONS_FIXED_FEE] [int] NOT NULL,
	[OHD_COUPONS_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_COUPONS_TOTAL_AMOUNT] [int] NOT NULL,
	[OHD_SERVICES_AMOUNT] [int] NOT NULL,
	[OHD_SERVICES_VAT] [int] NOT NULL,
	[OHD_SERVICES_PERC_FEE] [int] NOT NULL,
	[OHD_SERVICES_PERC_FEE_VAT] [int] NOT NULL,
	[OHD_SERVICES_FIXED_FEE] [int] NOT NULL,
	[OHD_SERVICES_FIXED_FEE_VAT] [int] NOT NULL,
	[OHD_SERVICES_TOTAL_AMOUNT] [int] NOT NULL,
 CONSTRAINT [PK_DB_OPERATIONS_HOUR_DIST_HIS] PRIMARY KEY CLUSTERED 
(
	[OHD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DB_OPERATIONS_HOUR_DIST_HIS]  WITH CHECK ADD  CONSTRAINT [FK_DB_OPERATIONS_HOUR_DIST_HIS_DB_OPERATIONS_HOUR] FOREIGN KEY([OHD_DBOH_ID])
REFERENCES [dbo].[DB_OPERATIONS_HOUR_HIS] ([DBOH_ID])
GO

ALTER TABLE [dbo].[DB_OPERATIONS_HOUR_DIST_HIS] CHECK CONSTRAINT [FK_DB_OPERATIONS_HOUR_DIST_HIS_DB_OPERATIONS_HOUR]
GO

ALTER TABLE [dbo].[DB_OPERATIONS_HOUR_DIST_HIS]  WITH CHECK ADD  CONSTRAINT [FK_DB_OPERATIONS_HOUR_DIST_HIS_FINAN_DIST_OPERATORS] FOREIGN KEY([OHD_FDO_ID])
REFERENCES [dbo].[FINAN_DIST_OPERATORS] ([FDO_ID])
GO

ALTER TABLE [dbo].[DB_OPERATIONS_HOUR_DIST_HIS] CHECK CONSTRAINT [FK_DB_OPERATIONS_HOUR_DIST_HIS_FINAN_DIST_OPERATORS]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Table to store Operations Data consolidated per hour distributed for finantial operator for finantial reports' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_HOUR_DIST_HIS'
GO



/****** Object:  Table [dbo].[DB_OPERATIONS_MINUTE_HIS]    Script Date: 22/03/2021 12:30:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB_OPERATIONS_MINUTE_HIS](
	[MINUTE] [datetime] NOT NULL,
	[OPE_INS_ID] [numeric](18, 0) NOT NULL,
	[GRP_ID] [numeric](18, 0) NOT NULL,
	[OPE_AMOUNT_CUR_ISO_CODE] [varchar](10) NOT NULL,
	[PARKINGS_COUNT] [int] NULL,
	[EXTENSIONS_COUNT] [int] NULL,
	[REFUNDS_COUNT] [int] NULL,
	[TICKETPAYMENTS_COUNT] [int] NULL,
	[RECHARGES_COUNT] [int] NULL,
	[PARKINGS_AMOUNT] [int] NULL,
	[EXTENSIONS_AMOUNT] [int] NULL,
	[REFUNDS_AMOUNT] [int] NULL,
	[RECHARGES_AMOUNT] [int] NULL,
	[PARKINGS_TIME] [int] NULL,
	[EXTENSIONS_TIME] [int] NULL,
	[REFUNDS_TIME] [int] NULL,
	[MINUTE_UTC] [datetime] NULL,
	[TICKETPAYMENTS_NON_USERS_COUNT] [int] NULL,
 CONSTRAINT [PK_DB_OPERATIONS_MINUTE_HIS] PRIMARY KEY CLUSTERED 
(
	[MINUTE] ASC,
	[OPE_INS_ID] ASC,
	[GRP_ID] ASC,
	[OPE_AMOUNT_CUR_ISO_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Table to store Operations Data consolidated for current operations dashboard screen' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_MINUTE_HIS'
GO



/****** Object:  Table [dbo].[DB_OPERATIONS_USERS_HOUR_HIS]    Script Date: 22/03/2021 12:38:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB_OPERATIONS_USERS_HOUR_HIS](
	[HOUR] [datetime] NOT NULL,
	[OPE_INS_ID] [numeric](18, 0) NOT NULL,
	[GRP_ID] [numeric](18, 0) NOT NULL,
	[USERS_COUNT] [int] NULL,
	[USERS_ALL_COUNT] [int] NULL,
	[HOUR_UTC] [datetime] NULL,
 CONSTRAINT [PK_DB_OPERATIONS_USERS_HOUR_HIS] PRIMARY KEY CLUSTERED 
(
	[HOUR] ASC,
	[OPE_INS_ID] ASC,
	[GRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hour Identificator' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'HOUR'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Installation ID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'OPE_INS_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Group Identificator' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'GRP_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Count' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'USERS_COUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'All count' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'USERS_ALL_COUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hour UTC Identificator' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'HOUR_UTC'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Table to store Users statistics for dashboard' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_OPERATIONS_USERS_HOUR_HIS'
GO



/****** Object:  Table [dbo].[DB_RECHARGES_HOUR_HIS]    Script Date: 22/03/2021 12:39:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB_RECHARGES_HOUR_HIS](
	[HOUR] [datetime] NOT NULL,
	[OPE_USR_ID] [numeric](18, 0) NOT NULL,
	[OPE_AMOUNT_CUR_ISO_CODE] [varchar](10) NOT NULL,
	[RECHARGES_COUNT] [int] NULL,
	[PREVRECHARGES_COUNT] [int] NULL,
	[RECHARGES_AMOUNT] [int] NULL,
	[HOUR_UTC] [datetime] NULL,
	[RECHARGES_USERCREATION_COUNT] [int] NULL,
	[RECHARGES_USERCREATION_AMOUNT] [int] NULL,
 CONSTRAINT [PK_DB_RECHARGES_HOUR_HIS] PRIMARY KEY CLUSTERED 
(
	[HOUR] ASC,
	[OPE_USR_ID] ASC,
	[OPE_AMOUNT_CUR_ISO_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DB_RECHARGES_HOUR_HIS]  WITH CHECK ADD  CONSTRAINT [FK_DB_RECHARGES_HOUR_HIS_USERS] FOREIGN KEY([OPE_USR_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[DB_RECHARGES_HOUR_HIS] CHECK CONSTRAINT [FK_DB_RECHARGES_HOUR_HIS_USERS]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hour Identificator' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'HOUR'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'User ID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'OPE_USR_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Amount Currency ISO Code' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'OPE_AMOUNT_CUR_ISO_CODE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recharges count' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'RECHARGES_COUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Previous Recharges count' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'PREVRECHARGES_COUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recharges amount' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'RECHARGES_AMOUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hour UTC Identificator' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'HOUR_UTC'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recharges User Creation count' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'RECHARGES_USERCREATION_COUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recharges User Creation Amount' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS', @level2type=N'COLUMN',@level2name=N'RECHARGES_USERCREATION_AMOUNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Table sto store Recharges Data consolidated for dashboard screen' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DB_RECHARGES_HOUR_HIS'
GO


