/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION ADD
	SOAPC_PUSH_APNS_COMPANY_CERT varchar(100) NOT NULL CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_FILECERT1_1 DEFAULT 'Blinkay_Technologies.p8',
	SOAPC_PUSH_APNS_KEY_ID varchar(100) NOT NULL CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_COMPANY_CERT1 DEFAULT '4JP795TWDV',
	SOAPC_PUSH_APNS_TEAM_ID varchar(100) NOT NULL CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_KEY_ID1 DEFAULT '59F9K744TR',
	SOAPC_PUSH_APNS_BUNDLE_ID varchar(100) NOT NULL CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_KEY_ID2 DEFAULT 'com.integraparking.iParkME'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Company File cert'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_COMPANY_CERT'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Key ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_KEY_ID'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Team ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_TEAM_ID'
GO
DECLARE @v sql_variant 
SET @v = N'APNS Bundle ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'SOURCE_APPS_CONFIGURATION', N'COLUMN', N'SOAPC_PUSH_APNS_BUNDLE_ID'
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION
	DROP CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_FIREBASE_SENDER_ID1
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION
	DROP CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_FILECERT1
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION
	DROP CONSTRAINT DF_SOURCE_APPS_CONFIGURATION_SOAPC_PUSH_APNS_PASSWORD1
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION
	DROP COLUMN SOAPC_PUSH_APNS_FILECERT, SOAPC_PUSH_APNS_PASSWORD, SOAPC_PUSH_APNS_IS_PRODUCTION_KEY
GO
ALTER TABLE dbo.SOURCE_APPS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
