/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SOURCE_APPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD
	CPTGC_INTERNAL_SOAPP_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'In case of being Internal what is the Source App assigned'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG', N'COLUMN', N'CPTGC_INTERNAL_SOAPP_ID'
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
	DROP CONSTRAINT DF_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_CPTGC_IS_INTERNAL
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	DF_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_CPTGC_IS_INTERNAL DEFAULT 0 FOR CPTGC_IS_INTERNAL
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_SOURCE_APPS FOREIGN KEY
	(
	CPTGC_INTERNAL_SOAPP_ID
	) REFERENCES dbo.SOURCE_APPS
	(
	SOAPP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
