/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CAMPAING SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.CAMPAINGS_INSTALLATIONS
	(
	CAMP_INS_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	CAMP_INS_CAMP_ID numeric(18, 0) NOT NULL,
	CAMP_INS_INS_ID numeric(18, 0) NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAINGS_INSTALLATIONS', N'COLUMN', N'CAMP_INS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Campaing ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAINGS_INSTALLATIONS', N'COLUMN', N'CAMP_INS_CAMP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Installation ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CAMPAINGS_INSTALLATIONS', N'COLUMN', N'CAMP_INS_INS_ID'
GO
ALTER TABLE dbo.CAMPAINGS_INSTALLATIONS ADD CONSTRAINT
	PK_CAMPAINGS_INSTALLATIONS PRIMARY KEY CLUSTERED 
	(
	CAMP_INS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CAMPAINGS_INSTALLATIONS ADD CONSTRAINT
	FK_CAMPAINGS_INSTALLATIONS_CAMPAING FOREIGN KEY
	(
	CAMP_INS_CAMP_ID
	) REFERENCES dbo.CAMPAING
	(
	CAMP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAINGS_INSTALLATIONS ADD CONSTRAINT
	FK_CAMPAINGS_INSTALLATIONS_INSTALLATIONS FOREIGN KEY
	(
	CAMP_INS_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CAMPAINGS_INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
