/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD
	INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED int NULL,
	INS_WEB_PORTAL_ANONYMOUS_PAYMENT_PAYPAL_ENABLED int NULL,
	INS_WEB_PORTAL_ANONYMOUS_PAYMENT_GOOGLE_PAY_ENABLED int NULL,
	INS_WEB_PORTAL_ANONYMOUS_PAYMENT_APPLE_PAY_ENABLED int NULL,
	INS_GOOGLE_PAY_CPTGC_ID numeric(18, 0) NULL,
	INS_APPLE_PAY_CPTGC_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Anonymous Portal Card Payment Enabled?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'INSTALLATIONS', N'COLUMN', N'INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED'
GO
DECLARE @v sql_variant 
SET @v = N'Anonymous Portal Paypal Payment Enabled?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'INSTALLATIONS', N'COLUMN', N'INS_WEB_PORTAL_ANONYMOUS_PAYMENT_PAYPAL_ENABLED'
GO
DECLARE @v sql_variant 
SET @v = N'Anonymous Portal Google Pay Payment Enabled?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'INSTALLATIONS', N'COLUMN', N'INS_WEB_PORTAL_ANONYMOUS_PAYMENT_GOOGLE_PAY_ENABLED'
GO
DECLARE @v sql_variant 
SET @v = N'Anonymous Portal Apple Pay Payment Enabled?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'INSTALLATIONS', N'COLUMN', N'INS_WEB_PORTAL_ANONYMOUS_PAYMENT_APPLE_PAY_ENABLED'
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_WEB_PORTAL_PAYMENT_ENABLED1 DEFAULT 1 FOR INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED1 DEFAULT 0 FOR INS_WEB_PORTAL_ANONYMOUS_PAYMENT_PAYPAL_ENABLED
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED2 DEFAULT 0 FOR INS_WEB_PORTAL_ANONYMOUS_PAYMENT_GOOGLE_PAY_ENABLED
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_WEB_PORTAL_ANONYMOUS_PAYMENT_CARD_ENABLED3 DEFAULT 0 FOR INS_WEB_PORTAL_ANONYMOUS_PAYMENT_APPLE_PAY_ENABLED
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	FK_INSTALLATIONS_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_GOOGLE_PAY FOREIGN KEY
	(
	INS_GOOGLE_PAY_CPTGC_ID
	) REFERENCES dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
	(
	CPTGC_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	FK_INSTALLATIONS_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_APPLE_PAY FOREIGN KEY
	(
	INS_APPLE_PAY_CPTGC_ID
	) REFERENCES dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG
	(
	CPTGC_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS ADD
	USR_IS_ANONYMOUS int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Flag to mark user as anonymous automatically created'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'USERS', N'COLUMN', N'USR_IS_ANONYMOUS'
GO
ALTER TABLE dbo.USERS ADD CONSTRAINT
	DF_USERS_USR_IS_ANONYMOUS DEFAULT 0 FOR USR_IS_ANONYMOUS
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
