/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS ADD
	TAR_SHOPKEEPER_BEHAVIOR_TYPE int NULL	
GO
DECLARE @v sql_variant 
SET @v = N'0: Users/Shopkeepers have access ; 1: Only Users have access; 2: Only Shopkeepers have access'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TARIFFS', N'COLUMN', N'TAR_SHOPKEEPER_BEHAVIOR_TYPE'
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_SHOPKEEPER_BEHAVIOR_TYPE1 DEFAULT 0 FOR TAR_SHOPKEEPER_BEHAVIOR_TYPE
GO
COMMIT
UPDATE TARIFFS SET TAR_SHOPKEEPER_BEHAVIOR_TYPE = 0
GO
COMMIT
