
/****** Object:  View [dbo].[VW_START_STOP_OPERATIONS]    Script Date: 12/07/2021 18:21:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_START_STOP_OPERATIONS]
AS

SELECT
	 OPE_TYPE, OPE_PARKING_MODE_STATUS, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 OPE_DATE, OPE_INIDATE, OPE_ENDDATE, OPE_UTC_DATE, OPE_UTC_INIDATE, OPE_UTC_ENDDATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, OPE_ENDDATE_UTC_OFFSET,
     OPE_AMOUNT,
	 ISNULL(OPE_REAL_AMOUNT, OPE_AMOUNT) OPE_REAL_AMOUNT,
	 OPE_FINAL_AMOUNT,
	 ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPE_EXTERNAL_ID1, OPE_EXTERNAL_ID2, OPE_EXTERNAL_ID3, OPE_EXTERNAL_BASE_ID1, OPE_EXTERNAL_BASE_ID2, OPE_EXTERNAL_BASE_ID3,
	 OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

FROM OPERATIONS WITH (NOLOCK)
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES WITH (NOLOCK) ON OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON OPE_INS_ID = INS_ID
WHERE OPE_PARKING_MODE = 1 AND OPE_PARKING_MODE_STATUS = 2

UNION ALL

SELECT 
	 opStop.OPE_TYPE, opStop.OPE_PARKING_MODE_STATUS, opStop.OPE_USR_ID, opStop.OPE_MOSE_OS, opStop.OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 opStop.OPE_DATE, opStop.OPE_INIDATE, opStop.OPE_ENDDATE, opStop.OPE_UTC_DATE, opStop.OPE_UTC_INIDATE, opStop.OPE_UTC_ENDDATE, opStop.OPE_DATE_UTC_OFFSET, opStop.OPE_INIDATE_UTC_OFFSET, opStop.OPE_ENDDATE_UTC_OFFSET,
	 opStart.OPE_AMOUNT - opStop.OPE_AMOUNT OPE_AMOUNT,
	 ISNULL(opStart.OPE_REAL_AMOUNT, opStart.OPE_AMOUNT) - ISNULL(opStop.OPE_REAL_AMOUNT, opStop.OPE_AMOUNT) OPE_REAL_AMOUNT,
	 opStart.OPE_FINAL_AMOUNT - opStop.OPE_FINAL_AMOUNT OPE_FINAL_AMOUNT,
	 ISNULL(opStart.OPE_TOTAL_AMOUNT, opStart.OPE_AMOUNT) - ISNULL(opStop.OPE_TOTAL_AMOUNT, opStop.OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 opStart.OPE_TIME - opStop.OPE_TIME OPE_TIME, 
	 opStop.OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     opStop.OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     opStop.OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     opStop.OPE_SUSCRIPTION_TYPE, opStop.OPE_BALANCE_BEFORE, opStop.OPE_INSERTION_UTC_DATE, opStop.OPE_CUSPMR_ID, opStop.OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, opStop.OPE_EXTERNAL_ID1, opStop.OPE_EXTERNAL_ID2, opStop.OPE_EXTERNAL_ID3, opStop.OPE_EXTERNAL_BASE_ID1, opStop.OPE_EXTERNAL_BASE_ID2, opStop.OPE_EXTERNAL_BASE_ID3,
	 opStop.OPE_LATITUDE, opStop.OPE_LONGITUDE, opStop.OPE_ID, opStop.OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

 FROM OPERATIONS opStart WITH (NOLOCK)
		INNER JOIN OPERATIONS opStop WITH (NOLOCK) ON opStart.OPE_EXTERNAL_BASE_ID1 = opStop.OPE_EXTERNAL_BASE_ID1
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON opStop.OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON opStop.OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON opStop.OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES WITH (NOLOCK) ON opStop.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON opStop.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON opStop.OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON opStop.OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON opStop.OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON opStop.OPE_INS_ID = INS_ID
WHERE  opStart.OPE_PARKING_MODE = 1 AND opStart.OPE_PARKING_MODE_STATUS = 1 AND opStart.OPE_TYPE = 1 AND
       opStop.OPE_PARKING_MODE = 1 AND opStop.OPE_PARKING_MODE_STATUS = 1 AND opStop.OPE_TYPE = 3
       
UNION ALL

SELECT

	 OPE_TYPE, OPE_PARKING_MODE_STATUS, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 OPE_DATE, OPE_INIDATE, NULL OPE_ENDDATE, OPE_UTC_DATE, OPE_UTC_INIDATE, NULL OPE_UTC_ENDDATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, NULL OPE_ENDDATE_UTC_OFFSET,
     OPE_AMOUNT,
	 ISNULL(OPE_REAL_AMOUNT, OPE_AMOUNT) OPE_REAL_AMOUNT,
	 OPE_FINAL_AMOUNT,
	 ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPE_EXTERNAL_ID1, OPE_EXTERNAL_ID2, OPE_EXTERNAL_ID3, OPE_EXTERNAL_BASE_ID1, OPE_EXTERNAL_BASE_ID2, OPE_EXTERNAL_BASE_ID3,	 
	 OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

FROM OPERATIONS WITH (NOLOCK)
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES WITH (NOLOCK) ON OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON OPE_INS_ID = INS_ID
WHERE OPE_PARKING_MODE = 1 AND OPE_PARKING_MODE_STATUS = 0




GO


ALTER VIEW [dbo].[VW_START_STOP_HIS_OPERATIONS]
AS

SELECT
	 OPE_TYPE, OPE_PARKING_MODE_STATUS, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 OPE_DATE, OPE_INIDATE, OPE_ENDDATE, OPE_UTC_DATE, OPE_UTC_INIDATE, OPE_UTC_ENDDATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, OPE_ENDDATE_UTC_OFFSET,
     OPE_AMOUNT,
	 ISNULL(OPE_REAL_AMOUNT, OPE_AMOUNT) OPE_REAL_AMOUNT,
	 OPE_FINAL_AMOUNT,
	 ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPE_EXTERNAL_ID1, OPE_EXTERNAL_ID2, OPE_EXTERNAL_ID3, OPE_EXTERNAL_BASE_ID1, OPE_EXTERNAL_BASE_ID2, OPE_EXTERNAL_BASE_ID3,
	 OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

FROM HIS_OPERATIONS  WITH (NOLOCK) 
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON OPE_INS_ID = INS_ID
WHERE OPE_PARKING_MODE = 1 AND OPE_PARKING_MODE_STATUS = 2

UNION ALL

SELECT 
	 opStop.OPE_TYPE, opStop.OPE_PARKING_MODE_STATUS, opStop.OPE_USR_ID, opStop.OPE_MOSE_OS, opStop.OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 opStop.OPE_DATE, opStop.OPE_INIDATE, opStop.OPE_ENDDATE, opStop.OPE_UTC_DATE, opStop.OPE_UTC_INIDATE, opStop.OPE_UTC_ENDDATE, opStop.OPE_DATE_UTC_OFFSET, opStop.OPE_INIDATE_UTC_OFFSET, opStop.OPE_ENDDATE_UTC_OFFSET,
	 opStart.OPE_AMOUNT - opStop.OPE_AMOUNT OPE_AMOUNT,
	 ISNULL(opStart.OPE_REAL_AMOUNT, opStart.OPE_AMOUNT) - ISNULL(opStop.OPE_REAL_AMOUNT, opStop.OPE_AMOUNT) OPE_REAL_AMOUNT,
	 opStart.OPE_FINAL_AMOUNT - opStop.OPE_FINAL_AMOUNT OPE_FINAL_AMOUNT,
	 ISNULL(opStart.OPE_TOTAL_AMOUNT, opStart.OPE_AMOUNT) - ISNULL(opStop.OPE_TOTAL_AMOUNT, opStop.OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 opStart.OPE_TIME - opStop.OPE_TIME OPE_TIME, 
	 opStop.OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     opStop.OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     opStop.OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     opStop.OPE_SUSCRIPTION_TYPE, opStop.OPE_BALANCE_BEFORE, opStop.OPE_INSERTION_UTC_DATE, opStop.OPE_CUSPMR_ID, opStop.OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, opStop.OPE_EXTERNAL_ID1, opStop.OPE_EXTERNAL_ID2, opStop.OPE_EXTERNAL_ID3, opStop.OPE_EXTERNAL_BASE_ID1, opStop.OPE_EXTERNAL_BASE_ID2, opStop.OPE_EXTERNAL_BASE_ID3,
	 opStop.OPE_LATITUDE, opStop.OPE_LONGITUDE, opStop.OPE_ID, opStop.OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

 FROM HIS_OPERATIONS opStart  WITH (NOLOCK) 
		INNER JOIN HIS_OPERATIONS opStop WITH (NOLOCK) ON opStart.OPE_EXTERNAL_BASE_ID1 = opStop.OPE_EXTERNAL_BASE_ID1
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON opStop.OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON opStop.OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON opStop.OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON opStop.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON opStop.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON opStop.OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON opStop.OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON opStop.OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON opStop.OPE_INS_ID = INS_ID
WHERE  opStart.OPE_PARKING_MODE = 1 AND opStart.OPE_PARKING_MODE_STATUS = 1 AND opStart.OPE_TYPE = 1 AND
       opStop.OPE_PARKING_MODE = 1 AND opStop.OPE_PARKING_MODE_STATUS = 1 AND opStop.OPE_TYPE = 3
       
UNION ALL

SELECT

	 OPE_TYPE, OPE_PARKING_MODE_STATUS, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
	 OPE_DATE, OPE_INIDATE, NULL OPE_ENDDATE, OPE_UTC_DATE, OPE_UTC_INIDATE, NULL OPE_UTC_ENDDATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, NULL OPE_ENDDATE_UTC_OFFSET,
     OPE_AMOUNT,
	 ISNULL(OPE_REAL_AMOUNT, OPE_AMOUNT) OPE_REAL_AMOUNT,
	 OPE_FINAL_AMOUNT,
	 ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) OPE_TOTAL_AMOUNT,
	 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
     OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
     OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
     OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
     CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
     CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
     OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
     CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
     CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
     CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPE_EXTERNAL_ID1, OPE_EXTERNAL_ID2, OPE_EXTERNAL_ID3, OPE_EXTERNAL_BASE_ID1, OPE_EXTERNAL_BASE_ID2, OPE_EXTERNAL_BASE_ID3,
	 OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,					 
	 USR_MAIN_TEL,	 
	 INS_STANDARD_CITY_ID

FROM HIS_OPERATIONS  WITH (NOLOCK) 
		LEFT OUTER JOIN dbo.USER_PLATES WITH (NOLOCK) ON OPE_USRP_ID = USER_PLATES.USRP_ID 
		INNER JOIN CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID 
		INNER JOIN CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID 
		LEFT OUTER JOIN dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID 
		LEFT OUTER JOIN dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID 
		LEFT OUTER JOIN dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID 
		INNER JOIN dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID 
		LEFT OUTER JOIN dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID 
		LEFT OUTER JOIN dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID
		INNER JOIN INSTALLATIONS WITH (NOLOCK) ON OPE_INS_ID = INS_ID
WHERE OPE_PARKING_MODE = 1 AND OPE_PARKING_MODE_STATUS = 0






GO



/****** Object:  View [dbo].[VW_HIS_OPERATIONS]    Script Date: 12/07/2021 18:33:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_HIS_OPERATIONS]
AS
SELECT        OPE_TYPE, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, OPE_DATE, OPE_UTC_DATE, OPE_INIDATE, OPE_ENDDATE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_AMOUNT ELSE - OPE_AMOUNT END AS int) OPE_AMOUNT, 
						  CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
					  ELSE -ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
				 END AS int) OPE_REAL_AMOUNT,
						 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_FINAL_AMOUNT ELSE - OPE_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
                         OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                         CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                         OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE,  CUSPMR_OP_REFERENCE,  CUSPMR_TRANSACTION_ID,  CUSPMR_AUTH_CODE,  CUSPMR_CARD_HASH,  
                         CUSPMR_CARD_REFERENCE,  CUSPMR_CARD_SCHEME,  CUSPMR_MASKED_CARD_NUMBER,  CUSPMR_CARD_EXPIRATION_DATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, 
                         OPE_ENDDATE_UTC_OFFSET, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                         CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, HIS_OPERATIONS.OPE_EXTERNAL_ID1, HIS_OPERATIONS.OPE_EXTERNAL_ID2, HIS_OPERATIONS.OPE_EXTERNAL_ID3, 
				OPE_CONFIRMED_IN_WS1, OPE_CONFIRMED_IN_WS2, OPE_CONFIRMED_IN_WS3,
				OPE_CONFIRMATION_TIME_IN_WS1, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPE_CONFIRMATION_TIME_IN_WS2, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPE_CONFIRMATION_TIME_IN_WS3, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,				
				OPE_PERC_VAT1, OPE_PERC_VAT2, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_VAT1 ELSE -OPE_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				OPE_PERC_FEE, OPE_PERC_FEE_TOPPED, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_PERC_FEE ELSE -OPE_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				OPE_FIXED_FEE, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_FIXED_FEE ELSE -OPE_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				ISNULL(OPE_PERC_BONUS, 0) OPE_PERC_BONUS, CAST ( ISNULL(OPE_PARTIAL_BONUS_FEE, 0) AS int) OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN OPE_TYPE = 3 THEN ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) ELSE -ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				USR_MAIN_TEL,
					CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN OPE_TIME_BALANCE_USED 
					  ELSE -OPE_TIME_BALANCE_USED 
				 END AS int) OPE_TIME_BALANCE_USED, OPE_TIME_BALANCE_BEFORE, OPE_POSTPAY, OPE_SHOPKEEPER_OP, OPE_SHOPKEEPER_AMOUNT, OPE_SHOPKEEPER_PROFIT,
				 INSTALLATIONS.INS_STANDARD_CITY_ID
FROM            dbo.HIS_OPERATIONS WITH (NOLOCK) LEFT OUTER JOIN 
                         dbo.USER_PLATES WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID LEFT OUTER JOIN
                         dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID, INSTALLATIONS
WHERE        OPE_INS_ID = INS_ID







GO


ALTER VIEW [dbo].[VW_HIS_OPERATIONS_RESTRICTED]
AS
SELECT        OPE_TYPE, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, OPE_DATE, OPE_UTC_DATE, OPE_INIDATE, OPE_ENDDATE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_AMOUNT ELSE - OPE_AMOUNT END AS int) OPE_AMOUNT, 
						 CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
					  ELSE -ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
				 END AS int) OPE_REAL_AMOUNT,
						 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_FINAL_AMOUNT ELSE - OPE_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPE_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
                         OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                         CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                         OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, 
                         OPE_ENDDATE_UTC_OFFSET, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                         CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, HIS_OPERATIONS.OPE_EXTERNAL_ID1, HIS_OPERATIONS.OPE_EXTERNAL_ID2, HIS_OPERATIONS.OPE_EXTERNAL_ID3, 
				OPE_CONFIRMED_IN_WS1, OPE_CONFIRMED_IN_WS2, OPE_CONFIRMED_IN_WS3,
				OPE_CONFIRMATION_TIME_IN_WS1, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPE_CONFIRMATION_TIME_IN_WS2, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPE_CONFIRMATION_TIME_IN_WS3, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,				
				OPE_PERC_VAT1, OPE_PERC_VAT2, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_VAT1 ELSE -OPE_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				OPE_PERC_FEE, OPE_PERC_FEE_TOPPED, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_PERC_FEE ELSE -OPE_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				OPE_FIXED_FEE, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_FIXED_FEE ELSE -OPE_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				ISNULL(OPE_PERC_BONUS, 0) OPE_PERC_BONUS, CAST ( ISNULL(OPE_PARTIAL_BONUS_FEE, 0) AS int) OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN OPE_TYPE = 3 THEN ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) ELSE -ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				USR_MAIN_TEL,
					CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN OPE_TIME_BALANCE_USED 
					  ELSE -OPE_TIME_BALANCE_USED 
				 END AS int) OPE_TIME_BALANCE_USED, OPE_TIME_BALANCE_BEFORE, OPE_POSTPAY, OPE_SHOPKEEPER_OP, OPE_SHOPKEEPER_AMOUNT, OPE_SHOPKEEPER_PROFIT
FROM            dbo.HIS_OPERATIONS  WITH (NOLOCK) LEFT OUTER JOIN
                         dbo.USER_PLATES WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 WITH (NOLOCK) ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 WITH (NOLOCK) ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON dbo.HIS_OPERATIONS.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS WITH (NOLOCK) ON OPE_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS WITH (NOLOCK) ON OPE_GRP_ID = GRP_ID LEFT OUTER JOIN
                         dbo.TARIFFS WITH (NOLOCK) ON OPE_TAR_ID = TAR_ID, INSTALLATIONS  WITH (NOLOCK)
WHERE        OPE_INS_ID = INS_ID

UNION ALL

SELECT        4 OPE_TYPE, TIPA_USR_ID, TIPA_MOSE_OS, TIPA_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TIPA_DATE, TIPA_UTC_DATE, NULL, NULL, - TIPA_AMOUNT TIPA_AMOUNT, -TIPA_AMOUNT, NULL, TIPA_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - TIPA_FINAL_AMOUNT, TIPA_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, TIPA_CHANGE_APPLIED, USRP_ID, 
                         TIPA_PLATE_STRING, TIPA_TICKET_NUMBER, TIPA_TICKET_DATA,  NULL, GRP_ID, NULL, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, NULL, TIPA_SUSCRIPTION_TYPE, TIPA_BALANCE_BEFORE, TIPA_INSERTION_UTC_DATE, TIPA_CUSPMR_ID, 
                         TIPA_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, 
                         OPEDIS_AMOUNT_CUR_ID, CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         TIPA_DATE_UTC_OFFSET, NULL, NULL, CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, CUR3.CUR_NAME, CUR4.CUR_NAME, 
                         CUR5.CUR_NAME, NULL, NULL, NULL, TIPA_CONFIRMED_IN_WS,NULL,NULL,
						 TIPA_CONFIRMATION_TIME_IN_WS, TIPA_QUEUE_LENGTH_BEFORE_CONFIRM_WS, NULL,NULL,NULL,NULL,
						 TIPA_LATITUDE, TIPA_LONGITUDE, TIPA_ID,TIPA_APP_VERSION,						 
						 TIPA_PERC_VAT1, TIPA_PERC_VAT2, - TIPA_PARTIAL_VAT1,
						 TIPA_PERC_FEE, TIPA_PERC_FEE_TOPPED, - TIPA_PARTIAL_PERC_FEE,
						 TIPA_FIXED_FEE, - TIPA_PARTIAL_FIXED_FEE,
						 0, 0,
						 -ISNULL(TIPA_TOTAL_AMOUNT, TIPA_AMOUNT),
						 USR_MAIN_TEL, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY,0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT
FROM            dbo.TICKET_PAYMENTS  WITH (NOLOCK) LEFT OUTER JOIN
                         dbo.USER_PLATES WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 WITH (NOLOCK) ON TIPA_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 WITH (NOLOCK) ON TIPA_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS WITH (NOLOCK) ON TIPA_USR_ID = USR_ID LEFT OUTER JOIN
						 dbo.GROUPS WITH (NOLOCK) ON TIPA_GRP_ID = GRP_ID,
						 INSTALLATIONS  WITH (NOLOCK)
WHERE        TIPA_INS_ID = INS_ID





GO

ALTER VIEW [dbo].[VW_TICKET_PAYMENTS]
AS
SELECT        4 OPE_TYPE, TIPA_USR_ID, TIPA_MOSE_OS, TIPA_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TIPA_DATE, TIPA_UTC_DATE, - TIPA_AMOUNT TIPA_AMOUNT, TIPA_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - TIPA_FINAL_AMOUNT AS TIPA_FINAL_AMOUNT, TIPA_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE TIPA_BALANCE_CUR_ISO_CODE, TIPA_CHANGE_APPLIED, USRP_ID, 
                         TIPA_PLATE_STRING, TIPA_TICKET_NUMBER, TIPA_TICKET_DATA, GRP_ID, TIPA_SUSCRIPTION_TYPE, TIPA_BALANCE_BEFORE, TIPA_INSERTION_UTC_DATE, TIPA_CUSPMR_ID, 
                         TIPA_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, 
                         OPEDIS_AMOUNT_CUR_ID, CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         TIPA_DATE_UTC_OFFSET, CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
						 CUR1.CUR_NAME TIPA_AMOUNT_CUR_NAME, CUR2.CUR_NAME TIPA_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                         CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, 
						 TIPA_CONFIRMED_IN_WS,
						 TIPA_CONFIRMATION_TIME_IN_WS, TIPA_QUEUE_LENGTH_BEFORE_CONFIRM_WS, 
						 TIPA_LATITUDE, TIPA_LONGITUDE, TIPA_ID,TIPA_APP_VERSION,						 
						 TIPA_PERC_VAT1, TIPA_PERC_VAT2, - TIPA_PARTIAL_VAT1 TIPA_PARTIAL_VAT1,
						 TIPA_PERC_FEE, TIPA_PERC_FEE_TOPPED, - TIPA_PARTIAL_PERC_FEE TIPA_PARTIAL_PERC_FEE,
						 TIPA_FIXED_FEE, - TIPA_PARTIAL_FIXED_FEE TIPA_PARTIAL_FIXED_FEE,
						 -ISNULL(TIPA_TOTAL_AMOUNT, TIPA_AMOUNT) TIPA_TOTAL_AMOUNT,
						 USR_MAIN_TEL,
						 INSTALLATIONS.INS_STANDARD_CITY_ID
FROM            dbo.TICKET_PAYMENTS WITH (NOLOCK) LEFT OUTER JOIN
                         dbo.USER_PLATES WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 WITH (NOLOCK) ON TIPA_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 WITH (NOLOCK) ON TIPA_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS WITH (NOLOCK) ON dbo.TICKET_PAYMENTS.TIPA_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 WITH (NOLOCK) ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 WITH (NOLOCK) ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 WITH (NOLOCK) ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS WITH (NOLOCK) ON TIPA_USR_ID = USR_ID LEFT OUTER JOIN
						 dbo.GROUPS WITH (NOLOCK) ON TIPA_GRP_ID = GRP_ID,
						 INSTALLATIONS WITH (NOLOCK)
WHERE        TIPA_INS_ID = INS_ID






GO







ALTER VIEW [dbo].[VW_TICKET_PAYMENTS_NON_USER]
AS
SELECT TIPANU_ID,I.INS_DESCRIPTION,TIPANU_DATE,TIPANU_PLATE_STRING,TIPANU_TICKET_NUMBER,
CONCAT(CAST(ROUND((CAST(TIPANU_AMOUNT AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) SUBTOTAL,
CONCAT(CAST(ROUND((CAST(TIPANU_PARTIAL_VAT1 AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) VAT,
CONCAT(CAST(ROUND((CAST(TIPANU_PERC_FEE AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) FEE,
CONCAT(CAST(ROUND((CAST(TIPANU_FINAL_AMOUNT AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) FINAL_AMOUNT, I.INS_STANDARD_CITY_ID,
TIPANU_AMOUNT,
TIPANU_PARTIAL_VAT1,
TIPANU_PERC_FEE,
TIPANU_FINAL_AMOUNT,
C.CUR_ID, 
I.INS_ID,
TIPANU_GRP_ID,
TIPANU_BACKOFFICE_USR_ID,
COALESCE(TIPANU_PAYMENT_TYPE, 1) TIPANU_PAYMENT_TYPE
FROM TICKET_PAYMENTS_NON_USERS P WITH (NOLOCK)
INNER JOIN INSTALLATIONS I WITH (NOLOCK)
ON P.TIPANU_INS_ID = I.INS_ID
INNER JOIN CURRENCIES C WITH (NOLOCK)
ON P.TIPANU_AMOUNT_CUR_ID = C.CUR_ID LEFT OUTER JOIN
GROUPS WITH (NOLOCK) ON TIPANU_GRP_ID = GRP_ID


GO






ALTER VIEW [dbo].[VW_SHOPKEEPER_USERS]
AS
SELECT        dbo.USERS.USR_ID, dbo.USERS.USR_CUS_ID, dbo.USERS.USR_INSERT_UTC_DATE, dbo.USERS.USR_COU_ID, dbo.USERS.USR_EMAIL, dbo.USERS.USR_MAIN_TEL_COUNTRY, dbo.USERS.USR_MAIN_TEL, 
                         dbo.USERS.USR_SECUND_TEL_COUNTRY, dbo.USERS.USR_SECUND_TEL, dbo.USERS.USR_USERNAME, dbo.USERS.USR_SUSCRIPTION_TYPE, dbo.USERS.USR_CUSPM_ID, dbo.USERS.USR_BALANCE, 
                         dbo.USERS.USR_CUR_ID, dbo.USERS.USR_CULTURE_LANG, dbo.USERS.USR_UTC_OFFSET, dbo.USERS.USR_ENABLED, dbo.USERS.USR_LCT_ID, dbo.USERS.USR_INSERT_MOSE_OS, 
                         dbo.USERS.USR_DISABLE_UTC_DATE, dbo.USERS.USR_OPERATIVE_UTC_DATE, dbo.USERS.USR_PAGATELIA_LAST_USER, dbo.USERS.USR_PAGATELIA_LAST_PWD, dbo.USERS.USR_PAYMETH, 
                         dbo.CUSTOMERS.CUS_ID, dbo.CUSTOMERS.CUS_TYPE, dbo.CUSTOMERS.CUS_INSERT_UTC_DATE, dbo.CUSTOMERS.CUS_USR_ID, dbo.CUSTOMERS.CUS_COU_ID, dbo.CUSTOMERS.CUS_DOC_ID, 
                         dbo.CUSTOMERS.CUS_DOC_ID_TYPE, dbo.CUSTOMERS.CUS_NAME, dbo.CUSTOMERS.CUS_SURNAME1, dbo.CUSTOMERS.CUS_SURNAME2, dbo.CUSTOMERS.CUS_STREET, 
                         dbo.CUSTOMERS.CUS_STREE_NUMBER, dbo.CUSTOMERS.CUS_LEVEL_NUM, dbo.CUSTOMERS.CUS_DOOR, dbo.CUSTOMERS.CUS_LETTER, dbo.CUSTOMERS.CUS_STAIR, dbo.CUSTOMERS.CUS_CITY, 
                         dbo.CUSTOMERS.CUS_STATE, dbo.CUSTOMERS.CUS_ZIPCODE, dbo.CUSTOMERS.CUS_ENABLED, dbo.UserPlates(dbo.USERS.USR_ID) AS Plates, dbo.USERS.USR_PAYMETH AS PaymentMethod, 
                         DATEDIFF(day, ISNULL(dbo.USERS.USR_LAST_BALANCE_USE, '2000-01-01'), GETUTCDATE()) AS DaysWithoutOps, dbo.USERS.USR_SIGNUP_OS, dbo.USERS.USR_INAA_ID, 
                         dbo.USERS.USR_FIRST_OPERATION_INS_ID, dbo.USERS.USR_LAST_OPERATION_INS_ID,dbo.USERS.USR_SHOPKEEPER_STATUS
FROM            dbo.USERS WITH (NOLOCK) INNER JOIN
                         dbo.CUSTOMERS WITH (NOLOCK)  ON dbo.USERS.USR_CUS_ID = dbo.CUSTOMERS.CUS_ID
WHERE			USR_SHOPKEEPER_STATUS in (1,2)
AND (dbo.USERS.USR_FIRST_OPERATION_INS_ID NOT IN (SELECT INS_ID FROM INSTALLATIONS WITH (NOLOCK)  INNER JOIN COUNTRIES_REDIRECTIONS WITH (NOLOCK) ON INS_COU_ID = COURE_COU_ID) or dbo.USERS.USR_FIRST_OPERATION_INS_ID is null)
AND (dbo.USERS.USR_LAST_OPERATION_INS_ID NOT IN (SELECT INS_ID FROM INSTALLATIONS WITH (NOLOCK)  INNER JOIN COUNTRIES_REDIRECTIONS WITH (NOLOCK)  ON INS_COU_ID = COURE_COU_ID) or USERS.USR_LAST_OPERATION_INS_ID is null)





GO



ALTER VIEW [dbo].[VW_USERS]
AS
SELECT        dbo.USERS.USR_ID, dbo.USERS.USR_CUS_ID, dbo.USERS.USR_INSERT_UTC_DATE, dbo.USERS.USR_COU_ID, dbo.USERS.USR_EMAIL, dbo.USERS.USR_MAIN_TEL_COUNTRY, dbo.USERS.USR_MAIN_TEL, 
                         dbo.USERS.USR_SECUND_TEL_COUNTRY, dbo.USERS.USR_SECUND_TEL, dbo.USERS.USR_USERNAME, dbo.USERS.USR_SUSCRIPTION_TYPE, dbo.USERS.USR_CUSPM_ID, dbo.USERS.USR_BALANCE, 
                         dbo.USERS.USR_CUR_ID, dbo.USERS.USR_CULTURE_LANG, dbo.USERS.USR_UTC_OFFSET, dbo.USERS.USR_ENABLED, dbo.USERS.USR_LCT_ID, dbo.USERS.USR_INSERT_MOSE_OS, 
                         dbo.USERS.USR_DISABLE_UTC_DATE, dbo.USERS.USR_OPERATIVE_UTC_DATE, dbo.USERS.USR_PAGATELIA_LAST_USER, dbo.USERS.USR_PAGATELIA_LAST_PWD, dbo.USERS.USR_PAYMETH, 
                         dbo.CUSTOMERS.CUS_ID, dbo.CUSTOMERS.CUS_TYPE, dbo.CUSTOMERS.CUS_INSERT_UTC_DATE, dbo.CUSTOMERS.CUS_USR_ID, dbo.CUSTOMERS.CUS_COU_ID, dbo.CUSTOMERS.CUS_DOC_ID, 
                         dbo.CUSTOMERS.CUS_DOC_ID_TYPE, dbo.CUSTOMERS.CUS_NAME, dbo.CUSTOMERS.CUS_FIRST_NAME, dbo.CUSTOMERS.CUS_SURNAME1, dbo.CUSTOMERS.CUS_SURNAME2, dbo.CUSTOMERS.CUS_STREET, 
                         dbo.CUSTOMERS.CUS_STREE_NUMBER, dbo.CUSTOMERS.CUS_LEVEL_NUM, dbo.CUSTOMERS.CUS_DOOR, dbo.CUSTOMERS.CUS_LETTER, dbo.CUSTOMERS.CUS_STAIR, dbo.CUSTOMERS.CUS_CITY, 
                         dbo.CUSTOMERS.CUS_STATE, dbo.CUSTOMERS.CUS_ZIPCODE, dbo.CUSTOMERS.CUS_ENABLED, dbo.UserPlates(dbo.USERS.USR_ID) AS Plates, dbo.USERS.USR_PAYMETH AS PaymentMethod, 
                         DATEDIFF(day, ISNULL(dbo.USERS.USR_LAST_BALANCE_USE, '2000-01-01'), GETUTCDATE()) AS DaysWithoutOps, dbo.USERS.USR_SIGNUP_OS, dbo.USERS.USR_INAA_ID, 
                         dbo.USERS.USR_FIRST_OPERATION_INS_ID, dbo.USERS.USR_LAST_OPERATION_INS_ID,dbo.USERS.USR_SHOPKEEPER_STATUS
FROM            dbo.USERS WITH (NOLOCK) INNER JOIN
                         dbo.CUSTOMERS WITH (NOLOCK) ON dbo.USERS.USR_CUS_ID = dbo.CUSTOMERS.CUS_ID						 
						 WHERE 							
							(dbo.USERS.USR_FIRST_OPERATION_INS_ID NOT IN (SELECT INS_ID FROM INSTALLATIONS WITH (NOLOCK) INNER JOIN COUNTRIES_REDIRECTIONS WITH (NOLOCK) ON INS_COU_ID = COURE_COU_ID) or USR_FIRST_OPERATION_INS_ID is null)
							AND (dbo.USERS.USR_LAST_OPERATION_INS_ID NOT IN (SELECT INS_ID FROM INSTALLATIONS WITH (NOLOCK) INNER JOIN COUNTRIES_REDIRECTIONS WITH (NOLOCK) ON INS_COU_ID = COURE_COU_ID)  or USR_LAST_OPERATION_INS_ID is null)

GO


ALTER VIEW [dbo].[VW_CUSTOMER_INVOICES]
AS
	SELECT CUSTOMER_INVOICES.*, USR_USERNAME
	FROM CUSTOMER_INVOICES WITH (NOLOCK)
			INNER JOIN USERS WITH (NOLOCK) ON CUSINV_CUS_ID = USR_CUS_ID
	WHERE CUSINV_INV_NUMBER IS NOT NULL




GO

ALTER VIEW [dbo].[VW_CUSTOMER_PAYMENT_MEANS]
AS
SELECT        CUSPM.CUSPM_ID, USR.USR_EMAIL, CUSPM.CUSPM_PAT_ID, CUSPM.CUSPM_PAST_ID, CUSPM.CUSPM_CREDIT_CARD_PAYMENT_PROVIDER, CUSPM.CUSPM_DESCRIPTION, 
                         CUSPM.CUSPM_LAST_TIME_USERD, CUSPM.CUSPM_AUTOMATIC_RECHARGE, CUSPM.CUSPM_AMOUNT_TO_RECHARGE, CUSPM.CUSPM_RECHARGE_WHEN_AMOUNT_IS_LESS, CUSPM.CUSPM_CUR_ID, 
                         CUSPM.CUSPM_TOKEN_CARD_HASH, CUSPM.CUSPM_TOKEN_CARD_REFERENCE, CUSPM.CUSPM_TOKEN_MASKED_CARD_NUMBER, CUSPM.CUSPM_TOKEN_CARD_EXPIRATION_DATE, 
                         CUSPM.CUSPM_TOKEN_CARD_SCHEMA, CUSPM.CUSPM_TOKEN_PAYPAL_ID, CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_KEY, CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_START_DATE, 
                         CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_END_DATE, CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_MAX_NUMBER_PAYMENTS, 
                         CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_MAX_TOTAL_AMOUNT, CUSPM.CUSPM_TOKEN_PAYPAL_PREAPPROVAL_MAX_AMOUNT_PER_PAYMENT, CUSPM.CUSPM_AUTOMATIC_FAILED_RETRIES, 
                         CUSPM.CUSPM_VALID, CUSPM.CUSPM_ENABLED, CUSPM.CUSPM_CPTGC_ID, CUSPM.CUSPM_AMOUNT_TO_RECHARGE AS CUSPM_AMOUNT_TO_RECHARGE_RAW, 
                         CUSPM.CUSPM_RECHARGE_WHEN_AMOUNT_IS_LESS AS CUSPM_RECHARGE_WHEN_AMOUNT_IS_LESS_RAW,USR.USR_SUSCRIPTION_TYPE
FROM            dbo.CUSTOMER_PAYMENT_MEANS AS CUSPM WITH (NOLOCK) INNER JOIN
                         dbo.CUSTOMERS AS CUS WITH (NOLOCK) ON CUSPM.CUSPM_CUS_ID = CUS.CUS_ID INNER JOIN
                         dbo.USERS AS USR WITH (NOLOCK) ON CUS.CUS_USR_ID = USR.USR_ID
WHERE        (USR.USR_ENABLED = 1)
GO




ALTER VIEW [dbo].[VW_CUSTOMER_PAYMENT_MEANS_RECHARGES]
AS
SELECT        5 OPE_TYPE, CUSPMR_USR_ID, CUSPMR_MOSE_OS, CUSPMR_DATE, CUSPMR_UTC_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                          CUR_ISO_CODE, CUSPMR_SUSCRIPTION_TYPE, CUSPMR_BALANCE_BEFORE, 
                          CUSPMR_INSERTION_UTC_DATE, CUSPMR_OP_REFERENCE, 
                          CUSPMR_TRANSACTION_ID, CUSPMR_AUTH_CODE, CUSPMR_CARD_HASH, CUSPMR_CARD_REFERENCE, CUSPMR_CARD_SCHEME, CUSPMR_MASKED_CARD_NUMBER, CUSPMR_CARD_EXPIRATION_DATE,
                          CUSPMR_DATE_UTC_OFFSET, USR_USERNAME, CUSPMR_LATITUDE, CUSPMR_LONGITUDE, CUSPMR_ID,CUSPMR_APP_VERSION,						  
						  CUSPMR_PERC_VAT1, CUSPMR_PERC_VAT2, CUSPMR_PARTIAL_VAT1,
						  CUSPMR_PERC_FEE, CUSPMR_PERC_FEE_TOPPED, CUSPMR_PARTIAL_PERC_FEE,
						  CUSPMR_FIXED_FEE, CUSPMR_PARTIAL_FIXED_FEE,
						  ISNULL(CUSPMR_TOTAL_AMOUNT_CHARGED, CUSPMR_AMOUNT) CUSPMR_TOTAL_AMOUNT,
						  USR_MAIN_TEL,
						  CUSPMR_TYPE, CUSPMR_PAGATELIA_NEW_BALANCE,
						  CUSPMR_CREATION_TYPE,
						  CUSPMR_PAYPAL_INTENT, CUSPMR_PAYPAL_TRANSACTION_FEE_VALUE, CUSPMR_PAYPAL_TRANSACTION_FEE_CURRENCY_ISOCODE, CUSPMR_PAYPAL_TRANSACTION_URL, CUSPMR_PAYPAL_TRANSACTION_REFUND_URL,
						  CUSPMR_INS_ID, INS_DESCRIPTION, INS_SHORTDESC,
						  CUSPMR_FDO_ID, CUSPMR_BACKOFFICE_USR,						  
						  CUSPMR_SRC_CUR_ID, CUSPMR_SRC_AMOUNT, CUSPMR_SRC_CHANGE_APPLIED, CUSPMR_SRC_CHANGE_FEE_APPLIED,
						  CUSPMR_CASHPAY_EXPIRATION_DATE, CUSPMR_CASHPAY_BARCODE, CUSPMR_CASHPAY_REFERENCE, CUSPMR_CASHPAY_PAYU_URL,
						  CUSPMR_BALANCE_BONIFICATION_AMOUNT
FROM            dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS  WITH (NOLOCK) INNER JOIN
                         dbo.USERS WITH (NOLOCK) ON CUSPMR_USR_ID = USR_ID
						 LEFT JOIN INSTALLATIONS WITH (NOLOCK) ON CUSPMR_INS_ID = INS_ID
						 , dbo.CURRENCIES  WITH (NOLOCK)
WHERE        CUSPMR_CUR_ID = CUR_ID AND (CUSPMR_SUSCRIPTION_TYPE = 1 OR
                         CUSPMR_SUSCRIPTION_TYPE IS NULL) AND (CUSPMR_TRANS_STATUS IN (1, 2, 3, 4, 7) OR CUSPMR_RCOUP_ID IS NOT NULL OR CUSPMR_TYPE IN (3,4, 6))

GO


/****** Object:  View [dbo].[VW_USERS_PUSH_ID]    Script Date: 12/07/2021 18:51:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_USERS_PUSH_ID]
AS
	SELECT USERS_PUSH_ID.*, USR_USERNAME 
	FROM USERS_PUSH_ID WITH (NOLOCK)
	INNER JOIN USERS WITH (NOLOCK) ON UPID_USR_ID = USR_ID	

GO




ALTER VIEW [dbo].[VW_USERS_FRIENDS]
AS
	SELECT USERS_FRIENDS.*, U1.USR_USERNAME AS USR_USERNAME, U2.USR_USERNAME AS ACCEPT_USR_USERNAME
	FROM USERS_FRIENDS WITH (NOLOCK) INNER JOIN USERS U1 WITH (NOLOCK) ON USRF_USR_ID = U1.USR_ID	
			   LEFT JOIN USERS U2 WITH (NOLOCK) ON USRF_ACCEPT_USR_ID = U2.USR_ID









GO










/****** Object:  View [dbo].[VW_PERMIT_OPERATIONS]    Script Date: 7/12/2021 11:58:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_PERMIT_OPERATIONS] AS
		SELECT o1.*, c.CUR_ISO_CODE AS OPE_AMOUNT_CUR_ISO_CODE, c.CUR_MINOR_UNIT AS OPE_AMOUNT_CUR_MINOR_UNIT, t.TAR_DESCRIPTION, p1.USRP_PLATE, p1.USRP_ID, g.GRP_DESCRIPTION, u.USR_USERNAME, i.INS_STANDARD_CITY_ID, i.INS_DESCRIPTION,
			p2.USRP_PLATE AS USRP_PLATE2, p3.USRP_PLATE AS USRP_PLATE3, p4.USRP_PLATE AS USRP_PLATE4, p5.USRP_PLATE AS USRP_PLATE5, p6.USRP_PLATE AS USRP_PLATE6, p7.USRP_PLATE AS USRP_PLATE7, p8.USRP_PLATE AS USRP_PLATE8, p9.USRP_PLATE AS USRP_PLATE9, p10.USRP_PLATE AS USRP_PLATE10, g.GRP_PERMIT_MAX_MONTHS
	FROM   operations o1  WITH (NOLOCK) 
			LEFT JOIN user_plates p2 WITH (NOLOCK) ON p2.usrp_id = o1.ope_plate2_usrp_id
			LEFT JOIN user_plates p3 WITH (NOLOCK) ON p3.usrp_id = o1.ope_plate3_usrp_id
			LEFT JOIN user_plates p4 WITH (NOLOCK) ON p4.usrp_id = o1.ope_plate4_usrp_id
			LEFT JOIN user_plates p5 WITH (NOLOCK) ON p5.usrp_id = o1.ope_plate5_usrp_id
			LEFT JOIN user_plates p6 WITH (NOLOCK) ON p6.usrp_id = o1.ope_plate6_usrp_id
			LEFT JOIN user_plates p7 WITH (NOLOCK) ON p7.usrp_id = o1.ope_plate7_usrp_id
			LEFT JOIN user_plates p8 WITH (NOLOCK) ON p8.usrp_id = o1.ope_plate8_usrp_id
			LEFT JOIN user_plates p9 WITH (NOLOCK) ON p9.usrp_id = o1.ope_plate9_usrp_id
			LEFT JOIN user_plates p10 WITH (NOLOCK) ON p10.usrp_id = o1.ope_plate10_usrp_id, 
		   tariffs t  WITH (NOLOCK) , 
		   user_plates p1  WITH (NOLOCK) ,
		   currencies c  WITH (NOLOCK) ,
		   groups g  WITH (NOLOCK) ,
		   USERS u  WITH (NOLOCK) ,
		   INSTALLATIONS i  WITH (NOLOCK) 
	WHERE 
		   o1.ope_tar_id = t.tar_id 
		   AND t.tar_type = 1 
		   AND p1.usrp_id = o1.ope_usrp_id 
		   AND c.CUR_ID = o1.OPE_AMOUNT_CUR_ID
		   AND g.GRP_ID = o1.OPE_GRP_ID
		   AND u.USR_ID = o1.OPE_USR_ID
		   AND i.INS_ID = o1.OPE_INS_ID








GO



ALTER view [dbo].[VW_PERMIT_AUTORENEWABLE_OPERATIONS] AS
SELECT o1.* 
FROM   operations o1  WITH (NOLOCK) , 
       tariffs t  WITH (NOLOCK) , 
       user_plates p1  WITH (NOLOCK)  
WHERE  Getutcdate() BETWEEN 
               ope_utc_inidate AND ope_permit_expiration_utc_time 
               AND (SELECT Count(*) 
                    FROM   operations o2  WITH (NOLOCK) , 
                           user_plates p2  WITH (NOLOCK)  
                    WHERE  o2.ope_tar_id = o1.ope_tar_id 
						   AND o2.ope_grp_id = o1.ope_grp_id
                           AND p2.usrp_id = o2.ope_usrp_id 
                           AND p1.usrp_plate = p2.usrp_plate 
                           AND o2.ope_date > o1.ope_date) = 0 
	   AND (o1.ope_permit_last_autorenewal_status is null OR o1.ope_permit_last_autorenewal_status<4)
       AND o1.OPE_PERMIT_AUTO_RENEW=1
       AND o1.ope_tar_id = t.tar_id 
       AND t.tar_type = 1 
       AND p1.usrp_id = o1.ope_usrp_id 

GO


/****** Object:  Index [IND_DEL_USERS_PUSH_ID]    Script Date: 7/13/2021 5:44:47 AM ******/
CREATE NONCLUSTERED INDEX [IND_DEL_USERS_PUSH_ID] ON [dbo].[USERS_PUSH_ID]
(
	[UPID_LAST_UPDATE_DATETIME] ASC,
	[UPID_LAST_SUCESSFUL_PUSH] ASC,
	[UPID_PUSH_RETRIES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [IND_MOSE_UPID_ID]    Script Date: 7/13/2021 5:44:21 AM ******/
CREATE NONCLUSTERED INDEX [IND_MOSE_UPID_ID] ON [dbo].[MOBILE_SESSIONS]
(
	[MOSE_UPID_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


