ALTER TABLE [dbo].[CUSTOMER_PAYMENT_MEANS_RECHARGES] DROP CONSTRAINT [FK_CUSTOMER_PAYMENT_MEANS_RECHARGES_HIS_OPERATIONS]
GO
ALTER TABLE [dbo].[CUSTOMER_PAYMENT_MEANS_RECHARGES]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PAYMENT_MEANS_RECHARGES_OPERATIONS] FOREIGN KEY([CUSPMR_REFUND_OPE_ID])
REFERENCES [dbo].[OPERATIONS] ([OPE_ID])
GO
ALTER TABLE [dbo].[CUSTOMER_PAYMENT_MEANS_RECHARGES] CHECK CONSTRAINT [FK_CUSTOMER_PAYMENT_MEANS_RECHARGES_OPERATIONS]
GO


CREATE NONCLUSTERED INDEX [IND_CUSPMR_REFUND_OPE_ID] ON [dbo].[CUSTOMER_PAYMENT_MEANS_RECHARGES]
(
	[CUSPMR_REFUND_OPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO
