/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD
	INS_OVERRIDE_GPS_POSITION_PRECISION_MIN_METERS int NULL
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	DF_INSTALLATIONS_INS_OVERRIDE_GPS_POSITION_PRECISION_MIN_METERS DEFAULT ((0)) FOR INS_OVERRIDE_GPS_POSITION_PRECISION_MIN_METERS
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

--UPDATE INSTALLATIONS SET INS_OVERRIDE_GPS_POSITION_PRECISION_MIN_METERS=0
