/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD
	TIPANU_TOKEN_DELETED int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Token has been deleted?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TICKET_PAYMENTS_NON_USERS', N'COLUMN', N'TIPANU_TOKEN_DELETED'
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS ADD CONSTRAINT
	DF_TICKET_PAYMENTS_NON_USERS_TIPANU_TOKEN_DELETED DEFAULT 0 FOR TIPANU_TOKEN_DELETED
GO
ALTER TABLE dbo.TICKET_PAYMENTS_NON_USERS SET (LOCK_ESCALATION = TABLE)
GO
update dbo.TICKET_PAYMENTS_NON_USERS set TIPANU_TOKEN_DELETED=0
GO
COMMIT