/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TICKET_PAYMENTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.USERS_OPERATIONS_DEBTS
	(
	USROD_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	USROD_USR_ID numeric(18, 0) NOT NULL,
	USROD_DATE datetime NOT NULL,
	USROD_UTC_DATE datetime NOT NULL,
	USROD_DATE_UTC_OFFSET int NOT NULL,
	USROD_AMOUNT int NOT NULL,
	USROD_OPE_ID numeric(18, 0) NULL,
	USROD_OPEOFF_ID numeric(18, 0) NULL,
	USROD_TIPA_ID numeric(18, 0) NULL,
	USROD_PAY_DATE datetime NULL,
	USROD_PAY_UTC_DATE datetime NULL,
	USROD_PAY_DATE_UTC_OFFSET int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS ADD CONSTRAINT
	PK_USERS_OPERATIONS_DEBTS PRIMARY KEY CLUSTERED 
	(
	USROD_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS ADD CONSTRAINT
	FK_USERS_OPERATIONS_DEBTS_USERS FOREIGN KEY
	(
	USROD_USR_ID
	) REFERENCES dbo.USERS
	(
	USR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS ADD CONSTRAINT
	FK_USERS_OPERATIONS_DEBTS_HIS_OPERATIONS FOREIGN KEY
	(
	USROD_OPE_ID
	) REFERENCES dbo.HIS_OPERATIONS
	(
	OPE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS ADD CONSTRAINT
	FK_USERS_OPERATIONS_DEBTS_OPERATIONS_OFFSTREET FOREIGN KEY
	(
	USROD_OPEOFF_ID
	) REFERENCES dbo.OPERATIONS_OFFSTREET
	(
	OPEOFF_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS ADD CONSTRAINT
	FK_USERS_OPERATIONS_DEBTS_TICKET_PAYMENTS FOREIGN KEY
	(
	USROD_TIPA_ID
	) REFERENCES dbo.TICKET_PAYMENTS
	(
	TIPA_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_OPERATIONS_DEBTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
