/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET ADD
	OPEOFF_ENTRY_OPEOFF_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET ADD CONSTRAINT
	FK_OPERATIONS_OFFSTREET_OPERATIONS_OFFSTREET FOREIGN KEY
	(
	OPEOFF_ENTRY_OPEOFF_ID
	) REFERENCES dbo.OPERATIONS_OFFSTREET
	(
	OPEOFF_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS_OFFSTREET SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
