/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.MERCADOPAGO_CONFIGURATION
	(
	MEPACON_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	MEPACON_GUID varchar(100) NOT NULL,
	MEPACON_SDK_URL varchar(255) NOT NULL,
	MEPACON_API_URL varchar(255) NOT NULL,
	MEPACON_PUBLIC_KEY varchar(255) NOT NULL,
	MEPACON_ACCESS_TOKEN varchar(255) NOT NULL,
	MEPACON_SERVICE_TIMEOUT int NOT NULL,
	MEPACON_CHECK_DATE_AND_HASH int NOT NULL,
	MEPACON_CONFIRMATION_TIME int NOT NULL,
	MEPACON_HASH_SEED varchar(100) NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'Identifier'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Identifier GUID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_GUID'
GO
DECLARE @v sql_variant 
SET @v = N'SDK URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_SDK_URL'
GO
DECLARE @v sql_variant 
SET @v = N'API URL'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_API_URL'
GO
DECLARE @v sql_variant 
SET @v = N'Public Key'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_PUBLIC_KEY'
GO
DECLARE @v sql_variant 
SET @v = N'Access Token'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_ACCESS_TOKEN'
GO
DECLARE @v sql_variant 
SET @v = N'Wait Milliseconds'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_SERVICE_TIMEOUT'
GO
DECLARE @v sql_variant 
SET @v = N'Check date and hash or not?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_CHECK_DATE_AND_HASH'
GO
DECLARE @v sql_variant 
SET @v = N'Max Number of seconds to confirm transaction'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_CONFIRMATION_TIME'
GO
DECLARE @v sql_variant 
SET @v = N'Hash Seed'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_HASH_SEED'
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD CONSTRAINT
	DF_MERCADOPAGO_CONFIGURATION_MONCON_SERVICE_TIMEOUT DEFAULT ((5000)) FOR MEPACON_SERVICE_TIMEOUT
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD CONSTRAINT
	DF_MERCADOPAGO_CONFIGURATION_MONCON_CHECK_DATE_AND_HASH DEFAULT ((1)) FOR MEPACON_CHECK_DATE_AND_HASH
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD CONSTRAINT
	DF_MERCADOPAGO_CONFIGURATION_MONCON_CONFIRMATION_TIME DEFAULT ((300)) FOR MEPACON_CONFIRMATION_TIME
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD CONSTRAINT
	DF_MERCADOPAGO_CONFIGURATION_MONCON_HASH_SEED DEFAULT ((1)) FOR MEPACON_HASH_SEED
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD CONSTRAINT
	PK_MERCADOPAGO_CONFIGURATION PRIMARY KEY CLUSTERED 
	(
	MEPACON_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS ADD
	CUSPM_TOKEN_CARD_TYPE varchar(100) NULL,
	CUSPM_TOKEN_CARD_DOCUMENT_TYPE varchar(100) NULL,
	CUSPM_TOKEN_INSTALLMENTS varchar(100) NULL,
	CUSPM_CVV_LENGTH int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Card Document Type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_TOKEN_CARD_DOCUMENT_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Card Installments'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_TOKEN_INSTALLMENTS'
GO
DECLARE @v sql_variant 
SET @v = N'Card Type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_TOKEN_CARD_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Card CVV Length'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CUSTOMER_PAYMENT_MEANS', N'COLUMN', N'CUSPM_CVV_LENGTH'
GO
ALTER TABLE dbo.CUSTOMER_PAYMENT_MEANS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD
	CPTGC_MEPACON_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'MercadoPago Configuration'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG', N'COLUMN', N'CPTGC_MEPACON_ID'
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_MERCADOPAGO_CONFIGURATION FOREIGN KEY
	(
	CPTGC_MEPACON_ID
	) REFERENCES dbo.MERCADOPAGO_CONFIGURATION
	(
	MEPACON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
