/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION ADD
	MEPACON_CUENTAMP varchar(100) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Identificador de la Cuenta de MercadoPago'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'MERCADOPAGO_CONFIGURATION', N'COLUMN', N'MEPACON_CUENTAMP'
GO
ALTER TABLE dbo.MERCADOPAGO_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
