/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LITERALS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD
	CPTGC_DESC1_LIT_ID numeric(18, 0) NULL,
	CPTGC_DESC2_LIT_ID numeric(18, 0) NULL,
	CPTGC_ORDER int NOT NULL CONSTRAINT DF_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_CPTGC_ORDER DEFAULT 0,
	CPTGC_RECHARGE_DEF_VALUE int NULL,
	CPTGC_ICON_REF varchar(50) NULL
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LITERALS FOREIGN KEY
	(
	CPTGC_DESC1_LIT_ID
	) REFERENCES dbo.LITERALS
	(
	LIT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_LITERALS1 FOREIGN KEY
	(
	CPTGC_DESC2_LIT_ID
	) REFERENCES dbo.LITERALS
	(
	LIT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT