/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS ADD
	TARGR_CARD_PAYMENT_MODE int NOT NULL CONSTRAINT DF_TARIFFS_IN_GROUPS_TARGR_PAYMENT_MODE DEFAULT 0
GO
DECLARE @v sql_variant 
SET @v = N'Card Payment mode: 0- charge, 1- authorization, 2- AuthorizationPreferably'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TARIFFS_IN_GROUPS', N'COLUMN', N'TARGR_CARD_PAYMENT_MODE'
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
