/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_STREETS
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_STREETS_FROM
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_STREETS_TO
GO
ALTER TABLE dbo.STREETS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_INSTALLATIONS
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_GROUPS
GO
ALTER TABLE dbo.GROUPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT DF_STREET_SECTIONS_STRSE_SIDE
GO
ALTER TABLE dbo.STREET_SECTIONS
	DROP CONSTRAINT DF_STREET_SECTIONS_STRSE_DELETED
GO
CREATE TABLE dbo.Tmp_STREET_SECTIONS
	(
	STRSE_ID numeric(18, 0) NOT NULL,
	STRSE_ID_EXT varchar(50) NOT NULL,
	STRSE_DESCRIPTION varchar(255) NOT NULL,
	STRSE_STR_ID numeric(18, 0) NOT NULL,
	STRSE_STR_ID_FROM numeric(18, 0) NULL,
	STRSE_STR_ID_TO numeric(18, 0) NULL,
	STRSE_FROM int NULL,
	STRSE_TO int NULL,
	STRSE_SIDE int NOT NULL,
	STRSE_GRP_ID numeric(18, 0) NOT NULL,
	STRSE_DELETED int NOT NULL,
	STRSE_COLOUR varchar(8) NOT NULL,
	STRSE_INS_ID numeric(18, 0) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_STREET_SECTIONS SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_ID_EXT'
GO
DECLARE @v sql_variant 
SET @v = N'Street Stretch Description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_DESCRIPTION'
GO
DECLARE @v sql_variant 
SET @v = N'Street ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_STR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Street ID From'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_STR_ID_FROM'
GO
DECLARE @v sql_variant 
SET @v = N'Street ID To'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_STR_ID_TO'
GO
DECLARE @v sql_variant 
SET @v = N'Street Number From'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_FROM'
GO
DECLARE @v sql_variant 
SET @v = N'Street Number To'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_TO'
GO
DECLARE @v sql_variant 
SET @v = N'Street Side (0: unknown, 1: Odd, 2: Even'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_SIDE'
GO
DECLARE @v sql_variant 
SET @v = N'Group ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_GRP_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Registry is deleted'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_DELETED'
GO
DECLARE @v sql_variant 
SET @v = N'Colour to be used in app'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_COLOUR'
GO
DECLARE @v sql_variant 
SET @v = N'Installation Id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_STREET_SECTIONS', N'COLUMN', N'STRSE_INS_ID'
GO
ALTER TABLE dbo.Tmp_STREET_SECTIONS ADD CONSTRAINT
	DF_STREET_SECTIONS_STRSE_SIDE DEFAULT ((0)) FOR STRSE_SIDE
GO
ALTER TABLE dbo.Tmp_STREET_SECTIONS ADD CONSTRAINT
	DF_STREET_SECTIONS_STRSE_DELETED DEFAULT ((0)) FOR STRSE_DELETED
GO
IF EXISTS(SELECT * FROM dbo.STREET_SECTIONS)
	 EXEC('INSERT INTO dbo.Tmp_STREET_SECTIONS (STRSE_ID, STRSE_ID_EXT, STRSE_DESCRIPTION, STRSE_STR_ID, STRSE_STR_ID_FROM, STRSE_STR_ID_TO, STRSE_FROM, STRSE_TO, STRSE_SIDE, STRSE_GRP_ID, STRSE_DELETED, STRSE_COLOUR, STRSE_INS_ID)
		SELECT STRSE_ID, STRSE_ID_EXT, STRSE_DESCRIPTION, STRSE_STR_ID, STRSE_STR_ID_FROM, STRSE_STR_ID_TO, STRSE_FROM, STRSE_TO, STRSE_SIDE, STRSE_GRP_ID, STRSE_DELETED, STRSE_COLOUR, STRSE_INS_ID FROM dbo.STREET_SECTIONS WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.STREET_SECTIONS_GEOMETRY
	DROP CONSTRAINT FK_STREET_SECTIONS_GEOMETRY_STREET_SECTIONS
GO
ALTER TABLE dbo.STREET_SECTIONS_STREET_SECTIONS_GRID
	DROP CONSTRAINT FK_STREET_SECTIONS_STREET_SECTIONS_GRID_STREET_SECTIONS
GO
ALTER TABLE dbo.STREET_SECTIONS_TYPES_ASSIGNATIONS
	DROP CONSTRAINT FK_STREET_SECTIONS_TYPES_ASSIGNATIONS_STREET_SECTIONS
GO
ALTER TABLE dbo.TARIFFS_IN_STREETS_SECTIONS
	DROP CONSTRAINT FK_TARIFFS_IN_STREETS_SECTIONS_STREET_SECTIONS
GO
ALTER TABLE dbo.TARIFF_IN_STREETS_SECTIONS_COMPILED
	DROP CONSTRAINT FK_TARIFF_IN_STREETS_SECTIONS_COMPILED_STREET_SECTIONS
GO
ALTER TABLE dbo.OPERATIONS
	DROP CONSTRAINT FK_OPERATIONS_STREET_SECTIONS
GO
ALTER TABLE dbo.HIS_OPERATIONS
	DROP CONSTRAINT FK_HIS_OPERATIONS_STREET_SECTIONS
GO
DROP TABLE dbo.STREET_SECTIONS
GO
EXECUTE sp_rename N'dbo.Tmp_STREET_SECTIONS', N'STREET_SECTIONS', 'OBJECT' 
GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	PK_STREET_SECTIONS PRIMARY KEY CLUSTERED 
	(
	STRSE_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_GROUPS FOREIGN KEY
	(
	STRSE_GRP_ID
	) REFERENCES dbo.GROUPS
	(
	GRP_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_INSTALLATIONS FOREIGN KEY
	(
	STRSE_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_STREETS FOREIGN KEY
	(
	STRSE_STR_ID
	) REFERENCES dbo.STREETS
	(
	STR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_STREETS_FROM FOREIGN KEY
	(
	STRSE_STR_ID_FROM
	) REFERENCES dbo.STREETS
	(
	STR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_STREETS_TO FOREIGN KEY
	(
	STRSE_STR_ID_TO
	) REFERENCES dbo.STREETS
	(
	STR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HIS_OPERATIONS ADD CONSTRAINT
	FK_HIS_OPERATIONS_STREET_SECTIONS FOREIGN KEY
	(
	OPE_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS ADD CONSTRAINT
	FK_OPERATIONS_STREET_SECTIONS FOREIGN KEY
	(
	OPE_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFF_IN_STREETS_SECTIONS_COMPILED ADD CONSTRAINT
	FK_TARIFF_IN_STREETS_SECTIONS_COMPILED_STREET_SECTIONS FOREIGN KEY
	(
	TARSTRSEC_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFF_IN_STREETS_SECTIONS_COMPILED SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS_IN_STREETS_SECTIONS ADD CONSTRAINT
	FK_TARIFFS_IN_STREETS_SECTIONS_STREET_SECTIONS FOREIGN KEY
	(
	TARSTRSE_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS_IN_STREETS_SECTIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS_TYPES_ASSIGNATIONS ADD CONSTRAINT
	FK_STREET_SECTIONS_TYPES_ASSIGNATIONS_STREET_SECTIONS FOREIGN KEY
	(
	STRSETA_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS_TYPES_ASSIGNATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS_STREET_SECTIONS_GRID ADD CONSTRAINT
	FK_STREET_SECTIONS_STREET_SECTIONS_GRID_STREET_SECTIONS FOREIGN KEY
	(
	STRSESSG_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS_STREET_SECTIONS_GRID SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.STREET_SECTIONS_GEOMETRY ADD CONSTRAINT
	FK_STREET_SECTIONS_GEOMETRY_STREET_SECTIONS FOREIGN KEY
	(
	STRSEGE_STRSE_ID
	) REFERENCES dbo.STREET_SECTIONS
	(
	STRSE_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.STREET_SECTIONS_GEOMETRY SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
