/****** Object:  UserDefinedFunction [dbo].[InstallationCurrencies]    Script Date: 01/10/2018 18:08:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[InstallationCurrencies](@InsId numeric)
RETURNS varchar(500)
AS
BEGIN

	DECLARE @ret varchar(500);

	DECLARE @Cursor AS CURSOR;
	DECLARE @CurId AS varchar(50);

	SELECT @ret = CONVERT(VARCHAR, INS_CUR_ID) + ',' 
	FROM INSTALLATIONS
	WHERE INS_ID = @InsId;

	SET @Cursor = CURSOR FOR
		SELECT DISTINCT GC.CPTGC_CUR_ID 
		 FROM INSTALLATIONS 
				INNER JOIN CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ON INS_CPTGC_ID = CPTGC_ID,
			  CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG GC
		 WHERE INSTALLATIONS.INS_ID = @InsId AND
			   GC.CPTGC_CTG_ID = CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG.CPTGC_CTG_ID AND
			   GC.CPTGC_CUR_ID != INS_CUR_ID;
 
	OPEN @Cursor;
	FETCH NEXT FROM @Cursor INTO @CurId
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @ret = @ret + CONVERT(VARCHAR, @CurId) + ',';
		FETCH NEXT FROM @Cursor INTO @CurId;
	END
 
	CLOSE @Cursor;
	DEALLOCATE @Cursor;

	IF (@ret <> '') 
		SET @ret = SUBSTRING(@ret, 1, LEN(@ret) - 1);

	RETURN @ret;

END




GO


CREATE VIEW [dbo].[VW_INSTALLATIONS]
AS

	SELECT INS_ID, INS_DESCRIPTION, INS_SHORTDESC, [dbo].[InstallationCurrencies](INS_ID) AS Currencies
	FROM INSTALLATIONS		
	WHERE INS_ID NOT IN (SELECT SINS_CHILD_INS_ID FROM SUPER_INSTALLATIONS WHERE SINS_INI_APPLY_DATE <= GETUTCDATE() AND SINS_END_APPLY_DATE > GETUTCDATE()) AND
		  INS_ENABLED = 1 



GO


