
/******************************************************************************/
/*                             CAMPAING                                       */
/******************************************************************************/
CREATE TABLE [dbo].[CAMPAING](
	[CAMP_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CAMP_DESCRIPTION] [nvarchar](100) NULL,
	[CAMP_SCHEMA] [numeric](18, 0) NOT NULL,
	[CAMP_STATUS] [int] NOT NULL,
	[CAMP_COU_ID] [numeric](18, 0) NOT NULL,
	[CAMP_MAX_DELIVER_AMOUNT] [int] NULL,
	[CAMP_INSERTION_UTC_DATE] [date] NOT NULL,
	[CAMP_INITIAL_DELIVERY_DATE] [date] NOT NULL,
	[CAMP_END_DELIVERY_DATE] [date] NULL,
	[CAMP_USER_DELIVER_AMOUNT] [int] NOT NULL,
	[CAMP_USER_MAX_USES] [int] NOT NULL,
 CONSTRAINT [PK_CAMPAING] PRIMARY KEY CLUSTERED 
(
	[CAMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CAMPAING] ADD  CONSTRAINT [DF_CAMPAING_CAMP_STATUS]  DEFAULT ((1)) FOR [CAMP_STATUS]
GO

ALTER TABLE [dbo].[CAMPAING]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_COUNTRIES] FOREIGN KEY([CAMP_COU_ID])
REFERENCES [dbo].[COUNTRIES] ([COU_ID])
GO

ALTER TABLE [dbo].[CAMPAING] CHECK CONSTRAINT [FK_CAMPAING_COUNTRIES]
GO






/******************************************************************************/
/*                      CAMPAING_USER_ASSIGNATION                             */
/******************************************************************************/

CREATE TABLE [dbo].[CAMPAING_USER_ASSIGNATION](
	[CAUS_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CAUS_CAMP_ID] [numeric](18, 0) NOT NULL,
	[CAUS_USR_ID] [numeric](18, 0) NOT NULL,
	[CAUS_CURRENT_NUMBER_ID_USES] [numeric](18, 0) NOT NULL,
	[CAUS_STATUS] [int] NOT NULL,
	[CAUS_INSERTION_UTC_DATE] [date] NOT NULL,
	[CAUS_STATUS_UTC_DATE] [date] NOT NULL,
 CONSTRAINT [PK_CAMPAING_USER_ASSIGNATION] PRIMARY KEY CLUSTERED 
(
	[CAUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CAMPAING_USER_ASSIGNATION] ADD  CONSTRAINT [DF_CAMPAING_USER_ASSIGNATION_CAUS_STATUS]  DEFAULT ((1)) FOR [CAUS_STATUS]
GO

ALTER TABLE [dbo].[CAMPAING_USER_ASSIGNATION]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_USER_ASSIGNATION_CAMPAING] FOREIGN KEY([CAUS_CAMP_ID])
REFERENCES [dbo].[CAMPAING] ([CAMP_ID])
GO

ALTER TABLE [dbo].[CAMPAING_USER_ASSIGNATION] CHECK CONSTRAINT [FK_CAMPAING_USER_ASSIGNATION_CAMPAING]
GO

ALTER TABLE [dbo].[CAMPAING_USER_ASSIGNATION]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAING_USER_ASSIGNATION_USERS] FOREIGN KEY([CAUS_USR_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[CAMPAING_USER_ASSIGNATION] CHECK CONSTRAINT [FK_CAMPAING_USER_ASSIGNATION_USERS]
GO







/******************************************************************************/
/*                          CAMPAIGN_USER_USE                                 */
/******************************************************************************/
CREATE TABLE [dbo].[CAMPAIGN_USER_USE](
	[CAUSS_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CAUSS_CAUS_ID] [numeric](18, 0) NOT NULL,
	[CAUSS_DATE] [date] NOT NULL,
	[CAUSS_UTC_DATE] [date] NOT NULL,
	[CAUSS_OPE_ID] [numeric](18, 0) NULL,
	[CAUSS_TIPA_ID] [numeric](18, 0) NULL,
	[CAUSS_CUSPMR_ID] [numeric](18, 0) NOT NULL,
	[CAUSS_USRF_ACCEPT_USR_ID] [numeric](18, 0) NULL,
 CONSTRAINT [PK_CAMPAIGN_USER_USE] PRIMARY KEY CLUSTERED 
(
	[CAUSS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION] FOREIGN KEY([CAUSS_CAUS_ID])
REFERENCES [dbo].[CAMPAING_USER_ASSIGNATION] ([CAUS_ID])
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE] CHECK CONSTRAINT [FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION]
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES] FOREIGN KEY([CAUSS_CUSPMR_ID])
REFERENCES [dbo].[CUSTOMER_PAYMENT_MEANS_RECHARGES] ([CUSPMR_ID])
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE] CHECK CONSTRAINT [FK_CAMPAIGN_USER_USE_CUSTOMER_PAYMENT_MEANS_RECHARGES]
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_USER_USE_OPERATIONS] FOREIGN KEY([CAUSS_OPE_ID])
REFERENCES [dbo].[HIS_OPERATIONS] ([OPE_ID])
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE] CHECK CONSTRAINT [FK_CAMPAIGN_USER_USE_OPERATIONS]
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS] FOREIGN KEY([CAUSS_TIPA_ID])
REFERENCES [dbo].[TICKET_PAYMENTS] ([TIPA_ID])
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE] CHECK CONSTRAINT [FK_CAMPAIGN_USER_USE_TICKET_PAYMENTS]
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_USER_USE_USERS] FOREIGN KEY([CAUSS_USRF_ACCEPT_USR_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[CAMPAIGN_USER_USE] CHECK CONSTRAINT [FK_CAMPAIGN_USER_USE_USERS]
GO

