/****** Object:  StoredProcedure [dbo].[Report_INVOICE]    Script Date: 09/11/2018 15:19:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[Report_INVOICE]
	@InvoiceId AS numeric
AS	
BEGIN
	

SELECT CI.*, OPERATORS.*, CUSTOMERS.*, CURRENCIES.*, COUNTRIES.*,
			(SELECT COUNT(*) FROM CUSTOMER_PAYMENT_MEANS_RECHARGES WHERE CUSPMR_CUSINV_ID =  CI.CUSINV_ID) RECHARGES_COUNT,
			(SELECT COUNT(*) FROM HIS_OPERATIONS WHERE OPE_CUSINV_ID =  CI.CUSINV_ID) OPERATIONS_COUNT,
			(SELECT COUNT(*) FROM TICKET_PAYMENTS WHERE TIPA_CUSINV_ID =  CI.CUSINV_ID) TICKET_PAYMENTS_COUNT,
			(SELECT COUNT(*) FROM SERVICE_CHARGES WHERE SECH_CUSINV_ID =  CI.CUSINV_ID) SERVICE_CHARGES_COUNT,
			(SELECT COUNT(*) FROM OPERATIONS_OFFSTREET WHERE OPEOFF_CUSINV_ID =  CI.CUSINV_ID) OPERATIONSOFFSTREET_COUNT
FROM CUSTOMER_INVOICES CI
		INNER JOIN OPERATORS ON CUSINV_OPR_ID = OPR_ID
		INNER JOIN CUSTOMERS ON CUSINV_CUS_ID = CUS_ID
		INNER JOIN CURRENCIES ON CUSINV_CUR_ID = CUR_ID
		INNER JOIN COUNTRIES ON CUS_COU_ID = COU_ID
WHERE CUSINV_ID = @InvoiceId


END



GO







CREATE PROCEDURE [dbo].[Report_INVOICEOPERATIONSOFFSTREET]
	@InvoiceId AS numeric
AS	
BEGIN
	
SELECT H1.*, CURRENCIES.*, USERS.*, USER_PLATES.*, GROUPS.*, INS_DESCRIPTION,
			ROUND(CASE WHEN ISNULL(OPEOFF_PERC_FEE_TOPPED,0) > 0 AND ISNULL(OPEOFF_PERC_FEE_TOPPED,0) < (OPEOFF_AMOUNT * ISNULL(OPEOFF_PERC_FEE,0)) THEN OPEOFF_PERC_FEE_TOPPED ELSE (OPEOFF_AMOUNT * ISNULL(OPEOFF_PERC_FEE,0)) END + ISNULL(OPEOFF_FIXED_FEE, 0), 0)
				OPEOFF_FEE,
			ROUND(ISNULL(OPEOFF_PARTIAL_VAT1, 0) + 
				  ((CASE WHEN ISNULL(OPEOFF_PERC_FEE_TOPPED,0) > 0 AND ISNULL(OPEOFF_PERC_FEE_TOPPED,0) < (OPEOFF_AMOUNT * ISNULL(OPEOFF_PERC_FEE,0)) THEN OPEOFF_PERC_FEE_TOPPED ELSE ROUND(OPEOFF_AMOUNT * ISNULL(OPEOFF_PERC_FEE,0),0) END)  * ISNULL(OPEOFF_PERC_VAT2,0)) +
				  (ISNULL(OPEOFF_FIXED_FEE,0)  * ISNULL(OPEOFF_PERC_VAT2,0))
				  , 0) OPEOFF_VAT,
			(SELECT COUNT(DISTINCT H2.OPEOFF_PERC_VAT2) FROM OPERATIONS_OFFSTREET H2 WHERE ISNULL(H2.OPEOFF_PERC_VAT2, 0) <> 0 AND H2.OPEOFF_CUSINV_ID = H1.OPEOFF_CUSINV_ID) NUM_VATS,
			(SELECT TOP 1 H2.OPE_PERC_VAT2 FROM HIS_OPERATIONS H2 WHERE ISNULL(H2.OPE_PERC_VAT2, 0) <> 0 AND H2.OPE_CUSINV_ID = H1.OPEOFF_CUSINV_ID) VAT

FROM OPERATIONS_OFFSTREET H1
		INNER JOIN CURRENCIES ON OPEOFF_AMOUNT_CUR_ID = CUR_ID
		INNER JOIN USERS ON OPEOFF_USR_ID = USR_ID
		INNER JOIN INSTALLATIONS ON OPEOFF_INS_ID = INS_ID
		LEFT JOIN USER_PLATES ON OPEOFF_USRP_ID = USRP_ID
		LEFT JOIN GROUPS ON OPEOFF_GRP_ID = GRP_ID
WHERE OPEOFF_CUSINV_ID = @InvoiceId

END




GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Procedure to return Invoice Offstreet Operations Section Data' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'PROCEDURE',@level1name=N'Report_INVOICEOPERATIONSOFFSTREET'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Invoice ID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'PROCEDURE',@level1name=N'Report_INVOICEOPERATIONSOFFSTREET', @level2type=N'PARAMETER',@level2name=N'@InvoiceId'
GO


