ALTER TABLE dbo.TARIFFS_IN_GROUPS ADD
	TARGR_TAR_INFO2_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO3_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO4_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO5_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO6_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO7_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO8_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO9_LIT_ID numeric(18, 0) NULL,
	TARGR_TAR_INFO10_LIT_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS SET (LOCK_ESCALATION = TABLE)
GO




CREATE VIEW ALL_LITERALS_TARIFF_LANGUAGE AS
Select 
t.TARGR_TAR_ID, 
t.TARGR_LIT_ID, 
l.LIT_ID, 
l.LIT_DESCRIPTION, 
ll.LITL_LITERAL, 
ll.LITL_LAN_ID 
from TARIFFS_IN_GROUPS T
left join LITERALS L on (
							(L.LIT_ID= t.TARGR_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO2_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO3_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO4_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO5_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO6_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO7_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO8_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO9_LIT_ID) or
							(L.LIT_ID= t.TARGR_TAR_INFO10_LIT_ID)
							)
left join LITERAL_LANGUAGES LL on L.LIT_ID= ll.LITL_LIT_ID
