/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_PAYMENT_SUBTYPES
GO
ALTER TABLE dbo.PAYMENT_SUBTYPES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_PAYMENT_TYPES
GO
ALTER TABLE dbo.PAYMENT_TYPES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSTALLATIONS
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_SUSCRIPTION_TYPE
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_IS_TAX
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_PERC_FEE_APPLY
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_PERC_FEE_TOPPED_APPLY
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
	DROP CONSTRAINT DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_FIXED_FEE_APPLY
GO
CREATE TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE
	(
	INSF_ID numeric(18, 0) NOT NULL IDENTITY (1, 1),
	INSF_INS_ID numeric(18, 0) NOT NULL,
	INSF_SUSCRIPTION_TYPE int NOT NULL,
	INSF_PAT_ID int NULL,
	INSF_PAST_ID int NULL,
	INSF_OPE_TYPE int NOT NULL,
	INSF_TAR_TYPE int NULL,
	INSF_IS_TAX int NOT NULL,
	INSF_PERC_FEE_APPLY int NOT NULL,
	INSF_PERC_FEE numeric(18, 5) NULL,
	INSF_PERC_FEE_TOPPED_APPLY int NOT NULL,
	INSF_PERC_FEE_TOPPED numeric(18, 0) NULL,
	INSF_FIXED_FEE_APPLY int NOT NULL,
	INSF_FIXED_FEE numeric(18, 0) NULL,
	INSF_INI_APPLY_DATE datetime NOT NULL,
	INSF_END_APPLY_DATE datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Table to store installation Finantial parametres by operation type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', NULL, NULL
GO
DECLARE @v sql_variant 
SET @v = N'identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Installation'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_INS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Suscription type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_SUSCRIPTION_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Payment mean type id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PAT_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Payment mean subtype id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PAST_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Operation type'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_OPE_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Tariff type (0: standard, 1: permit)'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_TAR_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'Is tax?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_IS_TAX'
GO
DECLARE @v sql_variant 
SET @v = N'Percentage fee apply'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PERC_FEE_APPLY'
GO
DECLARE @v sql_variant 
SET @v = N'Percentage fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PERC_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'Topped fee apply'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PERC_FEE_TOPPED_APPLY'
GO
DECLARE @v sql_variant 
SET @v = N'Topped fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_PERC_FEE_TOPPED'
GO
DECLARE @v sql_variant 
SET @v = N'Fixed fee apply?'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_FIXED_FEE_APPLY'
GO
DECLARE @v sql_variant 
SET @v = N'Fixed fee'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_FIXED_FEE'
GO
DECLARE @v sql_variant 
SET @v = N'Ini apply date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_INI_APPLY_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'End apply date'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'COLUMN', N'INSF_END_APPLY_DATE'
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_SUSCRIPTION_TYPE DEFAULT ((1)) FOR INSF_SUSCRIPTION_TYPE
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_IS_TAX DEFAULT ((0)) FOR INSF_IS_TAX
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_PERC_FEE_APPLY DEFAULT ((0)) FOR INSF_PERC_FEE_APPLY
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_PERC_FEE_TOPPED_APPLY DEFAULT ((0)) FOR INSF_PERC_FEE_TOPPED_APPLY
GO
ALTER TABLE dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	DF_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSF_FIXED_FEE_APPLY DEFAULT ((0)) FOR INSF_FIXED_FEE_APPLY
GO
SET IDENTITY_INSERT dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE ON
GO
IF EXISTS(SELECT * FROM dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE)
	 EXEC('INSERT INTO dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE (INSF_ID, INSF_INS_ID, INSF_SUSCRIPTION_TYPE, INSF_PAT_ID, INSF_PAST_ID, INSF_OPE_TYPE, INSF_IS_TAX, INSF_PERC_FEE_APPLY, INSF_PERC_FEE, INSF_PERC_FEE_TOPPED_APPLY, INSF_PERC_FEE_TOPPED, INSF_FIXED_FEE_APPLY, INSF_FIXED_FEE, INSF_INI_APPLY_DATE, INSF_END_APPLY_DATE)
		SELECT INSF_ID, INSF_INS_ID, INSF_SUSCRIPTION_TYPE, INSF_PAT_ID, INSF_PAST_ID, INSF_OPE_TYPE, INSF_IS_TAX, INSF_PERC_FEE_APPLY, INSF_PERC_FEE, INSF_PERC_FEE_TOPPED_APPLY, INSF_PERC_FEE_TOPPED, INSF_FIXED_FEE_APPLY, INSF_FIXED_FEE, INSF_INI_APPLY_DATE, INSF_END_APPLY_DATE FROM dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE OFF
GO
DROP TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE
GO
EXECUTE sp_rename N'dbo.Tmp_INSTALLATIONS_FINAN_PARS_OPE_TYPE', N'INSTALLATIONS_FINAN_PARS_OPE_TYPE', 'OBJECT' 
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	PK_INSTALLATIONS_FINAN_PARS_OPE_TYPE PRIMARY KEY CLUSTERED 
	(
	INSF_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_INSTALLATIONS FOREIGN KEY
	(
	INSF_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_PAYMENT_TYPES FOREIGN KEY
	(
	INSF_PAT_ID
	) REFERENCES dbo.PAYMENT_TYPES
	(
	PAT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS_FINAN_PARS_OPE_TYPE ADD CONSTRAINT
	FK_INSTALLATIONS_FINAN_PARS_OPE_TYPE_PAYMENT_SUBTYPES FOREIGN KEY
	(
	INSF_PAST_ID
	) REFERENCES dbo.PAYMENT_SUBTYPES
	(
	PAST_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
