BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS ADD
	TAR_BEHAVIOR int NULL
GO
DECLARE @v sql_variant 
SET @v = N'0 standard, 1 StartStop'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'TARIFFS', N'COLUMN', N'TAR_BEHAVIOR'
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_BEHAVIOR DEFAULT ((0)) FOR TAR_BEHAVIOR
GO
ALTER TABLE dbo.TARIFFS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

Update TARIFFS SET TAR_BEHAVIOR=0