/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS
	DROP CONSTRAINT FK_TARIFFS_LITERALS
GO
ALTER TABLE dbo.LITERALS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS
	DROP CONSTRAINT FK_TARIFFS_INSTALLATIONS
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS
	DROP CONSTRAINT DF_TARIFFS_TAR_TYPE
GO
ALTER TABLE dbo.TARIFFS
	DROP CONSTRAINT DF_TARIFFS_TAR_MAX_PLATES
GO
ALTER TABLE dbo.TARIFFS
	DROP CONSTRAINT DF_TARIFFS_TAR_BEHAVIOR
GO
CREATE TABLE dbo.Tmp_TARIFFS
	(
	TAR_ID numeric(18, 0) NOT NULL,
	TAR_DESCRIPTION varchar(500) NOT NULL,
	TAR_LIT_ID numeric(18, 0) NOT NULL,
	TAR_QUERY_EXT_ID varchar(50) NULL,
	TAR_EXT1_ID varchar(50) NULL,
	TAR_EXT2_ID varchar(50) NULL,
	TAR_EXT3_ID varchar(50) NULL,
	TAR_ID_FOR_EXT_OPS varchar(50) NULL,
	TAR_INS_ID numeric(18, 0) NOT NULL,
	TAR_MIN_COIN int NULL,
	TAR_TYPE int NOT NULL,
	TAR_PERMIT_RENEWAL_DAY int NULL,
	TAR_MAX_PLATES int NOT NULL,
	TAR_MAX_PERMITS_ONCE int NULL,
	TAR_BEHAVIOR int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_TARIFFS SET (LOCK_ESCALATION = TABLE)
GO
DECLARE @v sql_variant 
SET @v = N'Table to store Tariffs'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', NULL, NULL
GO
DECLARE @v sql_variant 
SET @v = N'Identificator'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Tariff Description'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_DESCRIPTION'
GO
DECLARE @v sql_variant 
SET @v = N'Literal ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_LIT_ID'
GO
DECLARE @v sql_variant 
SET @v = N'External ID When communicationg external systems in query parking'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_QUERY_EXT_ID'
GO
DECLARE @v sql_variant 
SET @v = N'External ID When communicationg external systems 1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_EXT1_ID'
GO
DECLARE @v sql_variant 
SET @v = N'External ID When communicationg external systems 2'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_EXT2_ID'
GO
DECLARE @v sql_variant 
SET @v = N'External ID When communicationg external systems 3'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_EXT3_ID'
GO
DECLARE @v sql_variant 
SET @v = N'Id for external operations'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_ID_FOR_EXT_OPS'
GO
DECLARE @v sql_variant 
SET @v = N'Installation id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_INS_ID'
GO
DECLARE @v sql_variant 
SET @v = N'0: standard, 1: permit'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_TYPE'
GO
DECLARE @v sql_variant 
SET @v = N'0 standard, 1 StartStop'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Tmp_TARIFFS', N'COLUMN', N'TAR_BEHAVIOR'
GO
ALTER TABLE dbo.Tmp_TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_TYPE DEFAULT ((0)) FOR TAR_TYPE
GO
ALTER TABLE dbo.Tmp_TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_MAX_PLATES DEFAULT ((1)) FOR TAR_MAX_PLATES
GO
ALTER TABLE dbo.Tmp_TARIFFS ADD CONSTRAINT
	DF_TARIFFS_TAR_BEHAVIOR DEFAULT ((0)) FOR TAR_BEHAVIOR
GO
IF EXISTS(SELECT * FROM dbo.TARIFFS)
	 EXEC('INSERT INTO dbo.Tmp_TARIFFS (TAR_ID, TAR_DESCRIPTION, TAR_LIT_ID, TAR_QUERY_EXT_ID, TAR_EXT1_ID, TAR_EXT2_ID, TAR_EXT3_ID, TAR_ID_FOR_EXT_OPS, TAR_INS_ID, TAR_MIN_COIN, TAR_TYPE, TAR_PERMIT_RENEWAL_DAY, TAR_MAX_PLATES, TAR_MAX_PERMITS_ONCE, TAR_BEHAVIOR)
		SELECT TAR_ID, TAR_DESCRIPTION, TAR_LIT_ID, TAR_QUERY_EXT_ID, TAR_EXT1_ID, TAR_EXT2_ID, TAR_EXT3_ID, TAR_ID_FOR_EXT_OPS, TAR_INS_ID, TAR_MIN_COIN, TAR_TYPE, TAR_PERMIT_RENEWAL_DAY, TAR_MAX_PLATES, TAR_MAX_PERMITS_ONCE, TAR_BEHAVIOR FROM dbo.TARIFFS WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.USERS_FAVOURITES_AREAS
	DROP CONSTRAINT FK_USERS_FAVOURITES_AREAS_TARIFFS
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS
	DROP CONSTRAINT FK_TARIFFS_IN_GROUPS_TARIFFS
GO
ALTER TABLE dbo.PLATES_TARIFFS
	DROP CONSTRAINT FK_PLATES_TARIFFS_TARIFFS
GO
ALTER TABLE dbo.GROUPS_TARIFFS_EXTERNAL_TRANSLATIONS
	DROP CONSTRAINT FK_GROUPS_TARIFFS_EXTERNAL_TRANSLATIONS_TARIFFS
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS_GEOMETRY
	DROP CONSTRAINT FK_TARIFFS_IN_GROUPS_GEOMETRY_TARIFFS
GO
ALTER TABLE dbo.OPERATIONS
	DROP CONSTRAINT FK_OPERATIONS_TARIFFS
GO
ALTER TABLE dbo.EXTERNAL_PARKING_OPERATIONS
	DROP CONSTRAINT FK_EXTERNAL_PARKING_OPERATIONS_TARIFFS
GO
ALTER TABLE dbo.OPERATIONS_ONLINE_NOANSWERED
	DROP CONSTRAINT FK_OPERATIONS_ONLINE_NOANSWERED_TARIFFS
GO
ALTER TABLE dbo.HIS_OPERATIONS
	DROP CONSTRAINT FK_HIS_OPERATIONS_TARIFFS
GO
DROP TABLE dbo.TARIFFS
GO
EXECUTE sp_rename N'dbo.Tmp_TARIFFS', N'TARIFFS', 'OBJECT' 
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	PK_TARIFFS PRIMARY KEY CLUSTERED 
	(
	TAR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	FK_TARIFFS_INSTALLATIONS FOREIGN KEY
	(
	TAR_INS_ID
	) REFERENCES dbo.INSTALLATIONS
	(
	INS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS ADD CONSTRAINT
	FK_TARIFFS_LITERALS FOREIGN KEY
	(
	TAR_LIT_ID
	) REFERENCES dbo.LITERALS
	(
	LIT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HIS_OPERATIONS ADD CONSTRAINT
	FK_HIS_OPERATIONS_TARIFFS FOREIGN KEY
	(
	OPE_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.HIS_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS_ONLINE_NOANSWERED ADD CONSTRAINT
	FK_OPERATIONS_ONLINE_NOANSWERED_TARIFFS FOREIGN KEY
	(
	OPE_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS_ONLINE_NOANSWERED SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.EXTERNAL_PARKING_OPERATIONS ADD CONSTRAINT
	FK_EXTERNAL_PARKING_OPERATIONS_TARIFFS FOREIGN KEY
	(
	EPO_TARIFF
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.EXTERNAL_PARKING_OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OPERATIONS ADD CONSTRAINT
	FK_OPERATIONS_TARIFFS FOREIGN KEY
	(
	OPE_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OPERATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS_GEOMETRY ADD CONSTRAINT
	FK_TARIFFS_IN_GROUPS_GEOMETRY_TARIFFS FOREIGN KEY
	(
	TAGRGE_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS_GEOMETRY SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.GROUPS_TARIFFS_EXTERNAL_TRANSLATIONS ADD CONSTRAINT
	FK_GROUPS_TARIFFS_EXTERNAL_TRANSLATIONS_TARIFFS FOREIGN KEY
	(
	GTET_IN_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.GROUPS_TARIFFS_EXTERNAL_TRANSLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PLATES_TARIFFS ADD CONSTRAINT
	FK_PLATES_TARIFFS_TARIFFS FOREIGN KEY
	(
	PLTA_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PLATES_TARIFFS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS ADD CONSTRAINT
	FK_TARIFFS_IN_GROUPS_TARIFFS FOREIGN KEY
	(
	TARGR_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TARIFFS_IN_GROUPS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USERS_FAVOURITES_AREAS ADD CONSTRAINT
	FK_USERS_FAVOURITES_AREAS_TARIFFS FOREIGN KEY
	(
	USRA_TAR_ID
	) REFERENCES dbo.TARIFFS
	(
	TAR_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.USERS_FAVOURITES_AREAS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
