/****** Object:  Index [OPERATIONS_QUICKSEARCH]    Script Date: 1/15/2019 10:22:20 AM ******/
CREATE NONCLUSTERED INDEX [OPERATIONS_QUICKSEARCH] ON [dbo].[OPERATIONS]
(
	[OPE_USR_ID] ASC,
	[OPE_MOSE_OS] ASC,
	[OPE_USRP_ID] ASC,
	[OPE_INS_ID] ASC,
	[OPE_TYPE] ASC,
	[OPE_GRP_ID] ASC,
	[OPE_TAR_ID] ASC,
	[OPE_PLATE2_USRP_ID] ASC,
	[OPE_PLATE3_USRP_ID] ASC,
	[OPE_PLATE4_USRP_ID] ASC,
	[OPE_PLATE5_USRP_ID] ASC,
	[OPE_PLATE6_USRP_ID] ASC,
	[OPE_PLATE7_USRP_ID] ASC,
	[OPE_PLATE8_USRP_ID] ASC,
	[OPE_PLATE9_USRP_ID] ASC,
	[OPE_PLATE10_USRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [HIS_PARKINGS_QUICKSEARCH]    Script Date: 1/15/2019 10:40:04 AM ******/
CREATE NONCLUSTERED INDEX [HIS_PARKINGS_QUICKSEARCH] ON [dbo].[HIS_OPERATIONS]
(
	[OPE_USR_ID] ASC,
	[OPE_MOSE_OS] ASC,
	[OPE_USRP_ID] ASC,
	[OPE_INS_ID] ASC,
	[OPE_TYPE] ASC,
	[OPE_GRP_ID] ASC,
	[OPE_TAR_ID] ASC,
	[OPE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


