ALTER TABLE dbo.CAMPAIGN_USER_USE
	DROP CONSTRAINT FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION
GO


ALTER TABLE [CAMPAIGN_USER_USE] ALTER COLUMN [CAUSS_CAUS_ID] numeric(18, 0) NULL
GO


ALTER TABLE dbo.CAMPAIGN_USER_USE ADD
	CAUSS_CELL_IMEI varchar(100) NULL,
	CAUSS_CAMP_ID numeric(18, 0) NULL
GO


ALTER TABLE dbo.CAMPAIGN_USER_USE ADD CONSTRAINT
	FK_CAMPAIGN_USER_USE_CAMPAING_USER_ASSIGNATION1 FOREIGN KEY
	(
	CAUSS_CAUS_ID
	) REFERENCES dbo.CAMPAING_USER_ASSIGNATION
	(
	CAUS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO