ALTER TABLE dbo.INSTALLATIONS ADD
	INS_CITY_LIT_FINE_NUMBER numeric(18, 0) NULL
GO

BEGIN TRANSACTION
GO
ALTER TABLE dbo.LITERALS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD CONSTRAINT
	FK_INSTALLATIONS_LITERALS2 FOREIGN KEY
	(
	INS_CITY_LIT_FINE_NUMBER
	) REFERENCES dbo.LITERALS
	(
	LIT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT



Select * from [LITERALS] where [LIT_ID] in (60000008,60000009)


INSERT INTO [dbo].[LITERALS]([LIT_ID],[LIT_DESCRIPTION],[LIT_KEY])
VALUES(60000008,'cityFineNumberLit No Madrid',NULL)
INSERT INTO [dbo].[LITERALS]([LIT_ID],[LIT_DESCRIPTION],[LIT_KEY])
VALUES(60000009,'cityFineNumberLit Madrid',NULL)
GO

Select * from LANGUAGES

INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000008,1,'Número de Expediente')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000008,2,'Ticket Number')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000008,3,'Numéro de dossier')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000008,4,'Número d''Expedient')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000008,5,'Número de Multa')
GO


INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000009,1,'Número de Boletín')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000009,2,'Ticket Number')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000009,3,'Numéro de dossier')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000009,4,'Número de Butlletí')
INSERT INTO [dbo].[LITERAL_LANGUAGES]([LITL_LIT_ID],[LITL_LAN_ID],[LITL_LITERAL])
VALUES(60000009,5,'Número de Multa')

Select * from INSTALLATIONS where INS_ID=300017

UPDATE INSTALLATIONS SET INS_CITY_LIT_FINE_NUMBER=60000008
UPDATE INSTALLATIONS SET INS_CITY_LIT_FINE_NUMBER=60000009 where INS_ID=300017