SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Report_LIQUIDATIONDETAIL_CANADA_WITH_TARTYPE_AND_TICKETPAYMENTS]
	@DateIniUTC AS DATETIME,
	@DateEndUTC AS DATETIME,
	@Culture	AS VARCHAR(5)
AS	
BEGIN

IF @Culture IS NULL
BEGIN
	SET @Culture = 'en-US'
END

SELECT x.OPE_INS_ID, x.GRP_ID, x.REGION, x.[REGION NAME], x.[PAYBYPHONE LOT ID], x.[LOT NAME], 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.Free) ELSE 0 END Free0, 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.Payments) ELSE 0 END Payments0, 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.Refunds) ELSE 0 END Refunds0, 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.[Parking FEE]) ELSE 0 END ParkingFEE0, 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.[PAYBYPHONE CONSUMER FEE]) ELSE 0 END CONSUMERFEE0, 
		CASE WHEN x.TAR_TYPE = 0 THEN SUM(x.[TOTAL FOR DEPOSIT]) ELSE 0 END TOTALFORDEPOSIT0, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.Free) ELSE 0 END Free1, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.Payments) ELSE 0 END Payments1, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.Refunds) ELSE 0 END Refunds1, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.[Parking FEE]) ELSE 0 END ParkingFEE1, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.[PAYBYPHONE CONSUMER FEE]) ELSE 0 END CONSUMERFEE1, 
		CASE WHEN x.TAR_TYPE = 1 THEN SUM(x.[TOTAL FOR DEPOSIT]) ELSE 0 END TOTALFORDEPOSIT1, 
		x.VAT, x.CUR_ISO_CODE, x.DECIMAL_PART, x.VAT_AMOUNT, x.LITL_LITERAL, x.LAN_DESCRIPTION, x.INS_DESCRIPTION, x.GRP_DESCRIPTION, x.INS_CULTURE_LANG,
		TPS.TICKET_PAYMENTS, TPS.WEB_TICKET_PAYMENTS, TPS.SUBTOTAL, TPS.FEE, TPS.TOTAL, TPS.ISO_CODE, x.TAR_TYPE
FROM (
	SELECT 	g.GRP_INS_ID OPE_INS_ID, GRP_ID, g.GRP_INS_ID REGION, i.INS_DESCRIPTION [REGION NAME], g.GRP_SHOW_ID [PAYBYPHONE LOT ID], g.GRP_DESCRIPTION [LOT NAME], 
			0 Free, 0 Payments, 0 Refunds, 0 [Parking FEE], 0 [PAYBYPHONE CONSUMER FEE], 0 [TOTAL FOR DEPOSIT], 
			1+i.INS_PERC_VAT2 VAT, c.CUR_ISO_CODE, POWER(10, c.CUR_MINOR_UNIT) DECIMAL_PART, CAST(ROUND(i.INS_PERC_VAT2*100,2) AS NUMERIC(18,2)) VAT_AMOUNT, ll.LITL_LITERAL, 
			l.LAN_DESCRIPTION, i.INS_DESCRIPTION, g.GRP_DESCRIPTION, i.INS_CULTURE_LANG, 0 TAR_TYPE
	FROM GROUPS g
	INNER JOIN INSTALLATIONS i ON g.GRP_INS_ID = i.INS_ID
	INNER JOIN CURRENCIES c ON i.INS_CUR_ID = c.CUR_ID
	INNER JOIN LITERAL_LANGUAGES ll ON i.INS_SERVICE_VAT_LIT_ID = ll.LITL_LIT_ID
	INNER JOIN LANGUAGES l ON ll.LITL_LAN_ID = l.LAN_ID
	WHERE l.LAN_CULTURE = @Culture

	UNION ALL

	SELECT  o.OPE_INS_ID,
			g.GRP_ID,
			i.INS_ID REGION, 
			i.INS_DESCRIPTION [REGION NAME], 
			g.GRP_SHOW_ID [PAYBYPHONE LOT ID], 
			g.GRP_DESCRIPTION [LOT NAME],
			SUM(CASE WHEN o.OPE_TYPE IN (1,2,3) AND o.OPE_TOTAL_AMOUNT=0 THEN 1 ELSE 0 END) Free,
			SUM(CASE WHEN o.OPE_TYPE IN (1,2) AND o.OPE_TOTAL_AMOUNT>0 THEN 1 ELSE 0 END) Payments,
			SUM(CASE WHEN o.OPE_TYPE IN (3) AND o.OPE_TOTAL_AMOUNT>0 THEN 1 ELSE 0 END) Refunds,
			SUM(CASE WHEN o.OPE_TYPE IN (1,2) THEN (o.OPE_AMOUNT + o.OPE_PARTIAL_VAT1) WHEN o.OPE_TYPE IN (3) THEN -(o.OPE_AMOUNT + o.OPE_PARTIAL_VAT1) ELSE 0 END) [Parking FEE],
			SUM(CASE WHEN o.OPE_TYPE IN (1,2) THEN (o.OPE_PARTIAL_PERC_FEE + o.OPE_PARTIAL_FIXED_FEE) WHEN o.OPE_TYPE IN (3) THEN -(o.OPE_PARTIAL_PERC_FEE + o.OPE_PARTIAL_FIXED_FEE) ELSE 0 END) [PAYBYPHONE CONSUMER FEE],
			SUM(CASE WHEN o.OPE_TYPE IN (1,2) THEN (o.OPE_AMOUNT + o.OPE_PARTIAL_VAT1 + o.OPE_PARTIAL_PERC_FEE + o.OPE_PARTIAL_FIXED_FEE) WHEN o.OPE_TYPE IN (3) THEN -(o.OPE_PARTIAL_PERC_FEE + o.OPE_PARTIAL_FIXED_FEE + o.OPE_PARTIAL_PERC_FEE + o.OPE_PARTIAL_FIXED_FEE) ELSE 0  END) [TOTAL FOR DEPOSIT],
			1+i.INS_PERC_VAT2 VAT,
			c.CUR_ISO_CODE,
			POWER(10, c.CUR_MINOR_UNIT) DECIMAL_PART,
			CAST(ROUND(i.INS_PERC_VAT2*100,2) AS NUMERIC(18,2)) VAT_AMOUNT,		
			ll.LITL_LITERAL,
			l.LAN_DESCRIPTION,
			i.INS_DESCRIPTION,
			g.GRP_DESCRIPTION,
			i.INS_CULTURE_LANG,
			t.TAR_TYPE
	FROM HIS_OPERATIONS o 
	INNER JOIN GROUPS g ON o.OPE_GRP_ID = g.GRP_ID
	INNER JOIN INSTALLATIONS i ON o.OPE_INS_ID = i.INS_ID
	INNER JOIN CURRENCIES c ON i.INS_CUR_ID = c.CUR_ID
	INNER JOIN LITERAL_LANGUAGES ll ON i.INS_SERVICE_VAT_LIT_ID = ll.LITL_LIT_ID
	INNER JOIN LANGUAGES l ON ll.LITL_LAN_ID = l.LAN_ID
	INNER JOIN TARIFFS t ON o.OPE_TAR_ID = t.TAR_ID
	WHERE o.OPE_UTC_DATE >= @DateIniUTC AND
		o.OPE_UTC_DATE <= @DateEndUTC AND
		o.OPE_GRP_ID = g.GRP_ID AND
		o.OPE_INS_ID = i.INS_ID
		AND l.LAN_CULTURE = @Culture
	GROUP BY i.INS_ID, i.INS_DESCRIPTION, g.GRP_SHOW_ID, g.GRP_DESCRIPTION, o.OPE_INS_ID, g.GRP_ID, i.INS_PERC_VAT2, c.CUR_ISO_CODE, c.CUR_MINOR_UNIT, ll.LITL_LITERAL, l.LAN_DESCRIPTION, i.INS_CULTURE_LANG, t.TAR_TYPE
) x
LEFT JOIN (
	SELECT INS_STANDARD_CITY_ID, INS_ID, SUM(TICKET_PAYMENTS) TICKET_PAYMENTS, SUM(WEB_TICKET_PAYMENTS) WEB_TICKET_PAYMENTS, SUM(SUBTOTAL) SUBTOTAL, SUM(FEE) FEE, SUM(TOTAL) TOTAL, ISO_CODE, DECIMAL_PART
	FROM (
		SELECT INS_STANDARD_CITY_ID, INS_ID, COUNT(*) TICKET_PAYMENTS, 0 WEB_TICKET_PAYMENTS, SUM(SUBTOTAL) SUBTOTAL, SUM(FEE) FEE, SUM(TOTAL) TOTAL, ISO_CODE, DECIMAL_PART
		FROM (
			SELECT [INS_STANDARD_CITY_ID], TIPA_INS_ID INS_ID
				,ABS([TIPA_TOTAL_AMOUNT]-([TIPA_PARTIAL_PERC_FEE]+[TIPA_PARTIAL_FIXED_FEE])) SUBTOTAL
				,ABS([TIPA_PARTIAL_PERC_FEE]+[TIPA_PARTIAL_FIXED_FEE]) FEE
				,ABS([TIPA_TOTAL_AMOUNT]) TOTAL
				,[OPE_AMOUNT_CUR_ISO_CODE] ISO_CODE
				,POWER(10, c.CUR_MINOR_UNIT) DECIMAL_PART
			FROM [dbo].[VW_TICKET_PAYMENTS] p
			INNER JOIN CURRENCIES c
			ON p.TIPA_AMOUNT_CUR_ID = c.CUR_ID
			WHERE TIPA_UTC_DATE >= @DateIniUTC AND TIPA_UTC_DATE <= @DateEndUTC
		) X
		GROUP BY INS_STANDARD_CITY_ID, ISO_CODE, DECIMAL_PART, INS_ID

		UNION ALL

		SELECT INS_STANDARD_CITY_ID, INS_ID, 0 TICKET_PAYMENTS, COUNT(*) WEB_TICKET_PAYMENTS, SUM(SUBTOTAL) SUBTOTAL, SUM(FEE) FEE, SUM(TOTAL) TOTAL, ISO_CODE, DECIMAL_PART
		FROM (
			SELECT I.INS_STANDARD_CITY_ID, INS_ID
				,ABS(TIPANU_AMOUNT-(TIPANU_PARTIAL_PERC_FEE+TIPANU_FIXED_FEE)) SUBTOTAL
				,ABS(TIPANU_PARTIAL_PERC_FEE+TIPANU_FIXED_FEE) FEE
				,ABS(TIPANU_TOTAL_AMOUNT) TOTAL
				,C.CUR_ISO_CODE ISO_CODE
				,POWER(10, c.CUR_MINOR_UNIT) DECIMAL_PART
			FROM TICKET_PAYMENTS_NON_USERS P
			INNER JOIN INSTALLATIONS I
			ON P.TIPANU_INS_ID = I.INS_ID
			INNER JOIN CURRENCIES C
			ON P.TIPANU_AMOUNT_CUR_ID = C.CUR_ID
			WHERE TIPANU_UTC_DATE >= @DateIniUTC AND TIPANU_UTC_DATE <= @DateEndUTC
		) X
		GROUP BY INS_STANDARD_CITY_ID, ISO_CODE, DECIMAL_PART, INS_ID
	) X
	GROUP BY INS_STANDARD_CITY_ID, ISO_CODE, INS_ID, DECIMAL_PART
) TPS
ON x.OPE_INS_ID = TPS.INS_ID
GROUP BY x.OPE_INS_ID, x.GRP_ID, x.REGION, x.[REGION NAME], x.[PAYBYPHONE LOT ID], x.[LOT NAME], 
		x.VAT, x.CUR_ISO_CODE, x.DECIMAL_PART, x.VAT_AMOUNT, x.LITL_LITERAL, 
		x.LAN_DESCRIPTION, x.INS_DESCRIPTION, x.GRP_DESCRIPTION, x.INS_CULTURE_LANG,
		TPS.TICKET_PAYMENTS, TPS.WEB_TICKET_PAYMENTS, TPS.SUBTOTAL, TPS.FEE, TPS.TOTAL, TPS.ISO_CODE, x.TAR_TYPE
END

GO


