CREATE TABLE [dbo].[USERS_WARNINGS](
	[UWA_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[UWA_USER_ID] [numeric](18, 0) NOT NULL,
	[UWA_URL_IMAGE] [varchar](512) NULL,
	[UWA_TITLE] [varchar](512) NULL,
	[UWA_TEXT1] [varchar](512) NULL,
	[UWA_TEXT2] [varchar](512) NULL,
	[UWA_BUTTON1_TEXT] [varchar](512) NULL,
	[UWA_BUTTON1_FUNCTION] [varchar](512) NULL,
	[UWA_BUTTON2_TEXT] [varchar](512) NULL,
	[UWA_STATUS] [int] NOT NULL,
	[UWA_TYPE_PUSH] [int] NOT NULL,
	[UWA_TYPE_LOGIN] [int] NOT NULL,
	[UWA_TYPE_PARK] [int] NOT NULL,
	[UWA_TYPE_UNPARK] [int] NOT NULL,
	[UWA_TYPE_FINE] [int] NOT NULL,
	[UWA_UNO_ID] [numeric](18, 0) NULL,
	[UWA_STARTDATETIME] [datetime] NULL,
 CONSTRAINT [PK_USER_WARNINGS] PRIMARY KEY CLUSTERED 
(
	[UWA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_STATUS]  DEFAULT ((0)) FOR [UWA_STATUS]
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_TYPE_PUSH]  DEFAULT ((0)) FOR [UWA_TYPE_PUSH]
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_TYPE_LOGIN]  DEFAULT ((0)) FOR [UWA_TYPE_LOGIN]
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_TYPE_PARK]  DEFAULT ((0)) FOR [UWA_TYPE_PARK]
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_TYPE_UNPARK]  DEFAULT ((0)) FOR [UWA_TYPE_UNPARK]
GO

ALTER TABLE [dbo].[USERS_WARNINGS] ADD  CONSTRAINT [DF_USERS_WARNINGS_UWA_TYPE_FINE]  DEFAULT ((0)) FOR [UWA_TYPE_FINE]
GO

ALTER TABLE [dbo].[USERS_WARNINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_NOTIFICATIONS_USER_WARNINGS] FOREIGN KEY([UWA_UNO_ID])
REFERENCES [dbo].[USERS_NOTIFICATIONS] ([UNO_ID])
GO

ALTER TABLE [dbo].[USERS_WARNINGS] CHECK CONSTRAINT [FK_USER_NOTIFICATIONS_USER_WARNINGS]
GO

ALTER TABLE [dbo].[USERS_WARNINGS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_WARNINGS_USERS] FOREIGN KEY([UWA_USER_ID])
REFERENCES [dbo].[USERS] ([USR_ID])
GO

ALTER TABLE [dbo].[USERS_WARNINGS] CHECK CONSTRAINT [FK_USERS_WARNINGS_USERS]
GO


