/****** Object:  View [dbo].[VW_TICKET_PAYMENTS_NON_USER]    Script Date: 19/02/2019 9:27:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_TICKET_PAYMENTS_NON_USER]
AS
SELECT TIPANU_ID,I.INS_DESCRIPTION,TIPANU_DATE,TIPANU_PLATE_STRING,TIPANU_TICKET_NUMBER,
CONCAT(CAST(ROUND((CAST(TIPANU_AMOUNT AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) SUBTOTAL,
CONCAT(CAST(ROUND((CAST(TIPANU_PARTIAL_VAT1 AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) VAT,
CONCAT(CAST(ROUND((CAST(TIPANU_PERC_FEE AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) FEE,
CONCAT(CAST(ROUND((CAST(TIPANU_FINAL_AMOUNT AS DECIMAL(10,2))/100),2) AS DECIMAL(10,2)),' ',C.CUR_ISO_CODE) FINAL_AMOUNT, I.INS_STANDARD_CITY_ID,
TIPANU_AMOUNT,
TIPANU_PARTIAL_VAT1,
TIPANU_PERC_FEE,
TIPANU_FINAL_AMOUNT,
C.CUR_ID, 
I.INS_ID
FROM TICKET_PAYMENTS_NON_USERS P
INNER JOIN INSTALLATIONS I
ON P.TIPANU_INS_ID = I.INS_ID
INNER JOIN CURRENCIES C
ON P.TIPANU_AMOUNT_CUR_ID = C.CUR_ID
