/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INSTALLATIONS ADD
	INS_SERVICE_FEE_PLUS_VAT_LIT_ID numeric(18, 0) NULL
GO
DECLARE @v sql_variant 
SET @v = N'Service Fee Plus VAT Literal id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'INSTALLATIONS', N'COLUMN', N'INS_SERVICE_FEE_PLUS_VAT_LIT_ID'
GO
ALTER TABLE dbo.INSTALLATIONS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


UPDATE INSTALLATIONS
SET INS_SERVICE_FEE_PLUS_VAT_LIT_ID = CASE INS_SHORTDESC WHEN 'MAD' THEN 301763 ELSE 83 END,
	INS_SERVICE_FEE_LIT_ID = 72
GO