SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET XACT_ABORT ON
GO


BEGIN TRANSACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[INSTALLATIONS] ADD [INS_SERVICE_FINE_LIT_ID] [numeric](18,0) NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[INSTALLATIONS] ADD [INS_SERVICE_FINE_MAX_DATE_LIT_ID] [numeric](18,0) NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[INSTALLATIONS] WITH CHECK ADD CONSTRAINT [FK_INSTALLATIONS_LITERALS_FINE_MAX_DATE] FOREIGN KEY
(
	[INS_SERVICE_FINE_MAX_DATE_LIT_ID]
)
REFERENCES [dbo].[LITERALS]
(
	[LIT_ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[INSTALLATIONS] WITH CHECK ADD CONSTRAINT [FK_INSTALLATIONS_LITERALS_SERVICE_FINE] FOREIGN KEY
(
	[INS_SERVICE_FINE_LIT_ID]
)
REFERENCES [dbo].[LITERALS]
(
	[LIT_ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Service Fine Max Payment DateTime literal id', @level0type = 'SCHEMA', @level0name = N'dbo', @level1type = 'TABLE', @level1name = N'INSTALLATIONS', @level2type = 'COLUMN', @level2name = N'INS_SERVICE_FINE_MAX_DATE_LIT_ID'
GO

EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = N'Service Fine literal id', @level0type = 'SCHEMA', @level0name = N'dbo', @level1type = 'TABLE', @level1name = N'INSTALLATIONS', @level2type = 'COLUMN', @level2name = N'INS_SERVICE_FINE_LIT_ID'
GO


COMMIT TRANSACTION
GO
