/****** Object:  View [dbo].[ALL_CURR_OPERATIONS_EXT]    Script Date: 12/03/2019 13:24:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO












ALTER VIEW [dbo].[ALL_CURR_OPERATIONS_EXT]
AS
SELECT        CASE ISNULL(TAR_TYPE, 0) WHEN 1 THEN 19 ELSE OPE_TYPE END AS OPE_TYPE, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, OPE_DATE, OPE_UTC_DATE, OPE_INIDATE, OPE_ENDDATE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_AMOUNT ELSE - OPE_AMOUNT END AS int) OPE_AMOUNT, 
						  CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
					  ELSE -ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
				 END AS int) OPE_REAL_AMOUNT,
						 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_FINAL_AMOUNT ELSE - OPE_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPE_CHANGE_APPLIED, USER_PLATES.USRP_ID, USER_PLATES.USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
                         OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                         CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                         OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, 
                         OPE_ENDDATE_UTC_OFFSET, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                         CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPERATIONS.OPE_EXTERNAL_ID1, OPERATIONS.OPE_EXTERNAL_ID2, OPERATIONS.OPE_EXTERNAL_ID3, 
				OPE_CONFIRMED_IN_WS1, OPE_CONFIRMED_IN_WS2, OPE_CONFIRMED_IN_WS3,
				OPE_CONFIRMATION_TIME_IN_WS1, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPE_CONFIRMATION_TIME_IN_WS2, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPE_CONFIRMATION_TIME_IN_WS3, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
				OPE_PERC_VAT1, OPE_PERC_VAT2, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_VAT1 ELSE -OPE_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				OPE_PERC_FEE, OPE_PERC_FEE_TOPPED, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_PERC_FEE ELSE -OPE_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				OPE_FIXED_FEE, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_FIXED_FEE ELSE -OPE_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				ISNULL(OPE_PERC_BONUS, 0) OPE_PERC_BONUS, CAST ( ISNULL(OPE_PARTIAL_BONUS_FEE, 0) AS int) OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN OPE_TYPE = 3 THEN ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) ELSE -ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE,
					CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN OPE_TIME_BALANCE_USED 
					  ELSE -OPE_TIME_BALANCE_USED 
				 END AS int) OPE_TIME_BALANCE_USED, OPE_TIME_BALANCE_BEFORE, OPE_POSTPAY, OPE_SHOPKEEPER_OP, OPE_SHOPKEEPER_AMOUNT, OPE_SHOPKEEPER_PROFIT,
				 INSTALLATIONS.INS_STANDARD_CITY_ID,
				 UP2.USRP_PLATE USRP_PLATE2, UP3.USRP_PLATE USRP_PLATE3, UP4.USRP_PLATE USRP_PLATE4, UP5.USRP_PLATE USRP_PLATE5, 
				 UP6.USRP_PLATE USRP_PLATE6, UP7.USRP_PLATE USRP_PLATE7, UP8.USRP_PLATE USRP_PLATE8, UP9.USRP_PLATE USRP_PLATE9, UP10.USRP_PLATE USRP_PLATE10,
				 OPE_PERMIT_AUTO_RENEW, OPE_PERMIT_EXPIRATION_TIME,
				 NULL AS OPE_TRANS_STATUS, NULL AS OPE_REFUND_AMOUNT
FROM            dbo.OPERATIONS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.OPERATIONS.OPE_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.OPERATIONS.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.OPERATIONS.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON OPE_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS ON OPE_GRP_ID = GRP_ID LEFT OUTER JOIN
                         dbo.TARIFFS ON OPE_TAR_ID = TAR_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP2 ON dbo.OPERATIONS.OPE_PLATE2_USRP_ID = UP2.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP3 ON dbo.OPERATIONS.OPE_PLATE3_USRP_ID = UP3.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP4 ON dbo.OPERATIONS.OPE_PLATE4_USRP_ID = UP4.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP5 ON dbo.OPERATIONS.OPE_PLATE5_USRP_ID = UP5.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP6 ON dbo.OPERATIONS.OPE_PLATE6_USRP_ID = UP6.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP7 ON dbo.OPERATIONS.OPE_PLATE7_USRP_ID = UP7.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP8 ON dbo.OPERATIONS.OPE_PLATE8_USRP_ID = UP8.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP9 ON dbo.OPERATIONS.OPE_PLATE9_USRP_ID = UP9.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP10 ON dbo.OPERATIONS.OPE_PLATE10_USRP_ID = UP10.USRP_ID
						 , INSTALLATIONS
WHERE        OPE_INS_ID = INS_ID
UNION ALL
SELECT        4 OPE_TYPE, TIPA_USR_ID, TIPA_MOSE_OS, TIPA_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TIPA_DATE, TIPA_UTC_DATE, TIPA_DATE, NULL, - TIPA_AMOUNT TIPA_AMOUNT,-TIPA_AMOUNT, NULL, TIPA_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - TIPA_FINAL_AMOUNT, TIPA_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, TIPA_CHANGE_APPLIED, USRP_ID, 
                         TIPA_PLATE_STRING, TIPA_TICKET_NUMBER, TIPA_TICKET_DATA, NULL, NULL, GRP_ID, NULL, NULL, TIPA_SUSCRIPTION_TYPE, TIPA_BALANCE_BEFORE, TIPA_INSERTION_UTC_DATE, TIPA_CUSPMR_ID, 
                         TIPA_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, 
                         OPEDIS_AMOUNT_CUR_ID, CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         TIPA_DATE_UTC_OFFSET, NULL, NULL, CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, CUR3.CUR_NAME, CUR4.CUR_NAME, 
                         CUR5.CUR_NAME, NULL, NULL, NULL, TIPA_CONFIRMED_IN_WS,NULL,NULL,
TIPA_CONFIRMATION_TIME_IN_WS, TIPA_QUEUE_LENGTH_BEFORE_CONFIRM_WS, NULL,NULL,NULL,NULL,
TIPA_LATITUDE, TIPA_LONGITUDE, TIPA_ID,TIPA_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 TIPA_PERC_VAT1, TIPA_PERC_VAT2, - TIPA_PARTIAL_VAT1,
						 TIPA_PERC_FEE, TIPA_PERC_FEE_TOPPED, - TIPA_PARTIAL_PERC_FEE,
						 TIPA_FIXED_FEE, - TIPA_PARTIAL_FIXED_FEE,
						 0, 0,
						 -ISNULL(TIPA_TOTAL_AMOUNT, TIPA_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 INSTALLATIONS.INS_STANDARD_CITY_ID,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.TICKET_PAYMENTS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.TICKET_PAYMENTS.TIPA_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON TIPA_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON TIPA_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.TICKET_PAYMENTS.TIPA_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.TICKET_PAYMENTS.TIPA_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON TIPA_USR_ID = USR_ID LEFT OUTER JOIN
						 dbo.GROUPS ON TIPA_GRP_ID = GRP_ID,
						 INSTALLATIONS 
WHERE        TIPA_INS_ID = INS_ID
UNION ALL
SELECT        5 OPE_TYPE, CUSPMR_USR_ID, CUSPMR_MOSE_OS, NULL, NULL, NULL, CUSPMR_DATE, CUSPMR_UTC_DATE, CUSPMR_DATE, NULL, CUSPMR_AMOUNT,CUSPMR_AMOUNT, NULL, CUSPMR_CUR_ID, 
                         CUR_ISO_CODE, NULL, CUSPMR_CUR_ID, CUR_ISO_CODE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CUSPMR_SUSCRIPTION_TYPE, CUSPMR_BALANCE_BEFORE, 
                         CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CUSPMR_OP_REFERENCE, 
                         CUSPMR_TRANSACTION_ID, CUSPMR_AUTH_CODE, CUSPMR_CARD_HASH, CUSPMR_CARD_REFERENCE, CUSPMR_CARD_SCHEME, CUSPMR_MASKED_CARD_NUMBER, CUSPMR_CARD_EXPIRATION_DATE,
                          CUSPMR_DATE_UTC_OFFSET, NULL, NULL, NULL, NULL, USR_USERNAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,NULL,CUSPMR_LATITUDE, CUSPMR_LONGITUDE, CUSPMR_ID,CUSPMR_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						  CUSPMR_PERC_VAT1, CUSPMR_PERC_VAT2, CUSPMR_PARTIAL_VAT1,
						  CUSPMR_PERC_FEE, CUSPMR_PERC_FEE_TOPPED, CUSPMR_PARTIAL_PERC_FEE,
						  CUSPMR_FIXED_FEE, CUSPMR_PARTIAL_FIXED_FEE,
						  0, 0,
						  ISNULL(CUSPMR_TOTAL_AMOUNT_CHARGED, CUSPMR_AMOUNT),
						  CUSPMR_TYPE, CUSPMR_PAGATELIA_NEW_BALANCE OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						  NULL,
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 CUSPMR_TRANS_STATUS, CASE WHEN CUSPMR_TRANS_STATUS = 10 AND ISNULL(CUSPMR_REFUND_AMOUNT,0) = 0 THEN CUSPMR_TOTAL_AMOUNT_CHARGED ELSE ISNULL(CUSPMR_REFUND_AMOUNT,0) END
FROM            dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES INNER JOIN
                         dbo.USERS ON CUSPMR_USR_ID = USR_ID, dbo.CURRENCIES
WHERE        CUSPMR_CUR_ID = CUR_ID AND (CUSPMR_SUSCRIPTION_TYPE = 1 OR
                         CUSPMR_SUSCRIPTION_TYPE IS NULL) AND (CUSPMR_TRANS_STATUS IN (1, 2, 3, 4, 8, 9, 10) OR CUSPMR_RCOUP_ID IS NOT NULL OR CUSPMR_TYPE IN (3,4,6))
UNION ALL
SELECT        6 OPE_TYPE, SECH_USR_ID, SECH_MOSE_OS, NULL, NULL, NULL, SECH_DATE, SECH_UTC_DATE, SECH_DATE, NULL, - SECH_AMOUNT,-SECH_AMOUNT, NULL, SECH_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - SECH_FINAL_AMOUNT, SECH_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         SECH_CHANGE_APPLIED, NULL, NULL, NULL, NULL, SECH_SECHT_ID, NULL, NULL, NULL, NULL, SECH_SUSCRIPTION_TYPE, SECH_BALANCE_BEFORE, SECH_INSERTION_UTC_DATE, 
                         SECH_CUSPMR_ID, NULL, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, 
                         CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         SECH_DATE_UTC_OFFSET, NULL, NULL, CUSPMR_DATE_UTC_OFFSET, NULL, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, CUR3.CUR_NAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,
                         SECH_ID,SECH_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 SECH_PERC_VAT1, SECH_PERC_VAT2, - SECH_PARTIAL_VAT1,
						 SECH_PERC_FEE, SECH_PERC_FEE_TOPPED, - SECH_PARTIAL_PERC_FEE,
						 SECH_FIXED_FEE, - SECH_PARTIAL_FIXED_FEE,
						 0, 0,
						 - ISNULL(SECH_TOTAL_AMOUNT, SECH_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.SERVICE_CHARGES INNER JOIN
                         dbo.CURRENCIES CUR1 ON SECH_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON SECH_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.SERVICE_CHARGES.SECH_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID INNER JOIN
                         dbo.USERS ON SECH_USR_ID = USR_ID
UNION ALL
SELECT        7 OPE_TYPE, OPEDIS_USR_ID, OPEDIS_MOSE_OS, NULL, NULL, NULL, OPEDIS_DATE, OPEDIS_UTC_DATE, OPEDIS_DATE, NULL, OPEDIS_AMOUNT,OPEDIS_AMOUNT, NULL, OPEDIS_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, OPEDIS_SUSCRIPTION_TYPE, OPEDIS_BALANCE_BEFORE, 
                         OPEDIS_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL 
                         CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL 
                         CUSPMR_CARD_EXPIRATION_DATE, OPEDIS_DATE_UTC_OFFSET, NULL, NULL, NULL, NULL, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,
                         OPEDIS_LATITUDE, OPEDIS_LONGITUDE, OPEDIS_ID,OPEDIS_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 OPEDIS_PERC_VAT1, OPEDIS_PERC_VAT2, OPEDIS_PARTIAL_VAT1,
						 OPEDIS_PERC_FEE, OPEDIS_PERC_FEE_TOPPED, OPEDIS_PARTIAL_PERC_FEE,
						 OPEDIS_FIXED_FEE, OPEDIS_PARTIAL_FIXED_FEE,
						 0, 0,
						 ISNULL(OPEDIS_TOTAL_AMOUNT, OPEDIS_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.OPERATIONS_DISCOUNTS INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPEDIS_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPEDIS_BALANCE_CUR_ID = CUR2.CUR_ID INNER JOIN
                         dbo.USERS ON OPEDIS_USR_ID = USR_ID

UNION ALL
SELECT        OPEOFF_TYPE, OPEOFF_USR_ID, OPEOFF_MOSE_OS, OPEOFF_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_NOTIFY_ENTRY_DATE ELSE OPEOFF_PAYMENT_DATE END, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_UTC_NOTIFY_ENTRY_DATE ELSE OPEOFF_UTC_PAYMENT_DATE END, 
				OPEOFF_ENTRY_DATE, OPEOFF_END_DATE, 
                CAST(-OPEOFF_AMOUNT AS int),CAST(-OPEOFF_AMOUNT AS int), OPEOFF_TIME, OPEOFF_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                CAST(-OPEOFF_FINAL_AMOUNT AS int), OPEOFF_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                OPEOFF_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, NULL, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, NULL, 
                OPEOFF_SUSCRIPTION_TYPE, OPEOFF_BALANCE_BEFORE, OPEOFF_INSERTION_UTC_DATE, OPEOFF_CUSPMR_ID, OPEOFF_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_NOTIFY_ENTRY_DATE_UTC_OFFSET ELSE OPEOFF_PAYMENT_DATE_UTC_OFFSET END,
				OPEOFF_ENTRY_DATE_UTC_OFFSET, OPEOFF_END_DATE_UTC_OFFSET, 
				CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPEOFF_EXTERNAL_ID1, OPEOFF_EXTERNAL_ID2, OPEOFF_EXTERNAL_ID3, 
				OPEOFF_CONFIRMED_IN_WS1, OPEOFF_CONFIRMED_IN_WS2, OPEOFF_CONFIRMED_IN_WS3,
				OPEOFF_CONFIRMATION_TIME_IN_WS1, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPEOFF_CONFIRMATION_TIME_IN_WS2, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPEOFF_CONFIRMATION_TIME_IN_WS3, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPEOFF_LATITUDE, OPEOFF_LONGITUDE, OPEOFF_ID, OPEOFF_APP_VERSION,
				OPEOFF_ENTRY_DATE, OPEOFF_NOTIFY_ENTRY_DATE, OPEOFF_PAYMENT_DATE, OPEOFF_END_DATE, OPEOFF_EXIT_LIMIT_DATE, OPEOFF_EXIT_DATE,
				OPEOFF_UTC_ENTRY_DATE, OPEOFF_UTC_NOTIFY_ENTRY_DATE, OPEOFF_UTC_PAYMENT_DATE, OPEOFF_UTC_END_DATE, OPEOFF_UTC_EXIT_LIMIT_DATE, OPEOFF_UTC_EXIT_DATE,
				OPEOFF_LOGICAL_ID, OPEOFF_TARIFF, OPEOFF_GATE, OPEOFF_SPACE_DESCRIPTION,			
				OPEOFF_PERC_VAT1, OPEOFF_PERC_VAT2, -OPEOFF_PARTIAL_VAT1,
				OPEOFF_PERC_FEE, OPEOFF_PERC_FEE_TOPPED, -OPEOFF_PARTIAL_PERC_FEE,
				OPEOFF_FIXED_FEE, -OPEOFF_PARTIAL_FIXED_FEE,
				0,0,
				-ISNULL(OPEOFF_TOTAL_AMOUNT, OPEOFF_AMOUNT) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
				INSTALLATIONS.INS_STANDARD_CITY_ID,
				NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.OPERATIONS_OFFSTREET LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.OPERATIONS_OFFSTREET.OPEOFF_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPEOFF_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPEOFF_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.OPERATIONS_OFFSTREET.OPEOFF_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.OPERATIONS_OFFSTREET.OPEOFF_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON OPEOFF_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS ON OPEOFF_GRP_ID = GRP_ID, INSTALLATIONS
WHERE        OPEOFF_INS_ID = INS_ID

UNION ALL

SELECT        14, BAT_SRC_USR_ID, BAT_MOSE_OS, NULL, NULL, NULL, BAT_DATE, BAT_UTC_DATE, BAT_DATE, NULL, 
                         -BAT_AMOUNT, -BAT_AMOUNT,NULL, BAT_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         -BAT_AMOUNT, BAT_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         BAT_CHANGE_APPLIED, NULL, NULL, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL, NULL, NULL GRP_DESCRIPTION, NULL, 
                         1 OPE_SUSCRIPTION_TYPE, BAT_SRC_BALANCE_BEFORE, BAT_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, NULL, NULL, 
                         NULL, NULL, NULL, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR1.CUR_NAME OPE_BALANCE_CUR_NAME, NULL, NULL, 
                         NULL OPEDIS_BALANCE_CUR_NAME, NULL, NULL, NULL, 
						 NULL, NULL, NULL,
						 NULL, NULL, NULL, NULL, NULL , NULL,
						 NULL, NULL, BAT_ID, BAT_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 NULL, NULL, NULL OPE_PARTIAL_VAT1,
						 NULL, NULL, NULL OPE_PARTIAL_PERC_FEE,
						 NULL, NULL OPE_PARTIAL_FIXED_FEE,
						 NULL OPE_PERC_BONUS, NULL OPE_PARTIAL_BONUS_FEE,
						 -BAT_AMOUNT OPE_TOTAL_AMOUNT,
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY,
						 BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_COLLECTED_AMOUNT, BAT_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.BALANCE_TRANSFERS LEFT OUTER JOIN                         
                         dbo.CURRENCIES CUR1 ON BAT_AMOUNT_CUR_ID = CUR1.CUR_ID LEFT OUTER JOIN                                                  
                         dbo.USERS ON BAT_SRC_USR_ID = USR_ID

UNION ALL

SELECT        15, BAT_DST_USR_ID, BAT_MOSE_OS, NULL, NULL, NULL, BAT_DATE, BAT_UTC_DATE, BAT_DATE, NULL, 
                         BAT_DST_AMOUNT, BAT_DST_AMOUNT,NULL, BAT_DST_BALANCE_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         BAT_DST_AMOUNT, BAT_DST_BALANCE_CUR_ID, CUR1.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         BAT_CHANGE_APPLIED, NULL, NULL, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL, NULL, NULL GRP_DESCRIPTION, NULL, 
                         1 OPE_SUSCRIPTION_TYPE, BAT_DST_BALANCE_BEFORE, BAT_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, NULL, NULL, 
                         NULL, NULL, NULL, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR1.CUR_NAME OPE_BALANCE_CUR_NAME, NULL, NULL, 
                         NULL OPEDIS_BALANCE_CUR_NAME, NULL, NULL, NULL, 
						 NULL, NULL, NULL,
						 NULL, NULL, NULL, NULL, NULL , NULL,
						 NULL, NULL, BAT_ID, BAT_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 NULL, NULL, NULL OPE_PARTIAL_VAT1,
						 NULL, NULL, NULL OPE_PARTIAL_PERC_FEE,
						 NULL, NULL OPE_PARTIAL_FIXED_FEE,
						 NULL OPE_PERC_BONUS, NULL OPE_PARTIAL_BONUS_FEE,
						 BAT_AMOUNT OPE_TOTAL_AMOUNT,
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY,
						 BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_COLLECTED_AMOUNT, BAT_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.BALANCE_TRANSFERS LEFT OUTER JOIN                                                  
                         dbo.CURRENCIES CUR1 ON BAT_DST_BALANCE_CUR_ID = CUR1.CUR_ID LEFT OUTER JOIN                                                  
                         dbo.USERS ON BAT_DST_USR_ID = USR_ID


UNION ALL

SELECT        TOLM_TYPE, TOLM_USR_ID, TOLM_MOSE_OS, TOLM_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TOLM_DATE, TOLM_UTC_DATE, TOLM_DATE, NULL, 
                         CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_AMOUNT ELSE - TOLM_AMOUNT END AS int) OPE_AMOUNT, 
						 CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_AMOUNT ELSE - TOLM_AMOUNT END AS int) OPE_REAL_AMOUNT, NULL, TOLM_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_FINAL_AMOUNT ELSE - TOLM_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, TOLM_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         TOLM_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL/*TOL_ID*/, NULL, NULL, TOLM_TOL_TARIFF, 
                         TOLM_SUSCRIPTION_TYPE, TOLM_BALANCE_BEFORE, TOLM_INSERTION_UTC_DATE, TOLM_CUSPMR_ID, NULL, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, 
                         NULL OPEDIS_AMOUNT_CUR_ISO_CODE, NULL, NULL, NULL OPEDIS_BALANCE_CUR_ISO_CODE, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, TOLM_DATE_UTC_OFFSET, NULL, 
                         NULL, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, NULL OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, NULL OPEDIS_AMOUNT_CUR_NAME, 
                         NULL OPEDIS_BALANCE_CUR_NAME, TOLM_EXTERNAL_ID, NULL, NULL, 
				NULL, NULL, NULL,
				NULL, NULL,NULL, NULL,NULL, NULL,
				TOLM_LATITUDE, TOLM_LONGITUDE, TOLM_ID,TOLM_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
				TOLM_PERC_VAT1, TOLM_PERC_VAT2, CAST( CASE WHEN TOLM_TYPE = 18 THEN TOLM_PARTIAL_VAT1 ELSE -TOLM_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				TOLM_PERC_FEE, TOLM_PERC_FEE_TOPPED, CAST( CASE WHEN TOLM_TYPE = 18 THEN TOLM_PARTIAL_PERC_FEE ELSE -TOLM_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				TOLM_FIXED_FEE, CAST( CASE WHEN TOLM_TYPE = 2 THEN TOLM_PARTIAL_FIXED_FEE ELSE -TOLM_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				0 OPE_PERC_BONUS, 0 OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN TOLM_TYPE = 18 THEN ISNULL(TOLM_TOTAL_AMOUNT, TOLM_AMOUNT) ELSE -ISNULL(TOLM_TOTAL_AMOUNT, TOLM_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
				INSTALLATIONS.INS_STANDARD_CITY_ID,
				NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.TOLL_MOVEMENTS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.TOLL_MOVEMENTS.TOLM_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON TOLM_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON TOLM_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.TOLL_MOVEMENTS.TOLM_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN                         
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.USERS ON TOLM_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.TOLLS ON TOLM_TOL_ID = TOL_ID, INSTALLATIONS
WHERE        TOLM_INS_ID = INS_ID














GO


ALTER VIEW [dbo].[ALL_OPERATIONS_EXT]
AS
SELECT        CASE ISNULL(TAR_TYPE, 0) WHEN 1 THEN 19 ELSE OPE_TYPE END AS OPE_TYPE, OPE_USR_ID, OPE_MOSE_OS, OPE_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, OPE_DATE, OPE_UTC_DATE, OPE_INIDATE, OPE_ENDDATE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_AMOUNT ELSE - OPE_AMOUNT END AS int) OPE_AMOUNT, 
						  CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
					  ELSE -ISNULL(OPE_REAL_AMOUNT,OPE_AMOUNT) 
				 END AS int) OPE_REAL_AMOUNT,
						 OPE_TIME, OPE_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN OPE_TYPE = 3 THEN OPE_FINAL_AMOUNT ELSE - OPE_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, OPE_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPE_CHANGE_APPLIED, USER_PLATES.USRP_ID, USER_PLATES.USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, TAR_ID, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, TAR_DESCRIPTION, 
                         OPE_SUSCRIPTION_TYPE, OPE_BALANCE_BEFORE, OPE_INSERTION_UTC_DATE, OPE_CUSPMR_ID, OPE_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                         CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                         OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, OPE_DATE_UTC_OFFSET, OPE_INIDATE_UTC_OFFSET, 
                         OPE_ENDDATE_UTC_OFFSET, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                         CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, HIS_OPERATIONS.OPE_EXTERNAL_ID1, HIS_OPERATIONS.OPE_EXTERNAL_ID2, HIS_OPERATIONS.OPE_EXTERNAL_ID3, 
				OPE_CONFIRMED_IN_WS1, OPE_CONFIRMED_IN_WS2, OPE_CONFIRMED_IN_WS3,
				OPE_CONFIRMATION_TIME_IN_WS1, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPE_CONFIRMATION_TIME_IN_WS2, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPE_CONFIRMATION_TIME_IN_WS3, OPE_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPE_LATITUDE, OPE_LONGITUDE, OPE_ID,OPE_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
				OPE_PERC_VAT1, OPE_PERC_VAT2, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_VAT1 ELSE -OPE_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				OPE_PERC_FEE, OPE_PERC_FEE_TOPPED, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_PERC_FEE ELSE -OPE_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				OPE_FIXED_FEE, CAST( CASE WHEN OPE_TYPE = 3 THEN OPE_PARTIAL_FIXED_FEE ELSE -OPE_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				ISNULL(OPE_PERC_BONUS, 0) OPE_PERC_BONUS, CAST ( ISNULL(OPE_PARTIAL_BONUS_FEE, 0) AS int) OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN OPE_TYPE = 3 THEN ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) ELSE -ISNULL(OPE_TOTAL_AMOUNT, OPE_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE,
					CAST( CASE 
					  WHEN OPE_TYPE = 3
						 THEN OPE_TIME_BALANCE_USED 
					  ELSE -OPE_TIME_BALANCE_USED 
				 END AS int) OPE_TIME_BALANCE_USED, OPE_TIME_BALANCE_BEFORE, OPE_POSTPAY, OPE_SHOPKEEPER_OP, OPE_SHOPKEEPER_AMOUNT, OPE_SHOPKEEPER_PROFIT,
				 INSTALLATIONS.INS_STANDARD_CITY_ID,
				 UP2.USRP_PLATE USRP_PLATE2, UP3.USRP_PLATE USRP_PLATE3, UP4.USRP_PLATE USRP_PLATE4, UP5.USRP_PLATE USRP_PLATE5, 
				 UP6.USRP_PLATE USRP_PLATE6, UP7.USRP_PLATE USRP_PLATE7, UP8.USRP_PLATE USRP_PLATE8, UP9.USRP_PLATE USRP_PLATE9, UP10.USRP_PLATE USRP_PLATE10,
				 OPE_PERMIT_AUTO_RENEW, OPE_PERMIT_EXPIRATION_TIME,
				 NULL AS OPE_TRANS_STATUS, NULL AS OPE_REFUND_AMOUNT
FROM            dbo.HIS_OPERATIONS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.HIS_OPERATIONS.OPE_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPE_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPE_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.HIS_OPERATIONS.OPE_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.HIS_OPERATIONS.OPE_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON OPE_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS ON OPE_GRP_ID = GRP_ID LEFT OUTER JOIN
                         dbo.TARIFFS ON OPE_TAR_ID = TAR_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP2 ON dbo.HIS_OPERATIONS.OPE_PLATE2_USRP_ID = UP2.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP3 ON dbo.HIS_OPERATIONS.OPE_PLATE3_USRP_ID = UP3.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP4 ON dbo.HIS_OPERATIONS.OPE_PLATE4_USRP_ID = UP4.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP5 ON dbo.HIS_OPERATIONS.OPE_PLATE5_USRP_ID = UP5.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP6 ON dbo.HIS_OPERATIONS.OPE_PLATE6_USRP_ID = UP6.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP7 ON dbo.HIS_OPERATIONS.OPE_PLATE7_USRP_ID = UP7.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP8 ON dbo.HIS_OPERATIONS.OPE_PLATE8_USRP_ID = UP8.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP9 ON dbo.HIS_OPERATIONS.OPE_PLATE9_USRP_ID = UP9.USRP_ID
						 LEFT OUTER JOIN dbo.USER_PLATES UP10 ON dbo.HIS_OPERATIONS.OPE_PLATE10_USRP_ID = UP10.USRP_ID
						 , INSTALLATIONS
WHERE        OPE_INS_ID = INS_ID
UNION ALL
SELECT        4 OPE_TYPE, TIPA_USR_ID, TIPA_MOSE_OS, TIPA_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TIPA_DATE, TIPA_UTC_DATE, TIPA_DATE, NULL, - TIPA_AMOUNT TIPA_AMOUNT,-TIPA_AMOUNT, NULL, TIPA_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - TIPA_FINAL_AMOUNT, TIPA_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, TIPA_CHANGE_APPLIED, USRP_ID, 
                         TIPA_PLATE_STRING, TIPA_TICKET_NUMBER, TIPA_TICKET_DATA, NULL, NULL, GRP_ID, NULL, NULL, TIPA_SUSCRIPTION_TYPE, TIPA_BALANCE_BEFORE, TIPA_INSERTION_UTC_DATE, TIPA_CUSPMR_ID, 
                         TIPA_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, 
                         OPEDIS_AMOUNT_CUR_ID, CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         TIPA_DATE_UTC_OFFSET, NULL, NULL, CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, CUR3.CUR_NAME, CUR4.CUR_NAME, 
                         CUR5.CUR_NAME, NULL, NULL, NULL, TIPA_CONFIRMED_IN_WS,NULL,NULL,
						 TIPA_CONFIRMATION_TIME_IN_WS, TIPA_QUEUE_LENGTH_BEFORE_CONFIRM_WS, NULL,NULL,NULL,NULL,
						 TIPA_LATITUDE, TIPA_LONGITUDE, TIPA_ID,TIPA_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 TIPA_PERC_VAT1, TIPA_PERC_VAT2, - TIPA_PARTIAL_VAT1,
						 TIPA_PERC_FEE, TIPA_PERC_FEE_TOPPED, - TIPA_PARTIAL_PERC_FEE,
						 TIPA_FIXED_FEE, - TIPA_PARTIAL_FIXED_FEE,
						 0, 0,
						 -ISNULL(TIPA_TOTAL_AMOUNT, TIPA_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 INSTALLATIONS.INS_STANDARD_CITY_ID,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.TICKET_PAYMENTS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.TICKET_PAYMENTS.TIPA_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON TIPA_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON TIPA_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.TICKET_PAYMENTS.TIPA_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.TICKET_PAYMENTS.TIPA_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON TIPA_USR_ID = USR_ID LEFT OUTER JOIN
						 dbo.GROUPS ON TIPA_GRP_ID = GRP_ID,
						 INSTALLATIONS 
WHERE        TIPA_INS_ID = INS_ID
UNION ALL
SELECT        5 OPE_TYPE, CUSPMR_USR_ID, CUSPMR_MOSE_OS, NULL, NULL, NULL, CUSPMR_DATE, CUSPMR_UTC_DATE, CUSPMR_DATE, NULL, CUSPMR_AMOUNT,CUSPMR_AMOUNT, NULL, CUSPMR_CUR_ID, 
                          CUR_ISO_CODE, NULL, CUSPMR_CUR_ID, CUR_ISO_CODE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CUSPMR_SUSCRIPTION_TYPE, CUSPMR_BALANCE_BEFORE, 
                          CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CUSPMR_OP_REFERENCE, 
                          CUSPMR_TRANSACTION_ID, CUSPMR_AUTH_CODE, CUSPMR_CARD_HASH, CUSPMR_CARD_REFERENCE, CUSPMR_CARD_SCHEME, CUSPMR_MASKED_CARD_NUMBER, CUSPMR_CARD_EXPIRATION_DATE,
                          CUSPMR_DATE_UTC_OFFSET, NULL, NULL, NULL, NULL, USR_USERNAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,NULL,CUSPMR_LATITUDE, CUSPMR_LONGITUDE, CUSPMR_ID,CUSPMR_APP_VERSION,
						  NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						  NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						  NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						  CUSPMR_PERC_VAT1, CUSPMR_PERC_VAT2, CUSPMR_PARTIAL_VAT1,
						  CUSPMR_PERC_FEE, CUSPMR_PERC_FEE_TOPPED, CUSPMR_PARTIAL_PERC_FEE,
						  CUSPMR_FIXED_FEE, CUSPMR_PARTIAL_FIXED_FEE,
						  0, 0,
						  ISNULL(CUSPMR_TOTAL_AMOUNT_CHARGED, CUSPMR_AMOUNT),
						  CUSPMR_TYPE OPE_CUSPMR_TYPE, CUSPMR_PAGATELIA_NEW_BALANCE OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						  NULL,
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 CUSPMR_TRANS_STATUS, CASE WHEN CUSPMR_TRANS_STATUS = 10 AND ISNULL(CUSPMR_REFUND_AMOUNT,0) = 0 THEN CUSPMR_TOTAL_AMOUNT_CHARGED ELSE ISNULL(CUSPMR_REFUND_AMOUNT,0) END
FROM            dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES INNER JOIN
                         dbo.USERS ON CUSPMR_USR_ID = USR_ID, dbo.CURRENCIES
WHERE        CUSPMR_CUR_ID = CUR_ID AND (CUSPMR_SUSCRIPTION_TYPE = 1 OR
                         CUSPMR_SUSCRIPTION_TYPE IS NULL) AND (CUSPMR_TRANS_STATUS IN (1, 2, 3, 4, 8, 9, 10) OR CUSPMR_RCOUP_ID IS NOT NULL OR CUSPMR_TYPE IN (3,4,6))

UNION ALL
SELECT        6 OPE_TYPE, SECH_USR_ID, SECH_MOSE_OS, NULL, NULL, NULL, SECH_DATE, SECH_UTC_DATE, SECH_DATE, NULL, - SECH_AMOUNT,-SECH_AMOUNT, NULL, SECH_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, - SECH_FINAL_AMOUNT, SECH_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         SECH_CHANGE_APPLIED, NULL, NULL, NULL, NULL, SECH_SECHT_ID, NULL, NULL, NULL, NULL, SECH_SUSCRIPTION_TYPE, SECH_BALANCE_BEFORE, SECH_INSERTION_UTC_DATE, 
                         SECH_CUSPMR_ID, NULL, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, CUR3.CUR_ISO_CODE, CUSPMR_BALANCE_BEFORE, 
                         CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL 
                         CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
                         SECH_DATE_UTC_OFFSET, NULL, NULL, CUSPMR_DATE_UTC_OFFSET, NULL, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, CUR3.CUR_NAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,
                         SECH_ID,SECH_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 SECH_PERC_VAT1, SECH_PERC_VAT2, - SECH_PARTIAL_VAT1,
						 SECH_PERC_FEE, SECH_PERC_FEE_TOPPED, - SECH_PARTIAL_PERC_FEE,
						 SECH_FIXED_FEE, - SECH_PARTIAL_FIXED_FEE,
						 0, 0,
						 - ISNULL(SECH_TOTAL_AMOUNT, SECH_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.SERVICE_CHARGES INNER JOIN
                         dbo.CURRENCIES CUR1 ON SECH_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON SECH_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.SERVICE_CHARGES.SECH_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID INNER JOIN
                         dbo.USERS ON SECH_USR_ID = USR_ID
UNION ALL
SELECT        7 OPE_TYPE, OPEDIS_USR_ID, OPEDIS_MOSE_OS, NULL, NULL, NULL, OPEDIS_DATE, OPEDIS_UTC_DATE, OPEDIS_DATE, NULL, OPEDIS_AMOUNT,OPEDIS_AMOUNT, NULL, OPEDIS_AMOUNT_CUR_ID, 
                         CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         OPEDIS_CHANGE_APPLIED, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, OPEDIS_SUSCRIPTION_TYPE, OPEDIS_BALANCE_BEFORE, 
                         OPEDIS_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL 
                         CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL 
                         CUSPMR_CARD_EXPIRATION_DATE, OPEDIS_DATE_UTC_OFFSET, NULL, NULL, NULL, NULL, USR_USERNAME, CUR1.CUR_NAME, CUR2.CUR_NAME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,NULL,NULL,
                         OPEDIS_LATITUDE, OPEDIS_LONGITUDE, OPEDIS_ID,OPEDIS_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 OPEDIS_PERC_VAT1, OPEDIS_PERC_VAT2, OPEDIS_PARTIAL_VAT1,
						 OPEDIS_PERC_FEE, OPEDIS_PERC_FEE_TOPPED, OPEDIS_PARTIAL_PERC_FEE,
						 OPEDIS_FIXED_FEE, OPEDIS_PARTIAL_FIXED_FEE,
						 0, 0,
						 ISNULL(OPEDIS_TOTAL_AMOUNT, OPEDIS_AMOUNT),
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.OPERATIONS_DISCOUNTS INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPEDIS_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPEDIS_BALANCE_CUR_ID = CUR2.CUR_ID INNER JOIN
                         dbo.USERS ON OPEDIS_USR_ID = USR_ID

UNION ALL
SELECT        OPEOFF_TYPE, OPEOFF_USR_ID, OPEOFF_MOSE_OS, OPEOFF_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_NOTIFY_ENTRY_DATE ELSE OPEOFF_PAYMENT_DATE END, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_UTC_NOTIFY_ENTRY_DATE ELSE OPEOFF_UTC_PAYMENT_DATE END, 
				OPEOFF_ENTRY_DATE, OPEOFF_END_DATE, 
                CAST(-OPEOFF_AMOUNT AS int),CAST(-OPEOFF_AMOUNT AS int), OPEOFF_TIME, OPEOFF_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                CAST(-OPEOFF_FINAL_AMOUNT AS int), OPEOFF_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                OPEOFF_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, GRP_ID, NULL, ISNULL(GRP_DESCRIPTION2,GRP_DESCRIPTION) GRP_DESCRIPTION, NULL, 
                OPEOFF_SUSCRIPTION_TYPE, OPEOFF_BALANCE_BEFORE, OPEOFF_INSERTION_UTC_DATE, OPEOFF_CUSPMR_ID, OPEOFF_OPEDIS_ID, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, OPEDIS_DATE, OPEDIS_AMOUNT, OPEDIS_AMOUNT_CUR_ID, 
                CUR4.CUR_ISO_CODE OPEDIS_AMOUNT_CUR_ISO_CODE, OPEDIS_FINAL_AMOUNT, OPEDIS_BALANCE_CUR_ID, CUR5.CUR_ISO_CODE OPEDIS_BALANCE_CUR_ISO_CODE, OPEDIS_CHANGE_APPLIED, 
                OPEDIS_BALANCE_BEFORE, OPEDIS_INSERTION_UTC_DATE, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, 
				CASE OPEOFF_TYPE WHEN 8 THEN OPEOFF_NOTIFY_ENTRY_DATE_UTC_OFFSET ELSE OPEOFF_PAYMENT_DATE_UTC_OFFSET END,
				OPEOFF_ENTRY_DATE_UTC_OFFSET, OPEOFF_END_DATE_UTC_OFFSET, 
				CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, OPEDIS_DATE_UTC_OFFSET OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, CUR4.CUR_NAME OPEDIS_AMOUNT_CUR_NAME, 
                CUR5.CUR_NAME OPEDIS_BALANCE_CUR_NAME, OPEOFF_EXTERNAL_ID1, OPEOFF_EXTERNAL_ID2, OPEOFF_EXTERNAL_ID3, 
				OPEOFF_CONFIRMED_IN_WS1, OPEOFF_CONFIRMED_IN_WS2, OPEOFF_CONFIRMED_IN_WS3,
				OPEOFF_CONFIRMATION_TIME_IN_WS1, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS1,OPEOFF_CONFIRMATION_TIME_IN_WS2, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS2,OPEOFF_CONFIRMATION_TIME_IN_WS3, OPEOFF_QUEUE_LENGTH_BEFORE_CONFIRM_WS3,
				OPEOFF_LATITUDE, OPEOFF_LONGITUDE, OPEOFF_ID, OPEOFF_APP_VERSION,
				OPEOFF_ENTRY_DATE, OPEOFF_NOTIFY_ENTRY_DATE, OPEOFF_PAYMENT_DATE, OPEOFF_END_DATE, OPEOFF_EXIT_LIMIT_DATE, OPEOFF_EXIT_DATE,
				OPEOFF_UTC_ENTRY_DATE, OPEOFF_UTC_NOTIFY_ENTRY_DATE, OPEOFF_UTC_PAYMENT_DATE, OPEOFF_UTC_END_DATE, OPEOFF_UTC_EXIT_LIMIT_DATE, OPEOFF_UTC_EXIT_DATE,
				OPEOFF_LOGICAL_ID, OPEOFF_TARIFF, OPEOFF_GATE, OPEOFF_SPACE_DESCRIPTION,
				OPEOFF_PERC_VAT1, OPEOFF_PERC_VAT2, -OPEOFF_PARTIAL_VAT1,
				OPEOFF_PERC_FEE, OPEOFF_PERC_FEE_TOPPED, -OPEOFF_PARTIAL_PERC_FEE,
				OPEOFF_FIXED_FEE, -OPEOFF_PARTIAL_FIXED_FEE,
				0,0,
				-ISNULL(OPEOFF_TOTAL_AMOUNT, OPEOFF_AMOUNT) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
				INSTALLATIONS.INS_STANDARD_CITY_ID,
				NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.OPERATIONS_OFFSTREET LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.OPERATIONS_OFFSTREET.OPEOFF_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON OPEOFF_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON OPEOFF_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.OPERATIONS_OFFSTREET.OPEOFF_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN
                         dbo.OPERATIONS_DISCOUNTS ON dbo.OPERATIONS_OFFSTREET.OPEOFF_OPEDIS_ID = OPERATIONS_DISCOUNTS.OPEDIS_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR4 ON OPEDIS_AMOUNT_CUR_ID = CUR4.CUR_ID LEFT OUTER JOIN
                         dbo.CURRENCIES CUR5 ON OPEDIS_BALANCE_CUR_ID = CUR5.CUR_ID INNER JOIN
                         dbo.USERS ON OPEOFF_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.GROUPS ON OPEOFF_GRP_ID = GRP_ID, INSTALLATIONS
WHERE        OPEOFF_INS_ID = INS_ID

UNION ALL

SELECT        14, BAT_SRC_USR_ID, BAT_MOSE_OS, NULL, NULL, NULL, BAT_DATE, BAT_UTC_DATE, BAT_DATE, NULL, 
                         -BAT_AMOUNT,-BAT_AMOUNT, NULL, BAT_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         -BAT_AMOUNT, BAT_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         BAT_CHANGE_APPLIED, NULL, NULL, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL, NULL, NULL GRP_DESCRIPTION, NULL, 
                         1 OPE_SUSCRIPTION_TYPE, BAT_SRC_BALANCE_BEFORE, BAT_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, NULL, NULL, 
                         NULL, NULL, NULL, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR1.CUR_NAME OPE_BALANCE_CUR_NAME, NULL, NULL, 
                         NULL OPEDIS_BALANCE_CUR_NAME, NULL, NULL, NULL, 
						 NULL, NULL, NULL,
						 NULL, NULL, NULL, NULL, NULL , NULL,
						 NULL, NULL, BAT_ID, BAT_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 NULL, NULL, NULL OPE_PARTIAL_VAT1,
						 NULL, NULL, NULL OPE_PARTIAL_PERC_FEE,
						 NULL, NULL OPE_PARTIAL_FIXED_FEE,
						 NULL OPE_PERC_BONUS, NULL OPE_PARTIAL_BONUS_FEE,
						 -BAT_AMOUNT OPE_TOTAL_AMOUNT,
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY,
						 BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_COLLECTED_AMOUNT, BAT_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.BALANCE_TRANSFERS LEFT OUTER JOIN                         
                         dbo.CURRENCIES CUR1 ON BAT_AMOUNT_CUR_ID = CUR1.CUR_ID LEFT OUTER JOIN                                                  
                         dbo.USERS ON BAT_SRC_USR_ID = USR_ID

UNION ALL

SELECT        15, BAT_DST_USR_ID, BAT_MOSE_OS, NULL, NULL, NULL, BAT_DATE, BAT_UTC_DATE, BAT_DATE, NULL, 
                         BAT_DST_AMOUNT,BAT_DST_AMOUNT, NULL, BAT_DST_BALANCE_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         BAT_DST_AMOUNT, BAT_DST_BALANCE_CUR_ID, CUR1.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         BAT_CHANGE_APPLIED, NULL, NULL, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL, NULL, NULL GRP_DESCRIPTION, NULL, 
                         1 OPE_SUSCRIPTION_TYPE, BAT_DST_BALANCE_BEFORE, BAT_INSERTION_UTC_DATE, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, NULL, NULL, 
                         NULL, NULL, NULL, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR1.CUR_NAME OPE_BALANCE_CUR_NAME, NULL, NULL, 
                         NULL OPEDIS_BALANCE_CUR_NAME, NULL, NULL, NULL, 
						 NULL, NULL, NULL,
						 NULL, NULL, NULL, NULL, NULL , NULL,
						 NULL, NULL, BAT_ID, BAT_APP_VERSION,
						 NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
						 NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
						 NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
						 NULL, NULL, NULL OPE_PARTIAL_VAT1,
						 NULL, NULL, NULL OPE_PARTIAL_PERC_FEE,
						 NULL, NULL OPE_PARTIAL_FIXED_FEE,
						 NULL OPE_PERC_BONUS, NULL OPE_PARTIAL_BONUS_FEE,
						 BAT_AMOUNT OPE_TOTAL_AMOUNT,
						 NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY,
						 BAT_SHOPKEEPER_OP, BAT_SHOPKEEPER_COLLECTED_AMOUNT, BAT_SHOPKEEPER_PROFIT,
						 NULL,
						 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.BALANCE_TRANSFERS LEFT OUTER JOIN                                                  
                         dbo.CURRENCIES CUR1 ON BAT_DST_BALANCE_CUR_ID = CUR1.CUR_ID LEFT OUTER JOIN                                                  
                         dbo.USERS ON BAT_DST_USR_ID = USR_ID

UNION ALL

SELECT        TOLM_TYPE, TOLM_USR_ID, TOLM_MOSE_OS, TOLM_INS_ID, INS_DESCRIPTION, INS_SHORTDESC, TOLM_DATE, TOLM_UTC_DATE, TOLM_DATE, NULL, 
                         CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_AMOUNT ELSE - TOLM_AMOUNT END AS int) OPE_AMOUNT, 
						 CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_AMOUNT ELSE - TOLM_AMOUNT END AS int) OPE_REAL_AMOUNT,NULL, TOLM_AMOUNT_CUR_ID, CUR1.CUR_ISO_CODE OPE_AMOUNT_CUR_ISO_CODE, 
                         CAST(CASE WHEN TOLM_TYPE = 18 THEN TOLM_FINAL_AMOUNT ELSE - TOLM_FINAL_AMOUNT END AS int) OPE_FINAL_AMOUNT, TOLM_BALANCE_CUR_ID, CUR2.CUR_ISO_CODE OPE_BALANCE_CUR_ISO_CODE, 
                         TOLM_CHANGE_APPLIED, USRP_ID, USRP_PLATE, NULL TIPA_TICKET_NUMBER, NULL TIPA_TICKET_DATA, NULL SECH_SECHT_ID, NULL/*TOL_ID*/, NULL, NULL, TOLM_TOL_TARIFF, 
                         TOLM_SUSCRIPTION_TYPE, TOLM_BALANCE_BEFORE, TOLM_INSERTION_UTC_DATE, TOLM_CUSPMR_ID, NULL, CUSPMR_DATE, CUSPMR_AMOUNT, CUSPMR_CUR_ID, 
                         CUR3.CUR_ISO_CODE CUSPMR_AMOUNT_ISO_CODE, CUSPMR_BALANCE_BEFORE, CUSPMR_INSERTION_UTC_DATE, NULL, NULL, NULL, 
                         NULL OPEDIS_AMOUNT_CUR_ISO_CODE, NULL, NULL, NULL OPEDIS_BALANCE_CUR_ISO_CODE, NULL, 
                         NULL, NULL, NULL CUSPMR_OP_REFERENCE, NULL CUSPMR_TRANSACTION_ID, NULL CUSPMR_AUTH_CODE, NULL CUSPMR_CARD_HASH, NULL 
                         CUSPMR_CARD_REFERENCE, NULL CUSPMR_CARD_SCHEME, NULL CUSPMR_MASKED_CARD_NUMBER, NULL CUSPMR_CARD_EXPIRATION_DATE, TOLM_DATE_UTC_OFFSET, NULL, 
                         NULL, CUSPMR_DATE_UTC_OFFSET OPE_CUSPMR_DATE_UTC_OFFSET, NULL OPE_OPEDIS_DATE_UTC_OFFSET, USR_USERNAME, 
                         CUR1.CUR_NAME OPE_AMOUNT_CUR_NAME, CUR2.CUR_NAME OPE_BALANCE_CUR_NAME, CUR3.CUR_NAME CUSPMR_CUR_NAME, NULL OPEDIS_AMOUNT_CUR_NAME, 
                         NULL OPEDIS_BALANCE_CUR_NAME, TOLM_EXTERNAL_ID, NULL, NULL, 
				NULL, NULL, NULL,
				NULL, NULL,NULL, NULL,NULL, NULL,
				TOLM_LATITUDE, TOLM_LONGITUDE, TOLM_ID,TOLM_APP_VERSION,
				NULL OPEOFF_ENTRY_DATE, NULL OPEOFF_NOTIFY_ENTRY_DATE, NULL OPEOFF_PAYMENT_DATE, NULL OPEOFF_END_DATE, NULL OPEOFF_EXIT_LIMIT_DATE, NULL OPEOFF_EXIT_DATE,
				NULL OPEOFF_UTC_ENTRY_DATE, NULL OPEOFF_UTC_NOTIFY_ENTRY_DATE, NULL OPEOFF_UTC_PAYMENT_DATE, NULL OPEOFF_UTC_END_DATE, NULL OPEOFF_UTC_EXIT_LIMIT_DATE, NULL OPEOFF_UTC_EXIT_DATE,
				NULL OPEOFF_LOGICAL_ID, NULL OPEOFF_TARIFF, NULL OPEOFF_GATE, NULL OPEOFF_SPACE_DESCRIPTION,
				TOLM_PERC_VAT1, TOLM_PERC_VAT2, CAST( CASE WHEN TOLM_TYPE = 18 THEN TOLM_PARTIAL_VAT1 ELSE -TOLM_PARTIAL_VAT1 END AS int) OPE_PARTIAL_VAT1,
				TOLM_PERC_FEE, TOLM_PERC_FEE_TOPPED, CAST( CASE WHEN TOLM_TYPE = 18 THEN TOLM_PARTIAL_PERC_FEE ELSE -TOLM_PARTIAL_PERC_FEE END AS int) OPE_PARTIAL_PERC_FEE,
				TOLM_FIXED_FEE, CAST( CASE WHEN TOLM_TYPE = 18 THEN TOLM_PARTIAL_FIXED_FEE ELSE -TOLM_PARTIAL_FIXED_FEE END AS int) OPE_PARTIAL_FIXED_FEE,
				0 OPE_PERC_BONUS, 0 OPE_PARTIAL_BONUS_FEE,
				CAST( CASE WHEN TOLM_TYPE = 18 THEN ISNULL(TOLM_TOTAL_AMOUNT, TOLM_AMOUNT) ELSE -ISNULL(TOLM_TOTAL_AMOUNT, TOLM_AMOUNT) END AS int) OPE_TOTAL_AMOUNT,
				NULL OPE_CUSPMR_TYPE, NULL OPE_CUSPMR_PAGATELIA_NEW_BALANCE, NULL OPE_TIME_BALANCE_USED, NULL OPE_TIME_BALANCE_BEFORE, NULL OPE_POSTPAY, 0 OPE_SHOPKEEPER_OP, 0 OPE_SHOPKEEPER_AMOUNT, 0 OPE_SHOPKEEPER_PROFIT,
				INSTALLATIONS.INS_STANDARD_CITY_ID,
				NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
						 NULL, NULL,
						 NULL, NULL
FROM            dbo.TOLL_MOVEMENTS LEFT OUTER JOIN
                         dbo.USER_PLATES ON dbo.TOLL_MOVEMENTS.TOLM_USRP_ID = USER_PLATES.USRP_ID INNER JOIN
                         dbo.CURRENCIES CUR1 ON TOLM_AMOUNT_CUR_ID = CUR1.CUR_ID INNER JOIN
                         dbo.CURRENCIES CUR2 ON TOLM_BALANCE_CUR_ID = CUR2.CUR_ID LEFT OUTER JOIN
                         dbo.CUSTOMER_PAYMENT_MEANS_RECHARGES ON dbo.TOLL_MOVEMENTS.TOLM_CUSPMR_ID = CUSTOMER_PAYMENT_MEANS_RECHARGES.CUSPMR_ID LEFT OUTER JOIN                         
                         dbo.CURRENCIES CUR3 ON CUSPMR_CUR_ID = CUR3.CUR_ID LEFT OUTER JOIN
                         dbo.USERS ON TOLM_USR_ID = USR_ID LEFT OUTER JOIN
                         dbo.TOLLS ON TOLM_TOL_ID = TOL_ID, INSTALLATIONS
WHERE        TOLM_INS_ID = INS_ID













GO


