SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BSREDSYS_CONFIGURATION](
	[BSRCON_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[BSRCON_GUID] [varchar](100) NOT NULL,
	[BSRCON_FORM_URL] [varchar](255) NOT NULL,
	[BSRCON_WS_URL] [varchar](255) NOT NULL,
	[BSRCON_MERCHANT_CODE] [int] NOT NULL,
	[BSRCON_MERCHANT_SIGNATURE] [varchar](255) NOT NULL,
	[BSRCON_MERCHANT_TERMINAL] [varchar](3) NOT NULL,
	[BSRCON_SERVICE_TIMEOUT] [int] NOT NULL,
	[BSRCON_CHECK_DATE_AND_HASH] [int] NOT NULL,
	[BSRCON_CONFIRMATION_TIME] [int] NOT NULL,
	[BSRCON_HASH_SEED] [varchar](100) NOT NULL,
 CONSTRAINT [PK_BSREDSYS_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[BSRCON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BSREDSYS_CONFIGURATION] ADD  CONSTRAINT [DF_BSREDSYS_CONFIGURATION_IECCON_CHECK_DATE_AND_HASH]  DEFAULT ((1)) FOR [BSRCON_CHECK_DATE_AND_HASH]
GO

ALTER TABLE [dbo].[BSREDSYS_CONFIGURATION] ADD  CONSTRAINT [DF_BSREDSYS_CONFIGURATION_IECCON_CONFIRMATION_TIME]  DEFAULT ((300)) FOR [BSRCON_CONFIRMATION_TIME]
GO

ALTER TABLE [dbo].[BSREDSYS_CONFIGURATION] ADD  CONSTRAINT [DF_BSREDSYS_CONFIGURATION_IECCON_HASH_SEED]  DEFAULT ((1)) FOR [BSRCON_HASH_SEED]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Identifier' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Identifier GUID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_GUID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Moneris Form URL' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_FORM_URL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Moneris Form URL' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_WS_URL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Check date and hash or not?' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_CHECK_DATE_AND_HASH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Max Number of seconds to confirm transaction' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_CONFIRMATION_TIME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hash Seed' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BSREDSYS_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'BSRCON_HASH_SEED'
GO




/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BSREDSYS_CONFIGURATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD
	CPTGC_BSRCON_ID numeric(18, 0) NULL
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG ADD CONSTRAINT
	FK_CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG_BSREDSYS_CONFIGURATION FOREIGN KEY
	(
	CPTGC_BSRCON_ID
	) REFERENCES dbo.BSREDSYS_CONFIGURATION
	(
	BSRCON_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CURRENCIES_PAYMENT_TYPE_GATEWAY_CONFIG SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
