CREATE TABLE [dbo].[COUNTRIES_REDIRECTIONS](
	[COURE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COURE_COU_ID] [numeric](18, 0) NOT NULL,
	[COURE_COUNTRY_REDIRECTION_WS_URL] [varchar](500) NULL,
	[COURE_COUNTRY_REDIRECTION_AUTH_HASH_KEY] [varchar](50) NULL,
	[COURE_COUNTRY_REDIRECTION_HTTP_USER] [varchar](50) NULL,
	[COURE_COUNTRY_REDIRECTION_PASSWORD] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[COUNTRIES_REDIRECTIONS]  WITH CHECK ADD  CONSTRAINT [FK_COUNTRIES_REDIRECTIONS_COUNTRIES] FOREIGN KEY([COURE_COU_ID])
REFERENCES [dbo].[COUNTRIES] ([COU_ID])
GO

ALTER TABLE [dbo].[COUNTRIES_REDIRECTIONS] CHECK CONSTRAINT [FK_COUNTRIES_REDIRECTIONS_COUNTRIES]
GO


/********************************************************************/
/***********************REGISTRO DE PRUEBA***************************/
/********************************************************************/
-- INSERT INTO [dbo].[COUNTRIES_REDIRECTIONS]([COURE_COU_ID],[COURE_COUNTRY_REDIRECTION_WS_URL],[COURE_COUNTRY_REDIRECTION_AUTH_HASH_KEY],[COURE_COUNTRY_REDIRECTION_HTTP_USER],[COURE_COUNTRY_REDIRECTION_PASSWORD])
-- VALUES(198,'https://ws-iparksuite.iparkme.com/Dev/TariffComputer.WS/TariffComputer.asmx','C?p@UnfepyvE6>m}?Df;?J]g','integraTariffsPrePro','TkbiY#D/q.')