CREATE TABLE [dbo].[SIGNUP_GUID_COUNTRIES_REDIRECTIONS](
	[SGCR_ID] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[SGCR_SIGNUP_GUID] [varchar](50) NOT NULL,
	[SGCR_COU_ID] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_SIGNUP_GUID_COUNTRIES_REDIRECTIONS] PRIMARY KEY CLUSTERED 
(
	[SGCR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO